! This file was automatically generated by SWIG (http://www.swig.org).
! Version 4.0.0
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.
module fortpetra
 use, intrinsic :: ISO_C_BINDING
 use forteuchos
 implicit none

 ! PUBLIC METHODS AND TYPES
 public :: ESide
 public :: ETransp
 public :: EUplo
 public :: EDiag
 public :: EType
 public :: ArithTraitsScalar
 public :: LocalGlobal, LocallyReplicated, GloballyDistributed
 public :: LookupStatus, AllIDsPresent, IDNotPresent
 public :: ProfileType, StaticProfile, DynamicProfile
 public :: OptimizeOption, DoOptimizeStorage, DoNotOptimizeStorage
 public :: EPrivateComputeViewConstructor, COMPUTE_VIEW_CONSTRUCTOR
 public :: EPrivateHostViewConstructor, HOST_VIEW_CONSTRUCTOR
 public :: ESweepDirection, Forward, Backward, Symmetric
 public :: TpetraMap
 ! TYPES
 enum, bind(c)
  enumerator :: ESide = -1
 end enum
 enum, bind(c)
  enumerator :: ETransp = -1
 end enum
 enum, bind(c)
  enumerator :: EUplo = -1
 end enum
 enum, bind(c)
  enumerator :: EDiag = -1
 end enum
 enum, bind(c)
  enumerator :: EType = -1
 end enum
 type :: ArithTraitsScalar
  ! These should be treated as PROTECTED data
  type(C_PTR), public :: swigptr = C_NULL_PTR
  logical, public :: swigown = .false.
 contains
  procedure :: create => swigf_new_ArithTraitsScalar
  procedure :: release => swigf_delete_ArithTraitsScalar
 end type
 enum, bind(c)
  enumerator :: LocalGlobal = -1
  enumerator :: LocallyReplicated = 0
  enumerator :: GloballyDistributed = LocallyReplicated + 1
 end enum
 enum, bind(c)
  enumerator :: LookupStatus = -1
  enumerator :: AllIDsPresent = 0
  enumerator :: IDNotPresent = AllIDsPresent + 1
 end enum
 enum, bind(c)
  enumerator :: ProfileType = -1
  enumerator :: StaticProfile = 0
  enumerator :: DynamicProfile = StaticProfile + 1
 end enum
 enum, bind(c)
  enumerator :: OptimizeOption = -1
  enumerator :: DoOptimizeStorage = 0
  enumerator :: DoNotOptimizeStorage = DoOptimizeStorage + 1
 end enum
 enum, bind(c)
  enumerator :: EPrivateComputeViewConstructor = -1
  enumerator :: COMPUTE_VIEW_CONSTRUCTOR = 0
 end enum
 enum, bind(c)
  enumerator :: EPrivateHostViewConstructor = -1
  enumerator :: HOST_VIEW_CONSTRUCTOR = 0
 end enum
 enum, bind(c)
  enumerator :: ESweepDirection = -1
  enumerator :: Forward = 0
  enumerator :: Backward = Forward + 1
  enumerator :: Symmetric = Backward + 1
 end enum
 type :: TpetraMap
  type(C_PTR), public :: swigptr = C_NULL_PTR
 contains
  procedure, private :: create__SWIG_0 => swigf_new_TpetraMap__SWIG_0
  procedure, private :: create__SWIG_1 => swigf_new_TpetraMap__SWIG_1
  procedure, private :: create__SWIG_2 => swigf_new_TpetraMap__SWIG_2
  procedure, private :: create__SWIG_3 => swigf_new_TpetraMap__SWIG_3
  procedure, private :: create__SWIG_4 => swigf_new_TpetraMap__SWIG_4
  procedure, private :: create__SWIG_5 => swigf_new_TpetraMap__SWIG_5
  procedure :: release => swigf_delete_TpetraMap
  procedure :: isOneToOne => swigf_TpetraMap_isOneToOne
  procedure :: getGlobalNumElements => swigf_TpetraMap_getGlobalNumElements
  procedure :: getNodeNumElements => swigf_TpetraMap_getNodeNumElements
  procedure :: getIndexBase => swigf_TpetraMap_getIndexBase
  procedure :: getMinLocalIndex => swigf_TpetraMap_getMinLocalIndex
  procedure :: getMaxLocalIndex => swigf_TpetraMap_getMaxLocalIndex
  procedure :: getMinGlobalIndex => swigf_TpetraMap_getMinGlobalIndex
  procedure :: getMaxGlobalIndex => swigf_TpetraMap_getMaxGlobalIndex
  procedure :: getMinAllGlobalIndex => swigf_TpetraMap_getMinAllGlobalIndex
  procedure :: getMaxAllGlobalIndex => swigf_TpetraMap_getMaxAllGlobalIndex
  procedure :: getLocalElement => swigf_TpetraMap_getLocalElement
  procedure :: getGlobalElement => swigf_TpetraMap_getGlobalElement
  procedure, private :: getRemoteIndexList__SWIG_0 => swigf_TpetraMap_getRemoteIndexList__SWIG_0
  procedure, private :: getRemoteIndexList__SWIG_1 => swigf_TpetraMap_getRemoteIndexList__SWIG_1
  procedure :: getNodeElementList => swigf_TpetraMap_getNodeElementList
  procedure :: isNodeLocalElement => swigf_TpetraMap_isNodeLocalElement
  procedure :: isNodeGlobalElement => swigf_TpetraMap_isNodeGlobalElement
  procedure :: isUniform => swigf_TpetraMap_isUniform
  procedure :: isContiguous => swigf_TpetraMap_isContiguous
  procedure :: isDistributed => swigf_TpetraMap_isDistributed
  procedure :: isCompatible => swigf_TpetraMap_isCompatible
  procedure :: isSameAs => swigf_TpetraMap_isSameAs
  procedure :: locallySameAs => swigf_TpetraMap_locallySameAs
  procedure :: getComm => swigf_TpetraMap_getComm
  procedure :: description => swigf_TpetraMap_description
  procedure, private :: swigf_assign_TpetraMap
  generic :: create => create__SWIG_0, create__SWIG_1, create__SWIG_2, create__SWIG_3, create__SWIG_4, create__SWIG_5
  generic :: assignment(=) => swigf_assign_TpetraMap
  generic :: getRemoteIndexList => getRemoteIndexList__SWIG_0, getRemoteIndexList__SWIG_1
 end type

 ! WRAPPER DECLARATIONS
 private
 interface
  function swigc_new_ArithTraitsScalar() &
     bind(C, name="swigc_new_ArithTraitsScalar") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   type(C_PTR) :: fresult
  end function
  subroutine swigc_delete_ArithTraitsScalar(farg1) &
     bind(C, name="swigc_delete_ArithTraitsScalar")
   use, intrinsic :: ISO_C_BINDING
   type(C_PTR), value :: farg1
  end subroutine
  function swigc_new_TpetraMap__SWIG_0(farg1, farg2, farg3, farg4) &
     bind(C, name="swigc_new_TpetraMap__SWIG_0") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   type(C_PTR) :: fresult
   integer(C_LONG), intent(in) :: farg1
   integer(C_INT), intent(in) :: farg2
   type(C_PTR), value :: farg3
   integer(C_INT), intent(in) :: farg4
  end function
  function swigc_new_TpetraMap__SWIG_1(farg1, farg2, farg3) &
     bind(C, name="swigc_new_TpetraMap__SWIG_1") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   type(C_PTR) :: fresult
   integer(C_LONG), intent(in) :: farg1
   integer(C_INT), intent(in) :: farg2
   type(C_PTR), value :: farg3
  end function
  function swigc_new_TpetraMap__SWIG_2(farg1, farg2, farg3, farg4) &
     bind(C, name="swigc_new_TpetraMap__SWIG_2") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   type(C_PTR) :: fresult
   integer(C_LONG), intent(in) :: farg1
   integer(C_SIZE_T), intent(in) :: farg2
   integer(C_INT), intent(in) :: farg3
   type(C_PTR), value :: farg4
  end function
  function swigc_new_TpetraMap__SWIG_3(farg1, farg2, farg3, farg4, farg5) &
     bind(C, name="swigc_new_TpetraMap__SWIG_3") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   type(C_PTR) :: fresult
   integer(C_LONG), intent(in) :: farg1
   integer(C_INT), dimension(*), intent(in) :: farg2
   integer(C_INT), intent(in) :: farg3
   integer(C_INT), intent(in) :: farg4
   type(C_PTR), value :: farg5
  end function
  function swigc_new_TpetraMap__SWIG_4(farg1, farg2, farg3, farg4) &
     bind(C, name="swigc_new_TpetraMap__SWIG_4") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   type(C_PTR) :: fresult
   integer(C_LONG), intent(in) :: farg1
   type(C_PTR), value :: farg2
   integer(C_INT), intent(in) :: farg3
   type(C_PTR), value :: farg4
  end function
  function swigc_new_TpetraMap__SWIG_5() &
     bind(C, name="swigc_new_TpetraMap__SWIG_5") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   type(C_PTR) :: fresult
  end function
  subroutine swigc_delete_TpetraMap(farg1) &
     bind(C, name="swigc_delete_TpetraMap")
   use, intrinsic :: ISO_C_BINDING
   type(C_PTR), value :: farg1
  end subroutine
  function swigc_TpetraMap_isOneToOne(farg1) &
     bind(C, name="swigc_TpetraMap_isOneToOne") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   logical(C_BOOL) :: fresult
   type(C_PTR), value :: farg1
  end function
  function swigc_TpetraMap_getGlobalNumElements(farg1) &
     bind(C, name="swigc_TpetraMap_getGlobalNumElements") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   integer(C_LONG) :: fresult
   type(C_PTR), value :: farg1
  end function
  function swigc_TpetraMap_getNodeNumElements(farg1) &
     bind(C, name="swigc_TpetraMap_getNodeNumElements") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   integer(C_SIZE_T) :: fresult
   type(C_PTR), value :: farg1
  end function
  function swigc_TpetraMap_getIndexBase(farg1) &
     bind(C, name="swigc_TpetraMap_getIndexBase") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   integer(C_INT) :: fresult
   type(C_PTR), value :: farg1
  end function
  function swigc_TpetraMap_getMinLocalIndex(farg1) &
     bind(C, name="swigc_TpetraMap_getMinLocalIndex") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   integer(C_INT) :: fresult
   type(C_PTR), value :: farg1
  end function
  function swigc_TpetraMap_getMaxLocalIndex(farg1) &
     bind(C, name="swigc_TpetraMap_getMaxLocalIndex") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   integer(C_INT) :: fresult
   type(C_PTR), value :: farg1
  end function
  function swigc_TpetraMap_getMinGlobalIndex(farg1) &
     bind(C, name="swigc_TpetraMap_getMinGlobalIndex") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   integer(C_INT) :: fresult
   type(C_PTR), value :: farg1
  end function
  function swigc_TpetraMap_getMaxGlobalIndex(farg1) &
     bind(C, name="swigc_TpetraMap_getMaxGlobalIndex") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   integer(C_INT) :: fresult
   type(C_PTR), value :: farg1
  end function
  function swigc_TpetraMap_getMinAllGlobalIndex(farg1) &
     bind(C, name="swigc_TpetraMap_getMinAllGlobalIndex") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   integer(C_INT) :: fresult
   type(C_PTR), value :: farg1
  end function
  function swigc_TpetraMap_getMaxAllGlobalIndex(farg1) &
     bind(C, name="swigc_TpetraMap_getMaxAllGlobalIndex") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   integer(C_INT) :: fresult
   type(C_PTR), value :: farg1
  end function
  function swigc_TpetraMap_getLocalElement(farg1, farg2) &
     bind(C, name="swigc_TpetraMap_getLocalElement") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   integer(C_INT) :: fresult
   type(C_PTR), value :: farg1
   integer(C_INT), intent(in) :: farg2
  end function
  function swigc_TpetraMap_getGlobalElement(farg1, farg2) &
     bind(C, name="swigc_TpetraMap_getGlobalElement") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   integer(C_INT) :: fresult
   type(C_PTR), value :: farg1
   integer(C_INT), intent(in) :: farg2
  end function
  function swigc_TpetraMap_getRemoteIndexList__SWIG_0(farg1, farg2, farg3, farg4) &
     bind(C, name="swigc_TpetraMap_getRemoteIndexList__SWIG_0") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   integer(C_INT) :: fresult
   type(C_PTR), value :: farg1
   type(C_PTR), value :: farg2
   type(C_PTR), value :: farg3
   type(C_PTR), value :: farg4
  end function
  function swigc_TpetraMap_getRemoteIndexList__SWIG_1(farg1, farg2, farg3) &
     bind(C, name="swigc_TpetraMap_getRemoteIndexList__SWIG_1") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   integer(C_INT) :: fresult
   type(C_PTR), value :: farg1
   type(C_PTR), value :: farg2
   type(C_PTR), value :: farg3
  end function
  function swigc_TpetraMap_getNodeElementList(farg1) &
     bind(C, name="swigc_TpetraMap_getNodeElementList") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   type(C_PTR) :: fresult
   type(C_PTR), value :: farg1
  end function
  function swigc_TpetraMap_isNodeLocalElement(farg1, farg2) &
     bind(C, name="swigc_TpetraMap_isNodeLocalElement") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   logical(C_BOOL) :: fresult
   type(C_PTR), value :: farg1
   integer(C_INT), intent(in) :: farg2
  end function
  function swigc_TpetraMap_isNodeGlobalElement(farg1, farg2) &
     bind(C, name="swigc_TpetraMap_isNodeGlobalElement") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   logical(C_BOOL) :: fresult
   type(C_PTR), value :: farg1
   integer(C_INT), intent(in) :: farg2
  end function
  function swigc_TpetraMap_isUniform(farg1) &
     bind(C, name="swigc_TpetraMap_isUniform") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   logical(C_BOOL) :: fresult
   type(C_PTR), value :: farg1
  end function
  function swigc_TpetraMap_isContiguous(farg1) &
     bind(C, name="swigc_TpetraMap_isContiguous") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   logical(C_BOOL) :: fresult
   type(C_PTR), value :: farg1
  end function
  function swigc_TpetraMap_isDistributed(farg1) &
     bind(C, name="swigc_TpetraMap_isDistributed") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   logical(C_BOOL) :: fresult
   type(C_PTR), value :: farg1
  end function
  function swigc_TpetraMap_isCompatible(farg1, farg2) &
     bind(C, name="swigc_TpetraMap_isCompatible") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   logical(C_BOOL) :: fresult
   type(C_PTR), value :: farg1
   type(C_PTR), value :: farg2
  end function
  function swigc_TpetraMap_isSameAs(farg1, farg2) &
     bind(C, name="swigc_TpetraMap_isSameAs") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   logical(C_BOOL) :: fresult
   type(C_PTR), value :: farg1
   type(C_PTR), value :: farg2
  end function
  function swigc_TpetraMap_locallySameAs(farg1, farg2) &
     bind(C, name="swigc_TpetraMap_locallySameAs") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   logical(C_BOOL) :: fresult
   type(C_PTR), value :: farg1
   type(C_PTR), value :: farg2
  end function
  function swigc_TpetraMap_getComm(farg1) &
     bind(C, name="swigc_TpetraMap_getComm") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   type(C_PTR) :: fresult
   type(C_PTR), value :: farg1
  end function
  function swigc_TpetraMap_description(farg1) &
     bind(C, name="swigc_TpetraMap_description") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   type(C_PTR) :: fresult
   type(C_PTR), value :: farg1
  end function
  function swigc_spcopy_TpetraMap(farg1) &
     bind(C, name="swigc_spcopy_TpetraMap") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   type(C_PTR) :: fresult
   type(C_PTR), value :: farg1
  end function
 end interface

contains
  ! FORTRAN PROXY CODE
  subroutine swigf_new_ArithTraitsScalar(self)
   use, intrinsic :: ISO_C_BINDING
   class(ArithTraitsScalar) :: self
   if (c_associated(self%swigptr)) call self%release()
   self%swigptr = swigc_new_ArithTraitsScalar()
   self%swigown = .true.
  end subroutine
  subroutine swigf_delete_ArithTraitsScalar(self)
   use, intrinsic :: ISO_C_BINDING
   class(ArithTraitsScalar) :: self
   if (self%swigown) then
    call swigc_delete_ArithTraitsScalar(self%swigptr)
    self%swigown = .false.
   end if
   self%swigptr = C_NULL_PTR
  end subroutine
  subroutine swigf_new_TpetraMap__SWIG_0(self, numGlobalElements, indexBase, comm, lg)
   use, intrinsic :: ISO_C_BINDING
   class(TpetraMap) :: self
   integer(C_LONG), intent(in) :: numGlobalElements
   integer(C_INT), intent(in) :: indexBase
   type(TeuchosComm) :: comm
   integer(kind(LocalGlobal)) :: lg
   if (c_associated(self%swigptr)) call self%release()
   self%swigptr = swigc_new_TpetraMap__SWIG_0(numGlobalElements, indexBase, comm%swigptr, lg)
  end subroutine
  subroutine swigf_new_TpetraMap__SWIG_1(self, numGlobalElements, indexBase, comm)
   use, intrinsic :: ISO_C_BINDING
   class(TpetraMap) :: self
   integer(C_LONG), intent(in) :: numGlobalElements
   integer(C_INT), intent(in) :: indexBase
   type(TeuchosComm) :: comm
   if (c_associated(self%swigptr)) call self%release()
   self%swigptr = swigc_new_TpetraMap__SWIG_1(numGlobalElements, indexBase, comm%swigptr)
  end subroutine
  subroutine swigf_new_TpetraMap__SWIG_2(self, numGlobalElements, numLocalElements, indexBase, comm)
   use, intrinsic :: ISO_C_BINDING
   class(TpetraMap) :: self
   integer(C_LONG), intent(in) :: numGlobalElements
   integer(C_SIZE_T), intent(in) :: numLocalElements
   integer(C_INT), intent(in) :: indexBase
   type(TeuchosComm) :: comm
   if (c_associated(self%swigptr)) call self%release()
   self%swigptr = swigc_new_TpetraMap__SWIG_2(numGlobalElements, numLocalElements, indexBase, comm%swigptr)
  end subroutine
  subroutine swigf_new_TpetraMap__SWIG_3(self, numGlobalElements, indexList, indexListSize, indexBase, comm)
   use, intrinsic :: ISO_C_BINDING
   class(TpetraMap) :: self
   integer(C_LONG), intent(in) :: numGlobalElements
   integer(C_INT), dimension(:), intent(in) :: indexList
   integer(C_INT), intent(in) :: indexListSize
   integer(C_INT), intent(in) :: indexBase
   type(TeuchosComm) :: comm
   if (c_associated(self%swigptr)) call self%release()
   self%swigptr = swigc_new_TpetraMap__SWIG_3(numGlobalElements, indexList, indexListSize, indexBase, comm%swigptr)
  end subroutine
  subroutine swigf_new_TpetraMap__SWIG_4(self, numGlobalElements, indexList, indexBase, comm)
   use, intrinsic :: ISO_C_BINDING
   class(TpetraMap) :: self
   integer(C_LONG), intent(in) :: numGlobalElements
   class(TeuchosArrayViewIntConst) :: indexList
   integer(C_INT), intent(in) :: indexBase
   type(TeuchosComm) :: comm
   if (c_associated(self%swigptr)) call self%release()
   self%swigptr = swigc_new_TpetraMap__SWIG_4(numGlobalElements, indexList%swigptr, indexBase, comm%swigptr)
  end subroutine
  subroutine swigf_new_TpetraMap__SWIG_5(self)
   use, intrinsic :: ISO_C_BINDING
   class(TpetraMap) :: self
   if (c_associated(self%swigptr)) call self%release()
   self%swigptr = swigc_new_TpetraMap__SWIG_5()
  end subroutine
  subroutine swigf_delete_TpetraMap(self)
   use, intrinsic :: ISO_C_BINDING
   class(TpetraMap) :: self
   call swigc_delete_TpetraMap(self%swigptr)
   self%swigptr = C_NULL_PTR
  end subroutine
  function swigf_TpetraMap_isOneToOne(self) &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   logical(C_BOOL) :: fresult
   class(TpetraMap) :: self
   fresult = swigc_TpetraMap_isOneToOne(self%swigptr)
  end function
  function swigf_TpetraMap_getGlobalNumElements(self) &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   integer(C_LONG) :: fresult
   class(TpetraMap) :: self
   fresult = swigc_TpetraMap_getGlobalNumElements(self%swigptr)
  end function
  function swigf_TpetraMap_getNodeNumElements(self) &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   integer(C_SIZE_T) :: fresult
   class(TpetraMap) :: self
   fresult = swigc_TpetraMap_getNodeNumElements(self%swigptr)
  end function
  function swigf_TpetraMap_getIndexBase(self) &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   integer(C_INT) :: fresult
   class(TpetraMap) :: self
   fresult = swigc_TpetraMap_getIndexBase(self%swigptr)
  end function
  function swigf_TpetraMap_getMinLocalIndex(self) &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   integer(C_INT) :: fresult
   class(TpetraMap) :: self
   fresult = swigc_TpetraMap_getMinLocalIndex(self%swigptr)
  end function
  function swigf_TpetraMap_getMaxLocalIndex(self) &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   integer(C_INT) :: fresult
   class(TpetraMap) :: self
   fresult = swigc_TpetraMap_getMaxLocalIndex(self%swigptr)
  end function
  function swigf_TpetraMap_getMinGlobalIndex(self) &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   integer(C_INT) :: fresult
   class(TpetraMap) :: self
   fresult = swigc_TpetraMap_getMinGlobalIndex(self%swigptr)
  end function
  function swigf_TpetraMap_getMaxGlobalIndex(self) &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   integer(C_INT) :: fresult
   class(TpetraMap) :: self
   fresult = swigc_TpetraMap_getMaxGlobalIndex(self%swigptr)
  end function
  function swigf_TpetraMap_getMinAllGlobalIndex(self) &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   integer(C_INT) :: fresult
   class(TpetraMap) :: self
   fresult = swigc_TpetraMap_getMinAllGlobalIndex(self%swigptr)
  end function
  function swigf_TpetraMap_getMaxAllGlobalIndex(self) &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   integer(C_INT) :: fresult
   class(TpetraMap) :: self
   fresult = swigc_TpetraMap_getMaxAllGlobalIndex(self%swigptr)
  end function
  function swigf_TpetraMap_getLocalElement(self, globalIndex) &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   integer(C_INT) :: fresult
   class(TpetraMap) :: self
   integer(C_INT), intent(in) :: globalIndex
   fresult = swigc_TpetraMap_getLocalElement(self%swigptr, globalIndex)
  end function
  function swigf_TpetraMap_getGlobalElement(self, localIndex) &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   integer(C_INT) :: fresult
   class(TpetraMap) :: self
   integer(C_INT), intent(in) :: localIndex
   fresult = swigc_TpetraMap_getGlobalElement(self%swigptr, localIndex)
  end function
  function swigf_TpetraMap_getRemoteIndexList__SWIG_0(self, GIDList, nodeIDList, LIDList) &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   integer(kind(LookupStatus)) :: fresult
   class(TpetraMap) :: self
   class(TeuchosArrayViewIntConst) :: GIDList
   class(TeuchosArrayViewInt) :: nodeIDList
   class(TeuchosArrayViewInt) :: LIDList
   fresult = swigc_TpetraMap_getRemoteIndexList__SWIG_0(self%swigptr, GIDList%swigptr, nodeIDList%swigptr, LIDList%swigptr)
  end function
  function swigf_TpetraMap_getRemoteIndexList__SWIG_1(self, GIDList, nodeIDList) &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   integer(kind(LookupStatus)) :: fresult
   class(TpetraMap) :: self
   class(TeuchosArrayViewIntConst) :: GIDList
   class(TeuchosArrayViewInt) :: nodeIDList
   fresult = swigc_TpetraMap_getRemoteIndexList__SWIG_1(self%swigptr, GIDList%swigptr, nodeIDList%swigptr)
  end function
  function swigf_TpetraMap_getNodeElementList(self) &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   type(TeuchosArrayViewIntConst) :: fresult
   class(TpetraMap) :: self
   fresult%swigptr = swigc_TpetraMap_getNodeElementList(self%swigptr)
  end function
  function swigf_TpetraMap_isNodeLocalElement(self, localIndex) &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   logical(C_BOOL) :: fresult
   class(TpetraMap) :: self
   integer(C_INT), intent(in) :: localIndex
   fresult = swigc_TpetraMap_isNodeLocalElement(self%swigptr, localIndex)
  end function
  function swigf_TpetraMap_isNodeGlobalElement(self, globalIndex) &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   logical(C_BOOL) :: fresult
   class(TpetraMap) :: self
   integer(C_INT), intent(in) :: globalIndex
   fresult = swigc_TpetraMap_isNodeGlobalElement(self%swigptr, globalIndex)
  end function
  function swigf_TpetraMap_isUniform(self) &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   logical(C_BOOL) :: fresult
   class(TpetraMap) :: self
   fresult = swigc_TpetraMap_isUniform(self%swigptr)
  end function
  function swigf_TpetraMap_isContiguous(self) &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   logical(C_BOOL) :: fresult
   class(TpetraMap) :: self
   fresult = swigc_TpetraMap_isContiguous(self%swigptr)
  end function
  function swigf_TpetraMap_isDistributed(self) &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   logical(C_BOOL) :: fresult
   class(TpetraMap) :: self
   fresult = swigc_TpetraMap_isDistributed(self%swigptr)
  end function
  function swigf_TpetraMap_isCompatible(self, map) &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   logical(C_BOOL) :: fresult
   class(TpetraMap) :: self
   class(TpetraMap) :: map
   fresult = swigc_TpetraMap_isCompatible(self%swigptr, map%swigptr)
  end function
  function swigf_TpetraMap_isSameAs(self, map) &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   logical(C_BOOL) :: fresult
   class(TpetraMap) :: self
   class(TpetraMap) :: map
   fresult = swigc_TpetraMap_isSameAs(self%swigptr, map%swigptr)
  end function
  function swigf_TpetraMap_locallySameAs(self, map) &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   logical(C_BOOL) :: fresult
   class(TpetraMap) :: self
   class(TpetraMap) :: map
   fresult = swigc_TpetraMap_locallySameAs(self%swigptr, map%swigptr)
  end function
  function swigf_TpetraMap_getComm(self) &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   type(TeuchosComm) :: fresult
   class(TpetraMap) :: self
   fresult%swigptr = swigc_TpetraMap_getComm(self%swigptr)
  end function
  function swigf_TpetraMap_description(self) &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   type(string) :: fresult
   class(TpetraMap) :: self
   fresult%swigptr = swigc_TpetraMap_description(self%swigptr)
   fresult%swigown = .true.
  end function
  subroutine swigf_assign_TpetraMap(self, other)
   use, intrinsic :: ISO_C_BINDING
   class(TpetraMap), intent(inout) :: self
   type(TpetraMap), intent(in) :: other
   call self%release()
   self%swigptr = swigc_spcopy_TpetraMap(other%swigptr)
  end subroutine
end module fortpetra
