TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
  LIB_REQUIRED_PACKAGES
    Anasazi
    NOX
    Stratimikos
    Teuchos
    Thyra
    ThyraTpetraAdapters
    Tpetra
    ForTrilinosTeuchos
    ForTrilinosTpetra
    ForTrilinosUtils
  LIB_OPTIONAL_PACKAGES
    Ifpack2
    MueLu
  TEST_OPTIONAL_PACKAGES
    Belos
    Ifpack2
    MueLu
)
