! This file was automatically generated by SWIG (http://www.swig.org).
! Version 4.0.0
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.

! Copyright 2017-2018, UT-Battelle, LLC
!
! SPDX-License-Identifier: BSD-3-Clause
! License-Filename: LICENSE

module forteuchos
 use, intrinsic :: ISO_C_BINDING
 use forerror
 implicit none
 private

 ! DECLARATION CONSTRUCTS
 ! enum Teuchos::ESide
 enum, bind(c)
  enumerator :: TeuchosLEFT_SIDE
  enumerator :: TeuchosRIGHT_SIDE
 end enum
 integer, parameter, public :: TeuchosESide = kind(TeuchosLEFT_SIDE)
 public :: TeuchosLEFT_SIDE, TeuchosRIGHT_SIDE
 ! enum Teuchos::ETransp
 enum, bind(c)
  enumerator :: TeuchosNO_TRANS
  enumerator :: TeuchosTRANS
  enumerator :: TeuchosCONJ_TRANS
 end enum
 integer, parameter, public :: TeuchosETransp = kind(TeuchosNO_TRANS)
 public :: TeuchosNO_TRANS, TeuchosTRANS, TeuchosCONJ_TRANS
 ! enum Teuchos::EUplo
 enum, bind(c)
  enumerator :: TeuchosUPPER_TRI
  enumerator :: TeuchosLOWER_TRI
  enumerator :: TeuchosUNDEF_TRI
 end enum
 integer, parameter, public :: TeuchosEUplo = kind(TeuchosUPPER_TRI)
 public :: TeuchosUPPER_TRI, TeuchosLOWER_TRI, TeuchosUNDEF_TRI
 ! enum Teuchos::EDiag
 enum, bind(c)
  enumerator :: TeuchosUNIT_DIAG
  enumerator :: TeuchosNON_UNIT_DIAG
 end enum
 integer, parameter, public :: TeuchosEDiag = kind(TeuchosUNIT_DIAG)
 public :: TeuchosUNIT_DIAG, TeuchosNON_UNIT_DIAG
 ! enum Teuchos::EType
 enum, bind(c)
  enumerator :: TeuchosFULL
  enumerator :: TeuchosLOWER
  enumerator :: TeuchosUPPER
  enumerator :: TeuchosHESSENBERG
  enumerator :: TeuchosSYM_BAND_L
  enumerator :: TeuchosSYM_BAND_U
  enumerator :: TeuchosBAND
 end enum
 integer, parameter, public :: TeuchosEType = kind(TeuchosFULL)
 public :: TeuchosFULL, TeuchosLOWER, TeuchosUPPER, TeuchosHESSENBERG, TeuchosSYM_BAND_L, TeuchosSYM_BAND_U, TeuchosBAND
 ! enum Teuchos::DataAccess
 enum, bind(c)
  enumerator :: TeuchosCopy
  enumerator :: TeuchosView
 end enum
 integer, parameter, public :: TeuchosDataAccess = kind(TeuchosCopy)
 public :: TeuchosCopy, TeuchosView
 enum, bind(c)
  enumerator :: SWIG_NULL
  enumerator :: SWIG_OWN
  enumerator :: SWIG_MOVE
  enumerator :: SWIG_REF
  enumerator :: SWIG_CREF
 end enum
 integer, parameter :: SwigMemState = kind(SWIG_NULL)
 type, bind(C) :: SwigClassWrapper
  type(C_PTR), public :: cptr = C_NULL_PTR
  integer(C_INT), public :: mem = SWIG_NULL
 end type
 ! class Teuchos::Comm< int >
 type, public :: TeuchosComm
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure :: getRank => swigf_TeuchosComm_getRank
  procedure :: getSize => swigf_TeuchosComm_getSize
  procedure :: barrier => swigf_TeuchosComm_barrier
  procedure :: getRawMpiComm => swigf_TeuchosComm_getRawMpiComm
  procedure :: release => delete_TeuchosComm
  procedure, private :: swigf_assignment_TeuchosComm
  generic :: assignment(=) => swigf_assignment_TeuchosComm
 end type TeuchosComm
 interface TeuchosComm
  module procedure new_TeuchosComm__SWIG_0
  module procedure new_TeuchosComm__SWIG_1
 end interface
 type, bind(C) :: SwigArrayWrapper
  type(C_PTR), public :: data = C_NULL_PTR
  integer(C_SIZE_T), public :: size = 0
 end type
 ! class Teuchos::ParameterList
 type, public :: ParameterList
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure :: print => swigf_ParameterList_print
  procedure :: remove => swigf_ParameterList_remove
  procedure :: is_parameter => swigf_ParameterList_is_parameter
  procedure :: sublist => swigf_ParameterList_sublist
  procedure, private :: set__SWIG_1 => swigf_ParameterList_set__SWIG_1
  procedure, private :: set__SWIG_2 => swigf_ParameterList_set__SWIG_2
  procedure, private :: set__SWIG_3 => swigf_ParameterList_set__SWIG_3
  procedure, private :: set__SWIG_4 => swigf_ParameterList_set__SWIG_4
  procedure, private :: set__SWIG_5 => swigf_ParameterList_set__SWIG_5
  procedure, private :: set__SWIG_6 => swigf_ParameterList_set__SWIG_6
  procedure, private :: set__SWIG_7 => swigf_ParameterList_set__SWIG_7
  procedure, private :: set__SWIG_8 => swigf_ParameterList_set__SWIG_8
  procedure, private :: set__SWIG_9 => swigf_ParameterList_set__SWIG_9
  procedure :: get_real => swigf_ParameterList_get_real
  procedure :: get_integer => swigf_ParameterList_get_integer
  procedure :: get_longlong => swigf_ParameterList_get_longlong
  procedure :: get_logical => swigf_ParameterList_get_logical
  procedure :: get_string => swigf_ParameterList_get_string
  procedure :: get_arr_real => swigf_ParameterList_get_arr_real
  procedure :: get_arr_integer => swigf_ParameterList_get_arr_integer
  procedure :: get_arr_longlong => swigf_ParameterList_get_arr_longlong
  procedure :: release => delete_ParameterList
  procedure, private :: swigf_assignment_ParameterList
  generic :: assignment(=) => swigf_assignment_ParameterList
  generic :: set => set__SWIG_1, set__SWIG_2, set__SWIG_3, set__SWIG_4, set__SWIG_5, set__SWIG_6, set__SWIG_7, set__SWIG_8, &
    set__SWIG_9
 end type ParameterList
 interface ParameterList
  module procedure new_ParameterList__SWIG_0
  module procedure new_ParameterList__SWIG_1
 end interface
 public :: load_from_xml
 public :: save_to_xml

! WRAPPER DECLARATIONS
interface
function swigc_TeuchosComm_getRank(farg1) &
bind(C, name="_wrap_TeuchosComm_getRank") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT) :: fresult
end function

function swigc_TeuchosComm_getSize(farg1) &
bind(C, name="_wrap_TeuchosComm_getSize") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT) :: fresult
end function

subroutine swigc_TeuchosComm_barrier(farg1) &
bind(C, name="_wrap_TeuchosComm_barrier")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
end subroutine

function swigc_new_TeuchosComm__SWIG_0(farg1) &
bind(C, name="_wrap_new_TeuchosComm__SWIG_0") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
integer(C_INT), intent(in) :: farg1
type(SwigClassWrapper) :: fresult
end function

function swigc_new_TeuchosComm__SWIG_1() &
bind(C, name="_wrap_new_TeuchosComm__SWIG_1") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: fresult
end function

function swigc_TeuchosComm_getRawMpiComm(farg1) &
bind(C, name="_wrap_TeuchosComm_getRawMpiComm") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT) :: fresult
end function

subroutine swigc_delete_TeuchosComm(farg1) &
bind(C, name="_wrap_delete_TeuchosComm")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
end subroutine

  subroutine swigc_assignment_TeuchosComm(self, other) &
     bind(C, name="_wrap_assign_TeuchosComm")
   use, intrinsic :: ISO_C_BINDING
   import :: SwigClassWrapper
   type(SwigClassWrapper), intent(inout) :: self
   type(SwigClassWrapper), intent(in) :: other
  end subroutine
function swigc_new_ParameterList__SWIG_0() &
bind(C, name="_wrap_new_ParameterList__SWIG_0") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: fresult
end function

function swigc_new_ParameterList__SWIG_1(farg1) &
bind(C, name="_wrap_new_ParameterList__SWIG_1") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_ParameterList_print(farg1) &
bind(C, name="_wrap_ParameterList_print")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
end subroutine

subroutine swigc_ParameterList_remove(farg1, farg2) &
bind(C, name="_wrap_ParameterList_remove")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigClassWrapper) :: farg1
type(SwigArrayWrapper) :: farg2
end subroutine

function swigc_ParameterList_is_parameter(farg1, farg2) &
bind(C, name="_wrap_ParameterList_is_parameter") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigClassWrapper) :: farg1
type(SwigArrayWrapper) :: farg2
logical(C_BOOL) :: fresult
end function

function swigc_ParameterList_sublist(farg1, farg2) &
bind(C, name="_wrap_ParameterList_sublist") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigClassWrapper) :: farg1
type(SwigArrayWrapper) :: farg2
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_ParameterList_set__SWIG_1(farg1, farg2, farg3) &
bind(C, name="_wrap_ParameterList_set__SWIG_1")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigClassWrapper) :: farg1
type(SwigArrayWrapper) :: farg2
real(C_DOUBLE), intent(in) :: farg3
end subroutine

subroutine swigc_ParameterList_set__SWIG_2(farg1, farg2, farg3) &
bind(C, name="_wrap_ParameterList_set__SWIG_2")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigClassWrapper) :: farg1
type(SwigArrayWrapper) :: farg2
integer(C_INT), intent(in) :: farg3
end subroutine

subroutine swigc_ParameterList_set__SWIG_3(farg1, farg2, farg3) &
bind(C, name="_wrap_ParameterList_set__SWIG_3")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigClassWrapper) :: farg1
type(SwigArrayWrapper) :: farg2
integer(C_LONG_LONG), intent(in) :: farg3
end subroutine

subroutine swigc_ParameterList_set__SWIG_4(farg1, farg2, farg3) &
bind(C, name="_wrap_ParameterList_set__SWIG_4")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigClassWrapper) :: farg1
type(SwigArrayWrapper) :: farg2
logical(C_BOOL), intent(in) :: farg3
end subroutine

subroutine swigc_ParameterList_set__SWIG_5(farg1, farg2, farg3) &
bind(C, name="_wrap_ParameterList_set__SWIG_5")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigClassWrapper) :: farg1
type(SwigArrayWrapper) :: farg2
type(SwigArrayWrapper) :: farg3
end subroutine

subroutine swigc_ParameterList_set__SWIG_6(farg1, farg2, farg3) &
bind(C, name="_wrap_ParameterList_set__SWIG_6")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigClassWrapper) :: farg1
type(SwigArrayWrapper) :: farg2
type(SwigArrayWrapper) :: farg3
end subroutine

subroutine swigc_ParameterList_set__SWIG_7(farg1, farg2, farg3) &
bind(C, name="_wrap_ParameterList_set__SWIG_7")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigClassWrapper) :: farg1
type(SwigArrayWrapper) :: farg2
type(SwigArrayWrapper) :: farg3
end subroutine

subroutine swigc_ParameterList_set__SWIG_8(farg1, farg2, farg3) &
bind(C, name="_wrap_ParameterList_set__SWIG_8")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigClassWrapper) :: farg1
type(SwigArrayWrapper) :: farg2
type(SwigArrayWrapper) :: farg3
end subroutine

subroutine swigc_ParameterList_set__SWIG_9(farg1, farg2, farg3) &
bind(C, name="_wrap_ParameterList_set__SWIG_9")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigClassWrapper) :: farg1
type(SwigArrayWrapper) :: farg2
type(SwigClassWrapper) :: farg3
end subroutine

function swigc_ParameterList_get_real(farg1, farg2) &
bind(C, name="_wrap_ParameterList_get_real") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigClassWrapper) :: farg1
type(SwigArrayWrapper) :: farg2
real(C_DOUBLE) :: fresult
end function

function swigc_ParameterList_get_integer(farg1, farg2) &
bind(C, name="_wrap_ParameterList_get_integer") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigClassWrapper) :: farg1
type(SwigArrayWrapper) :: farg2
integer(C_INT) :: fresult
end function

function swigc_ParameterList_get_longlong(farg1, farg2) &
bind(C, name="_wrap_ParameterList_get_longlong") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigClassWrapper) :: farg1
type(SwigArrayWrapper) :: farg2
integer(C_LONG_LONG) :: fresult
end function

function swigc_ParameterList_get_logical(farg1, farg2) &
bind(C, name="_wrap_ParameterList_get_logical") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigClassWrapper) :: farg1
type(SwigArrayWrapper) :: farg2
logical(C_BOOL) :: fresult
end function

function swigc_ParameterList_get_string(farg1, farg2) &
bind(C, name="_wrap_ParameterList_get_string") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(SwigArrayWrapper) :: farg2
type(SwigArrayWrapper) :: fresult
end function

function swigc_ParameterList_get_arr_real(farg1, farg2) &
bind(C, name="_wrap_ParameterList_get_arr_real") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(SwigArrayWrapper) :: farg2
type(SwigArrayWrapper) :: fresult
end function

function swigc_ParameterList_get_arr_integer(farg1, farg2) &
bind(C, name="_wrap_ParameterList_get_arr_integer") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(SwigArrayWrapper) :: farg2
type(SwigArrayWrapper) :: fresult
end function

function swigc_ParameterList_get_arr_longlong(farg1, farg2) &
bind(C, name="_wrap_ParameterList_get_arr_longlong") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(SwigArrayWrapper) :: farg2
type(SwigArrayWrapper) :: fresult
end function

subroutine swigc_delete_ParameterList(farg1) &
bind(C, name="_wrap_delete_ParameterList")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
end subroutine

  subroutine swigc_assignment_ParameterList(self, other) &
     bind(C, name="_wrap_assign_ParameterList")
   use, intrinsic :: ISO_C_BINDING
   import :: SwigClassWrapper
   type(SwigClassWrapper), intent(inout) :: self
   type(SwigClassWrapper), intent(in) :: other
  end subroutine
subroutine swigc_load_from_xml(farg1, farg2) &
bind(C, name="_wrap_load_from_xml")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigClassWrapper) :: farg1
type(SwigArrayWrapper) :: farg2
end subroutine

subroutine swigc_save_to_xml(farg1, farg2) &
bind(C, name="_wrap_save_to_xml")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigClassWrapper) :: farg1
type(SwigArrayWrapper) :: farg2
end subroutine

end interface


contains
 ! MODULE SUBPROGRAMS
function swigf_TeuchosComm_getRank(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(TeuchosComm), intent(in) :: self

integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_TeuchosComm_getRank(farg1)
swig_result = fresult
end function

function swigf_TeuchosComm_getSize(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(TeuchosComm), intent(in) :: self

integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_TeuchosComm_getSize(farg1)
swig_result = fresult
end function

subroutine swigf_TeuchosComm_barrier(self)
use, intrinsic :: ISO_C_BINDING
class(TeuchosComm), intent(in) :: self

type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
call swigc_TeuchosComm_barrier(farg1)
end subroutine

function new_TeuchosComm__SWIG_0(rawmpicomm) &
result(self)
use, intrinsic :: ISO_C_BINDING
type(TeuchosComm) :: self
integer :: rawmpicomm

type(SwigClassWrapper) :: fresult 
integer(C_INT) :: farg1 

farg1 = int(rawmpicomm, C_INT)
fresult = swigc_new_TeuchosComm__SWIG_0(farg1)
self%swigdata = fresult
end function

function new_TeuchosComm__SWIG_1() &
result(self)
use, intrinsic :: ISO_C_BINDING
type(TeuchosComm) :: self

type(SwigClassWrapper) :: fresult 

fresult = swigc_new_TeuchosComm__SWIG_1()
self%swigdata = fresult
end function

function swigf_TeuchosComm_getRawMpiComm(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer :: swig_result
class(TeuchosComm), intent(inout) :: self

integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_TeuchosComm_getRawMpiComm(farg1)
swig_result = int(fresult)
end function

subroutine delete_TeuchosComm(self)
use, intrinsic :: ISO_C_BINDING
class(TeuchosComm), intent(inout) :: self

type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
if (self%swigdata%mem == SWIG_OWN) then
call swigc_delete_TeuchosComm(farg1)
end if
self%swigdata%cptr = C_NULL_PTR
self%swigdata%mem = SWIG_NULL
end subroutine

  subroutine swigf_assignment_TeuchosComm(self, other)
   use, intrinsic :: ISO_C_BINDING
   class(TeuchosComm), intent(inout) :: self
   type(TeuchosComm), intent(in) :: other
   call swigc_assignment_TeuchosComm(self%swigdata, other%swigdata)
  end subroutine
function new_ParameterList__SWIG_0() &
result(self)
use, intrinsic :: ISO_C_BINDING
type(ParameterList) :: self

type(SwigClassWrapper) :: fresult 

fresult = swigc_new_ParameterList__SWIG_0()
self%swigdata = fresult
end function


subroutine SWIG_string_to_chararray(string, chars, wrap)
  use, intrinsic :: ISO_C_BINDING
  character(kind=C_CHAR, len=*), intent(IN) :: string
  character(kind=C_CHAR), dimension(:), target, allocatable, intent(OUT) :: chars
  type(SwigArrayWrapper), intent(OUT) :: wrap
  integer :: i

  allocate(character(kind=C_CHAR) :: chars(len(string) + 1))
  do i=1,len(string)
    chars(i) = string(i:i)
  end do
  i = len(string) + 1
  chars(i) = C_NULL_CHAR ! C string compatibility
  wrap%data = c_loc(chars)
  wrap%size = len(string)
end subroutine

function new_ParameterList__SWIG_1(name) &
result(self)
use, intrinsic :: ISO_C_BINDING
type(ParameterList) :: self
character(kind=C_CHAR, len=*), target :: name
character(kind=C_CHAR), dimension(:), allocatable, target :: farg1_chars

type(SwigClassWrapper) :: fresult 
type(SwigArrayWrapper) :: farg1 

call SWIG_string_to_chararray(name, farg1_chars, farg1)
fresult = swigc_new_ParameterList__SWIG_1(farg1)
self%swigdata = fresult
end function

subroutine swigf_ParameterList_print(self)
use, intrinsic :: ISO_C_BINDING
class(ParameterList), intent(in) :: self

type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
call swigc_ParameterList_print(farg1)
end subroutine

subroutine swigf_ParameterList_remove(self, name)
use, intrinsic :: ISO_C_BINDING
class(ParameterList), intent(inout) :: self

character(kind=C_CHAR, len=*), target :: name
character(kind=C_CHAR), dimension(:), allocatable, target :: farg2_chars

type(SwigClassWrapper) :: farg1 
type(SwigArrayWrapper) :: farg2 

farg1 = self%swigdata
call SWIG_string_to_chararray(name, farg2_chars, farg2)
call swigc_ParameterList_remove(farg1, farg2)
end subroutine

function swigf_ParameterList_is_parameter(self, name) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
logical(C_BOOL) :: swig_result
class(ParameterList), intent(in) :: self

character(kind=C_CHAR, len=*), target :: name
character(kind=C_CHAR), dimension(:), allocatable, target :: farg2_chars

logical(C_BOOL) :: fresult 
type(SwigClassWrapper) :: farg1 
type(SwigArrayWrapper) :: farg2 

farg1 = self%swigdata
call SWIG_string_to_chararray(name, farg2_chars, farg2)
fresult = swigc_ParameterList_is_parameter(farg1, farg2)
swig_result = fresult
end function

function swigf_ParameterList_sublist(self, name) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(ParameterList) :: swig_result
class(ParameterList), intent(inout) :: self

character(kind=C_CHAR, len=*), target :: name
character(kind=C_CHAR), dimension(:), allocatable, target :: farg2_chars

type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 
type(SwigArrayWrapper) :: farg2 

farg1 = self%swigdata
call SWIG_string_to_chararray(name, farg2_chars, farg2)
fresult = swigc_ParameterList_sublist(farg1, farg2)
swig_result%swigdata = fresult
end function

subroutine swigf_ParameterList_set__SWIG_1(self, name, value)
use, intrinsic :: ISO_C_BINDING
class(ParameterList), intent(inout) :: self

character(kind=C_CHAR, len=*), target :: name
character(kind=C_CHAR), dimension(:), allocatable, target :: farg2_chars
real(C_DOUBLE), intent(in) :: value

type(SwigClassWrapper) :: farg1 
type(SwigArrayWrapper) :: farg2 
real(C_DOUBLE) :: farg3 

farg1 = self%swigdata
call SWIG_string_to_chararray(name, farg2_chars, farg2)
farg3 = value
call swigc_ParameterList_set__SWIG_1(farg1, farg2, farg3)
end subroutine

subroutine swigf_ParameterList_set__SWIG_2(self, name, value)
use, intrinsic :: ISO_C_BINDING
class(ParameterList), intent(inout) :: self

character(kind=C_CHAR, len=*), target :: name
character(kind=C_CHAR), dimension(:), allocatable, target :: farg2_chars
integer(C_INT), intent(in) :: value

type(SwigClassWrapper) :: farg1 
type(SwigArrayWrapper) :: farg2 
integer(C_INT) :: farg3 

farg1 = self%swigdata
call SWIG_string_to_chararray(name, farg2_chars, farg2)
farg3 = value
call swigc_ParameterList_set__SWIG_2(farg1, farg2, farg3)
end subroutine

subroutine swigf_ParameterList_set__SWIG_3(self, name, value)
use, intrinsic :: ISO_C_BINDING
class(ParameterList), intent(inout) :: self

character(kind=C_CHAR, len=*), target :: name
character(kind=C_CHAR), dimension(:), allocatable, target :: farg2_chars
integer(C_LONG_LONG), intent(in) :: value

type(SwigClassWrapper) :: farg1 
type(SwigArrayWrapper) :: farg2 
integer(C_LONG_LONG) :: farg3 

farg1 = self%swigdata
call SWIG_string_to_chararray(name, farg2_chars, farg2)
farg3 = value
call swigc_ParameterList_set__SWIG_3(farg1, farg2, farg3)
end subroutine

subroutine swigf_ParameterList_set__SWIG_4(self, name, value)
use, intrinsic :: ISO_C_BINDING
class(ParameterList), intent(inout) :: self

character(kind=C_CHAR, len=*), target :: name
character(kind=C_CHAR), dimension(:), allocatable, target :: farg2_chars
logical(C_BOOL), intent(in) :: value

type(SwigClassWrapper) :: farg1 
type(SwigArrayWrapper) :: farg2 
logical(C_BOOL) :: farg3 

farg1 = self%swigdata
call SWIG_string_to_chararray(name, farg2_chars, farg2)
farg3 = value
call swigc_ParameterList_set__SWIG_4(farg1, farg2, farg3)
end subroutine

subroutine swigf_ParameterList_set__SWIG_5(self, name, value)
use, intrinsic :: ISO_C_BINDING
class(ParameterList), intent(inout) :: self

character(kind=C_CHAR, len=*), target :: name
character(kind=C_CHAR), dimension(:), allocatable, target :: farg2_chars
character(kind=C_CHAR, len=*), target :: value
character(kind=C_CHAR), dimension(:), allocatable, target :: farg3_chars

type(SwigClassWrapper) :: farg1 
type(SwigArrayWrapper) :: farg2 
type(SwigArrayWrapper) :: farg3 

farg1 = self%swigdata
call SWIG_string_to_chararray(name, farg2_chars, farg2)
call SWIG_string_to_chararray(value, farg3_chars, farg3)
call swigc_ParameterList_set__SWIG_5(farg1, farg2, farg3)
end subroutine

subroutine swigf_ParameterList_set__SWIG_6(self, name, value)
use, intrinsic :: ISO_C_BINDING
class(ParameterList), intent(inout) :: self

character(kind=C_CHAR, len=*), target :: name
character(kind=C_CHAR), dimension(:), allocatable, target :: farg2_chars
real(C_DOUBLE), dimension(:), target :: value
real(C_DOUBLE), pointer :: farg3_view

type(SwigClassWrapper) :: farg1 
type(SwigArrayWrapper) :: farg2 
type(SwigArrayWrapper) :: farg3 

farg1 = self%swigdata
call SWIG_string_to_chararray(name, farg2_chars, farg2)
farg3_view => value(1)
farg3%data = c_loc(farg3_view)
farg3%size = size(value)
call swigc_ParameterList_set__SWIG_6(farg1, farg2, farg3)
end subroutine

subroutine swigf_ParameterList_set__SWIG_7(self, name, value)
use, intrinsic :: ISO_C_BINDING
class(ParameterList), intent(inout) :: self

character(kind=C_CHAR, len=*), target :: name
character(kind=C_CHAR), dimension(:), allocatable, target :: farg2_chars
integer(C_INT), dimension(:), target :: value
integer(C_INT), pointer :: farg3_view

type(SwigClassWrapper) :: farg1 
type(SwigArrayWrapper) :: farg2 
type(SwigArrayWrapper) :: farg3 

farg1 = self%swigdata
call SWIG_string_to_chararray(name, farg2_chars, farg2)
farg3_view => value(1)
farg3%data = c_loc(farg3_view)
farg3%size = size(value)
call swigc_ParameterList_set__SWIG_7(farg1, farg2, farg3)
end subroutine

subroutine swigf_ParameterList_set__SWIG_8(self, name, value)
use, intrinsic :: ISO_C_BINDING
class(ParameterList), intent(inout) :: self

character(kind=C_CHAR, len=*), target :: name
character(kind=C_CHAR), dimension(:), allocatable, target :: farg2_chars
integer(C_LONG_LONG), dimension(:), target :: value
integer(C_LONG_LONG), pointer :: farg3_view

type(SwigClassWrapper) :: farg1 
type(SwigArrayWrapper) :: farg2 
type(SwigArrayWrapper) :: farg3 

farg1 = self%swigdata
call SWIG_string_to_chararray(name, farg2_chars, farg2)
farg3_view => value(1)
farg3%data = c_loc(farg3_view)
farg3%size = size(value)
call swigc_ParameterList_set__SWIG_8(farg1, farg2, farg3)
end subroutine

subroutine swigf_ParameterList_set__SWIG_9(self, name, value)
use, intrinsic :: ISO_C_BINDING
class(ParameterList), intent(inout) :: self

character(kind=C_CHAR, len=*), target :: name
character(kind=C_CHAR), dimension(:), allocatable, target :: farg2_chars
class(ParameterList), intent(in) :: value

type(SwigClassWrapper) :: farg1 
type(SwigArrayWrapper) :: farg2 
type(SwigClassWrapper) :: farg3 

farg1 = self%swigdata
call SWIG_string_to_chararray(name, farg2_chars, farg2)
farg3 = value%swigdata
call swigc_ParameterList_set__SWIG_9(farg1, farg2, farg3)
end subroutine

function swigf_ParameterList_get_real(self, name) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE) :: swig_result
class(ParameterList), intent(inout) :: self

character(kind=C_CHAR, len=*), target :: name
character(kind=C_CHAR), dimension(:), allocatable, target :: farg2_chars

real(C_DOUBLE) :: fresult 
type(SwigClassWrapper) :: farg1 
type(SwigArrayWrapper) :: farg2 

farg1 = self%swigdata
call SWIG_string_to_chararray(name, farg2_chars, farg2)
fresult = swigc_ParameterList_get_real(farg1, farg2)
swig_result = fresult
end function

function swigf_ParameterList_get_integer(self, name) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(ParameterList), intent(inout) :: self

character(kind=C_CHAR, len=*), target :: name
character(kind=C_CHAR), dimension(:), allocatable, target :: farg2_chars

integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 
type(SwigArrayWrapper) :: farg2 

farg1 = self%swigdata
call SWIG_string_to_chararray(name, farg2_chars, farg2)
fresult = swigc_ParameterList_get_integer(farg1, farg2)
swig_result = fresult
end function

function swigf_ParameterList_get_longlong(self, name) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_LONG_LONG) :: swig_result
class(ParameterList), intent(inout) :: self

character(kind=C_CHAR, len=*), target :: name
character(kind=C_CHAR), dimension(:), allocatable, target :: farg2_chars

integer(C_LONG_LONG) :: fresult 
type(SwigClassWrapper) :: farg1 
type(SwigArrayWrapper) :: farg2 

farg1 = self%swigdata
call SWIG_string_to_chararray(name, farg2_chars, farg2)
fresult = swigc_ParameterList_get_longlong(farg1, farg2)
swig_result = fresult
end function

function swigf_ParameterList_get_logical(self, name) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
logical(C_BOOL) :: swig_result
class(ParameterList), intent(inout) :: self

character(kind=C_CHAR, len=*), target :: name
character(kind=C_CHAR), dimension(:), allocatable, target :: farg2_chars

logical(C_BOOL) :: fresult 
type(SwigClassWrapper) :: farg1 
type(SwigArrayWrapper) :: farg2 

farg1 = self%swigdata
call SWIG_string_to_chararray(name, farg2_chars, farg2)
fresult = swigc_ParameterList_get_logical(farg1, farg2)
swig_result = fresult
end function


subroutine SWIG_chararray_to_string(wrap, string)
  use, intrinsic :: ISO_C_BINDING
  type(SwigArrayWrapper), intent(IN) :: wrap
  character(kind=C_CHAR, len=:), allocatable, intent(OUT) :: string
  character(kind=C_CHAR), dimension(:), pointer :: chars
  integer(kind=C_SIZE_T) :: i
  call c_f_pointer(wrap%data, chars, [wrap%size])
  allocate(character(kind=C_CHAR, len=wrap%size) :: string)
  do i=1, wrap%size
    string(i:i) = chars(i)
  enddo
end subroutine

function swigf_ParameterList_get_string(self, name) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
character(kind=C_CHAR, len=:), allocatable :: swig_result
class(ParameterList), intent(inout) :: self

character(kind=C_CHAR, len=*), target :: name
character(kind=C_CHAR), dimension(:), allocatable, target :: farg2_chars

type(SwigArrayWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 
type(SwigArrayWrapper) :: farg2 

farg1 = self%swigdata
call SWIG_string_to_chararray(name, farg2_chars, farg2)
fresult = swigc_ParameterList_get_string(farg1, farg2)
call SWIG_chararray_to_string(fresult, swig_result)
end function

function swigf_ParameterList_get_arr_real(self, name) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), dimension(:), pointer :: swig_result
class(ParameterList), intent(inout) :: self

character(kind=C_CHAR, len=*), target :: name
character(kind=C_CHAR), dimension(:), allocatable, target :: farg2_chars

type(SwigArrayWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 
type(SwigArrayWrapper) :: farg2 

farg1 = self%swigdata
call SWIG_string_to_chararray(name, farg2_chars, farg2)
fresult = swigc_ParameterList_get_arr_real(farg1, farg2)
call c_f_pointer(fresult%data, swig_result, [fresult%size])
end function

function swigf_ParameterList_get_arr_integer(self, name) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT), dimension(:), pointer :: swig_result
class(ParameterList), intent(inout) :: self

character(kind=C_CHAR, len=*), target :: name
character(kind=C_CHAR), dimension(:), allocatable, target :: farg2_chars

type(SwigArrayWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 
type(SwigArrayWrapper) :: farg2 

farg1 = self%swigdata
call SWIG_string_to_chararray(name, farg2_chars, farg2)
fresult = swigc_ParameterList_get_arr_integer(farg1, farg2)
call c_f_pointer(fresult%data, swig_result, [fresult%size])
end function

function swigf_ParameterList_get_arr_longlong(self, name) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_LONG_LONG), dimension(:), pointer :: swig_result
class(ParameterList), intent(inout) :: self

character(kind=C_CHAR, len=*), target :: name
character(kind=C_CHAR), dimension(:), allocatable, target :: farg2_chars

type(SwigArrayWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 
type(SwigArrayWrapper) :: farg2 

farg1 = self%swigdata
call SWIG_string_to_chararray(name, farg2_chars, farg2)
fresult = swigc_ParameterList_get_arr_longlong(farg1, farg2)
call c_f_pointer(fresult%data, swig_result, [fresult%size])
end function

subroutine delete_ParameterList(self)
use, intrinsic :: ISO_C_BINDING
class(ParameterList), intent(inout) :: self

type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
if (self%swigdata%mem == SWIG_OWN) then
call swigc_delete_ParameterList(farg1)
end if
self%swigdata%cptr = C_NULL_PTR
self%swigdata%mem = SWIG_NULL
end subroutine

  subroutine swigf_assignment_ParameterList(self, other)
   use, intrinsic :: ISO_C_BINDING
   class(ParameterList), intent(inout) :: self
   type(ParameterList), intent(in) :: other
   call swigc_assignment_ParameterList(self%swigdata, other%swigdata)
  end subroutine
subroutine load_from_xml(plist, xml_path)
use, intrinsic :: ISO_C_BINDING
class(ParameterList), intent(in) :: plist

character(kind=C_CHAR, len=*), target :: xml_path
character(kind=C_CHAR), dimension(:), allocatable, target :: farg2_chars

type(SwigClassWrapper) :: farg1 
type(SwigArrayWrapper) :: farg2 

farg1 = plist%swigdata
call SWIG_string_to_chararray(xml_path, farg2_chars, farg2)
call swigc_load_from_xml(farg1, farg2)
end subroutine

subroutine save_to_xml(plist, xml_path)
use, intrinsic :: ISO_C_BINDING
class(ParameterList), intent(in) :: plist

character(kind=C_CHAR, len=*), target :: xml_path
character(kind=C_CHAR), dimension(:), allocatable, target :: farg2_chars

type(SwigClassWrapper) :: farg1 
type(SwigArrayWrapper) :: farg2 

farg1 = plist%swigdata
call SWIG_string_to_chararray(xml_path, farg2_chars, farg2)
call swigc_save_to_xml(farg1, farg2)
end subroutine


end module
