TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
  LIB_REQUIRED_PACKAGES
    Stratimikos
    Teuchos
    Thyra
    ThyraTpetraAdapters
    Tpetra
    ForTrilinosTeuchos
  LIB_OPTIONAL_PACKAGES
    Ifpack2
    MueLu
)
