FROM ubuntu:16.04

ARG NPROC=14

RUN apt-get update && apt-get install -y \
        build-essential \
        gfortran \
        libopenmpi-dev \
        curl \
        cmake \
        git \
        wget \
        vim \
        autoconf \
        lcov \
        valgrind \
        libssl-dev \
        libpng-dev \
        libfreetype6-dev \
        libxft-dev \
        libsqlite3-dev \
        libbz2-dev \
        libatlas-base-dev \
        zlib1g-dev \
        python2.7-dev \
        tmux \
        unzip \
        environment-modules \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    ln -s /usr/bin/python2.7 /usr/bin/python

ENV PREFIX=/scratch
RUN mkdir -p ${PREFIX} && \
    cd ${PREFIX} && \
    mkdir archive && \
    mkdir source && \
    mkdir build && \
    mkdir install

# download Trilinos
RUN export TRILINOS_HASH=c2ce113e511bed0238816dfdcc8db938a35e0bdd && \
    export TRILINOS_SHORT_HASH=c2ce113 && \
    export TRILINOS_URL=https://github.com/trilinos/Trilinos/archive/${TRILINOS_HASH}.tar.gz && \
    export TRILINOS_ARCHIVE=${PREFIX}/archive/trilinos-${TRILINOS_HASH}.tar.gz && \
    export TRILINOS_SOURCE_DIR=${PREFIX}/source/trilinos/${TRILINOS_SHORT_HASH} && \
    export TRILINOS_BUILD_DIR=${PREFIX}/build/trilinos/${TRILINOS_SHORT_HASH} && \
    wget --quiet ${TRILINOS_URL} --output-document=${TRILINOS_ARCHIVE} && \
    mkdir -p ${TRILINOS_SOURCE_DIR} && \
    tar -xf ${TRILINOS_ARCHIVE} -C ${TRILINOS_SOURCE_DIR} --strip-components=1 && \
    ln -s ${TRILINOS_SOURCE_DIR} ${PREFIX}/source/trilinos/release && \
    mkdir -p ${TRILINOS_BUILD_DIR} && \
    rm -rf ${TRILINOS_ARCHIVE}

ENV TRILINOS_DIR=/scratch/source/trilinos/release

# append the option flag --allow-run-as-root to mpiexec
RUN echo '#!/usr/bin/env bash' > /usr/local/bin/mpiexec && \
    echo '/usr/bin/mpiexec --allow-run-as-root "$@"' >> /usr/local/bin/mpiexec && \
    chmod +x /usr/local/bin/mpiexec

ENV HOME=/root

ENV SPACK_ROOT=${PREFIX}/spack

# Install Spack (specific hash)
RUN export SPACK_HASH=c97d058ce3ff0ffc4b1de063daca78cecff23d62 && \
    export SPACK_URL="https://github.com/spack/spack/archive/${SPACK_HASH}.tar.gz" && \
    export SPACK_INSTALL_DIR="${SPACK_ROOT}" && \
    export SPACK_ARCHIVE="${PREFIX}/archive/spack-${SPACK_HASH}.tar.gz" && \
    wget --quiet ${SPACK_URL} --output-document=${SPACK_ARCHIVE} && \
    mkdir -p ${SPACK_INSTALL_DIR} && \
    tar -xf ${SPACK_ARCHIVE} -C ${SPACK_INSTALL_DIR} --strip-components=1 && \
    rm -rf ${SPACK_ARCHIVE} && \
    mkdir -p ${HOME}/.spack

# Load Spack
ENV PATH="${SPACK_ROOT}/bin:${PATH}"
RUN echo "source $SPACK_ROOT/share/spack/setup-env.sh" >> ${HOME}/.bashrc
RUN echo "source /usr/share/modules/init/bash"         >> ${HOME}/.bashrc

# Copy Spack package configuration
COPY packages.yaml ${HOME}/.spack/

# Install flang
RUN spack spec -I flang && spack install flang && spack clean -a
