! This file was automatically generated by SWIG (http://www.swig.org).
! Version 4.0.0
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.

! Copyright 2017, UT-Battelle, LLC
!
! SPDX-License-Identifier: BSD-3-Clause
! License-Filename: LICENSE
module forteuchos
 use, intrinsic :: ISO_C_BINDING
 implicit none
 private

 ! PUBLIC METHODS AND TYPES
 public :: VectorInt
 public :: VectorDouble
 public :: VectorLongLong
 public :: ESide, LEFT_SIDE, RIGHT_SIDE
 public :: ETransp, NO_TRANS, TRANS, CONJ_TRANS
 public :: EUplo, UPPER_TRI, LOWER_TRI, UNDEF_TRI
 public :: EDiag, UNIT_DIAG, NON_UNIT_DIAG
 public :: EType, FULL, LOWER, UPPER, HESSENBERG, SYM_BAND_L, SYM_BAND_U, BAND
 public :: DataAccess, Copy, View

 public :: ierr
 public :: serr

 public :: TeuchosComm
 public :: string
 public :: ParameterList

type, bind(C) :: SwigfArrayWrapper
  type(C_PTR), public :: data
  integer(C_SIZE_T), public :: size
end type

 public :: load_from_xml
 public :: save_to_xml

 ! PARAMETERS
 enum, bind(c)
  enumerator :: ESide = -1
  enumerator :: LEFT_SIDE = 0
  enumerator :: RIGHT_SIDE = LEFT_SIDE + 1
 end enum
 enum, bind(c)
  enumerator :: ETransp = -1
  enumerator :: NO_TRANS = 0
  enumerator :: TRANS = NO_TRANS + 1
  enumerator :: CONJ_TRANS = TRANS + 1
 end enum
 enum, bind(c)
  enumerator :: EUplo = -1
  enumerator :: UPPER_TRI = 0
  enumerator :: LOWER_TRI = UPPER_TRI + 1
  enumerator :: UNDEF_TRI = LOWER_TRI + 1
 end enum
 enum, bind(c)
  enumerator :: EDiag = -1
  enumerator :: UNIT_DIAG = 0
  enumerator :: NON_UNIT_DIAG = UNIT_DIAG + 1
 end enum
 enum, bind(c)
  enumerator :: EType = -1
  enumerator :: FULL = 0
  enumerator :: LOWER = FULL + 1
  enumerator :: UPPER = LOWER + 1
  enumerator :: HESSENBERG = UPPER + 1
  enumerator :: SYM_BAND_L = HESSENBERG + 1
  enumerator :: SYM_BAND_U = SYM_BAND_L + 1
  enumerator :: BAND = SYM_BAND_U + 1
 end enum
 enum, bind(c)
  enumerator :: DataAccess = -1
  enumerator :: Copy = 0
  enumerator :: View = Copy + 1
 end enum
 integer(C_INT), parameter, public :: SWIG_FORTRAN_ERROR_STRLEN = 1024_C_INT

 integer(C_INT), bind(C) :: ierr = 0
 character(kind=C_CHAR, len=1024), bind(C) :: serr = ""


 ! TYPES
 type :: VectorInt
  ! These should be treated as PROTECTED data
  type(C_PTR), public :: swigptr = C_NULL_PTR
 contains
  procedure, private :: create__SWIG_0 => swigf_new_VectorInt__SWIG_0
  procedure, private :: create__SWIG_1 => swigf_new_VectorInt__SWIG_1
  procedure, private :: create__SWIG_2 => swigf_new_VectorInt__SWIG_2
  procedure :: size => swigf_VectorInt_size
  procedure :: capacity => swigf_VectorInt_capacity
  procedure :: empty => swigf_VectorInt_empty
  procedure :: clear => swigf_VectorInt_clear
  procedure :: reserve => swigf_VectorInt_reserve
  procedure, private :: resize__SWIG_0 => swigf_VectorInt_resize__SWIG_0
  procedure, private :: resize__SWIG_1 => swigf_VectorInt_resize__SWIG_1
  procedure :: push_back => swigf_VectorInt_push_back
  procedure :: front => swigf_VectorInt_front
  procedure :: back => swigf_VectorInt_back
  procedure :: set => swigf_VectorInt_set
  procedure :: get => swigf_VectorInt_get
  procedure :: release => swigf_delete_VectorInt
  generic :: create => create__SWIG_0, create__SWIG_1, create__SWIG_2
  generic :: resize => resize__SWIG_0, resize__SWIG_1
 end type
 type :: VectorDouble
  ! These should be treated as PROTECTED data
  type(C_PTR), public :: swigptr = C_NULL_PTR
 contains
  procedure, private :: create__SWIG_0 => swigf_new_VectorDouble__SWIG_0
  procedure, private :: create__SWIG_1 => swigf_new_VectorDouble__SWIG_1
  procedure, private :: create__SWIG_2 => swigf_new_VectorDouble__SWIG_2
  procedure :: size => swigf_VectorDouble_size
  procedure :: capacity => swigf_VectorDouble_capacity
  procedure :: empty => swigf_VectorDouble_empty
  procedure :: clear => swigf_VectorDouble_clear
  procedure :: reserve => swigf_VectorDouble_reserve
  procedure, private :: resize__SWIG_0 => swigf_VectorDouble_resize__SWIG_0
  procedure, private :: resize__SWIG_1 => swigf_VectorDouble_resize__SWIG_1
  procedure :: push_back => swigf_VectorDouble_push_back
  procedure :: front => swigf_VectorDouble_front
  procedure :: back => swigf_VectorDouble_back
  procedure :: set => swigf_VectorDouble_set
  procedure :: get => swigf_VectorDouble_get
  procedure :: release => swigf_delete_VectorDouble
  generic :: create => create__SWIG_0, create__SWIG_1, create__SWIG_2
  generic :: resize => resize__SWIG_0, resize__SWIG_1
 end type
 type :: VectorLongLong
  ! These should be treated as PROTECTED data
  type(C_PTR), public :: swigptr = C_NULL_PTR
 contains
  procedure, private :: create__SWIG_0 => swigf_new_VectorLongLong__SWIG_0
  procedure, private :: create__SWIG_1 => swigf_new_VectorLongLong__SWIG_1
  procedure, private :: create__SWIG_2 => swigf_new_VectorLongLong__SWIG_2
  procedure :: size => swigf_VectorLongLong_size
  procedure :: capacity => swigf_VectorLongLong_capacity
  procedure :: empty => swigf_VectorLongLong_empty
  procedure :: clear => swigf_VectorLongLong_clear
  procedure :: reserve => swigf_VectorLongLong_reserve
  procedure, private :: resize__SWIG_0 => swigf_VectorLongLong_resize__SWIG_0
  procedure, private :: resize__SWIG_1 => swigf_VectorLongLong_resize__SWIG_1
  procedure :: push_back => swigf_VectorLongLong_push_back
  procedure :: front => swigf_VectorLongLong_front
  procedure :: back => swigf_VectorLongLong_back
  procedure :: set => swigf_VectorLongLong_set
  procedure :: get => swigf_VectorLongLong_get
  procedure :: release => swigf_delete_VectorLongLong
  generic :: create => create__SWIG_0, create__SWIG_1, create__SWIG_2
  generic :: resize => resize__SWIG_0, resize__SWIG_1
 end type
 type :: TeuchosComm
  ! These should be treated as PROTECTED data
  type(C_PTR), public :: swigptr = C_NULL_PTR
 contains
  procedure, private :: create__SWIG_0 => swigf_new_TeuchosComm__SWIG_0
  procedure, private :: create__SWIG_1 => swigf_new_TeuchosComm__SWIG_1
  procedure :: getRank => swigf_TeuchosComm_getRank
  procedure :: getSize => swigf_TeuchosComm_getSize
  procedure :: barrier => swigf_TeuchosComm_barrier
  procedure :: release => swigf_delete_TeuchosComm
  procedure, private :: swigf_assign_TeuchosComm
  generic :: create => create__SWIG_0, create__SWIG_1
  generic :: assignment(=) => swigf_assign_TeuchosComm
 end type
 type :: string
  ! These should be treated as PROTECTED data
  type(C_PTR), public :: swigptr = C_NULL_PTR
 contains
  procedure :: create => swigf_new_string
  procedure :: resize => swigf_string_resize
  procedure :: clear => swigf_string_clear
  procedure :: size => swigf_string_size
  procedure :: length => swigf_string_length
  procedure :: set => swigf_string_set
  procedure :: get => swigf_string_get
  procedure :: release => swigf_delete_string
 end type
 type :: ParameterList
  ! These should be treated as PROTECTED data
  type(C_PTR), public :: swigptr = C_NULL_PTR
 contains
  procedure :: print => swigf_ParameterList_print
  procedure, private :: create__SWIG_0 => swigf_new_ParameterList__SWIG_0
  procedure, private :: create__SWIG_1 => swigf_new_ParameterList__SWIG_1
  procedure, private :: get__SWIG_0 => swigf_ParameterList_get__SWIG_0
  procedure, private :: set__SWIG_0 => swigf_ParameterList_set__SWIG_0
  procedure, private :: get__SWIG_1 => swigf_ParameterList_get__SWIG_1
  procedure, private :: set__SWIG_1 => swigf_ParameterList_set__SWIG_1
  procedure, private :: set__SWIG_2 => swigf_ParameterList_set__SWIG_2
  procedure, private :: get__SWIG_2 => swigf_ParameterList_get__SWIG_2
  procedure, private :: set__SWIG_3 => swigf_ParameterList_set__SWIG_3
  procedure, private :: get__SWIG_3 => swigf_ParameterList_get__SWIG_3
  procedure, private :: set__SWIG_4 => swigf_ParameterList_set__SWIG_4
  procedure, private :: get__SWIG_4 => swigf_ParameterList_get__SWIG_4
  procedure, private :: set__SWIG_5 => swigf_ParameterList_set__SWIG_5
  procedure, private :: get__SWIG_5 => swigf_ParameterList_get__SWIG_5
  procedure :: sublist => swigf_ParameterList_sublist
  procedure :: get_length => swigf_ParameterList_get_length
  procedure :: remove => swigf_ParameterList_remove
  procedure :: is_parameter => swigf_ParameterList_is_parameter
  procedure :: release => swigf_delete_ParameterList
  procedure, private :: swigf_assign_ParameterList
  generic :: create => create__SWIG_0, create__SWIG_1
  generic :: assignment(=) => swigf_assign_ParameterList
  generic :: set => set__SWIG_0, set__SWIG_1, set__SWIG_2, set__SWIG_3, set__SWIG_4, set__SWIG_5
  generic :: get => get__SWIG_0, get__SWIG_1, get__SWIG_2, get__SWIG_3, get__SWIG_4, get__SWIG_5
 end type


 ! WRAPPER DECLARATIONS
 interface
function swigc_new_VectorInt__SWIG_0() &
bind(C, name="swigc_new_VectorInt__SWIG_0") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR) :: fresult
end function

function swigc_new_VectorInt__SWIG_1(farg1) &
bind(C, name="swigc_new_VectorInt__SWIG_1") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_LONG), intent(in) :: farg1
type(C_PTR) :: fresult
end function

function swigc_new_VectorInt__SWIG_2(farg1, farg2) &
bind(C, name="swigc_new_VectorInt__SWIG_2") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_LONG), intent(in) :: farg1
integer(C_INT), intent(in) :: farg2
type(C_PTR) :: fresult
end function

function swigc_VectorInt_size(farg1) &
bind(C, name="swigc_VectorInt_size") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_LONG) :: fresult
end function

function swigc_VectorInt_capacity(farg1) &
bind(C, name="swigc_VectorInt_capacity") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_LONG) :: fresult
end function

function swigc_VectorInt_empty(farg1) &
bind(C, name="swigc_VectorInt_empty") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
logical(C_BOOL) :: fresult
end function

subroutine swigc_VectorInt_clear(farg1) &
bind(C, name="swigc_VectorInt_clear")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
end subroutine

subroutine swigc_VectorInt_reserve(farg1, farg2) &
bind(C, name="swigc_VectorInt_reserve")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_LONG), intent(in) :: farg2
end subroutine

subroutine swigc_VectorInt_resize__SWIG_0(farg1, farg2) &
bind(C, name="swigc_VectorInt_resize__SWIG_0")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_LONG), intent(in) :: farg2
end subroutine

subroutine swigc_VectorInt_resize__SWIG_1(farg1, farg2, farg3) &
bind(C, name="swigc_VectorInt_resize__SWIG_1")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_LONG), intent(in) :: farg2
integer(C_INT), intent(in) :: farg3
end subroutine

subroutine swigc_VectorInt_push_back(farg1, farg2) &
bind(C, name="swigc_VectorInt_push_back")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT), intent(in) :: farg2
end subroutine

function swigc_VectorInt_front(farg1) &
bind(C, name="swigc_VectorInt_front") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT) :: fresult
end function

function swigc_VectorInt_back(farg1) &
bind(C, name="swigc_VectorInt_back") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT) :: fresult
end function

subroutine swigc_VectorInt_set(farg1, farg2, farg3) &
bind(C, name="swigc_VectorInt_set")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_LONG), intent(in) :: farg2
integer(C_INT), intent(in) :: farg3
end subroutine

function swigc_VectorInt_get(farg1, farg2) &
bind(C, name="swigc_VectorInt_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_LONG), intent(in) :: farg2
integer(C_INT) :: fresult
end function

subroutine swigc_delete_VectorInt(farg1) &
bind(C, name="swigc_delete_VectorInt")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
end subroutine

function swigc_new_VectorDouble__SWIG_0() &
bind(C, name="swigc_new_VectorDouble__SWIG_0") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR) :: fresult
end function

function swigc_new_VectorDouble__SWIG_1(farg1) &
bind(C, name="swigc_new_VectorDouble__SWIG_1") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_LONG), intent(in) :: farg1
type(C_PTR) :: fresult
end function

function swigc_new_VectorDouble__SWIG_2(farg1, farg2) &
bind(C, name="swigc_new_VectorDouble__SWIG_2") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_LONG), intent(in) :: farg1
real(C_DOUBLE), intent(in) :: farg2
type(C_PTR) :: fresult
end function

function swigc_VectorDouble_size(farg1) &
bind(C, name="swigc_VectorDouble_size") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_LONG) :: fresult
end function

function swigc_VectorDouble_capacity(farg1) &
bind(C, name="swigc_VectorDouble_capacity") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_LONG) :: fresult
end function

function swigc_VectorDouble_empty(farg1) &
bind(C, name="swigc_VectorDouble_empty") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
logical(C_BOOL) :: fresult
end function

subroutine swigc_VectorDouble_clear(farg1) &
bind(C, name="swigc_VectorDouble_clear")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
end subroutine

subroutine swigc_VectorDouble_reserve(farg1, farg2) &
bind(C, name="swigc_VectorDouble_reserve")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_LONG), intent(in) :: farg2
end subroutine

subroutine swigc_VectorDouble_resize__SWIG_0(farg1, farg2) &
bind(C, name="swigc_VectorDouble_resize__SWIG_0")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_LONG), intent(in) :: farg2
end subroutine

subroutine swigc_VectorDouble_resize__SWIG_1(farg1, farg2, farg3) &
bind(C, name="swigc_VectorDouble_resize__SWIG_1")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_LONG), intent(in) :: farg2
real(C_DOUBLE), intent(in) :: farg3
end subroutine

subroutine swigc_VectorDouble_push_back(farg1, farg2) &
bind(C, name="swigc_VectorDouble_push_back")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
real(C_DOUBLE), intent(in) :: farg2
end subroutine

function swigc_VectorDouble_front(farg1) &
bind(C, name="swigc_VectorDouble_front") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
real(C_DOUBLE) :: fresult
end function

function swigc_VectorDouble_back(farg1) &
bind(C, name="swigc_VectorDouble_back") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
real(C_DOUBLE) :: fresult
end function

subroutine swigc_VectorDouble_set(farg1, farg2, farg3) &
bind(C, name="swigc_VectorDouble_set")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_LONG), intent(in) :: farg2
real(C_DOUBLE), intent(in) :: farg3
end subroutine

function swigc_VectorDouble_get(farg1, farg2) &
bind(C, name="swigc_VectorDouble_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_LONG), intent(in) :: farg2
real(C_DOUBLE) :: fresult
end function

subroutine swigc_delete_VectorDouble(farg1) &
bind(C, name="swigc_delete_VectorDouble")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
end subroutine

function swigc_new_VectorLongLong__SWIG_0() &
bind(C, name="swigc_new_VectorLongLong__SWIG_0") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR) :: fresult
end function

function swigc_new_VectorLongLong__SWIG_1(farg1) &
bind(C, name="swigc_new_VectorLongLong__SWIG_1") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_LONG), intent(in) :: farg1
type(C_PTR) :: fresult
end function

function swigc_new_VectorLongLong__SWIG_2(farg1, farg2) &
bind(C, name="swigc_new_VectorLongLong__SWIG_2") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_LONG), intent(in) :: farg1
integer(C_LONG_LONG), intent(in) :: farg2
type(C_PTR) :: fresult
end function

function swigc_VectorLongLong_size(farg1) &
bind(C, name="swigc_VectorLongLong_size") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_LONG) :: fresult
end function

function swigc_VectorLongLong_capacity(farg1) &
bind(C, name="swigc_VectorLongLong_capacity") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_LONG) :: fresult
end function

function swigc_VectorLongLong_empty(farg1) &
bind(C, name="swigc_VectorLongLong_empty") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
logical(C_BOOL) :: fresult
end function

subroutine swigc_VectorLongLong_clear(farg1) &
bind(C, name="swigc_VectorLongLong_clear")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
end subroutine

subroutine swigc_VectorLongLong_reserve(farg1, farg2) &
bind(C, name="swigc_VectorLongLong_reserve")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_LONG), intent(in) :: farg2
end subroutine

subroutine swigc_VectorLongLong_resize__SWIG_0(farg1, farg2) &
bind(C, name="swigc_VectorLongLong_resize__SWIG_0")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_LONG), intent(in) :: farg2
end subroutine

subroutine swigc_VectorLongLong_resize__SWIG_1(farg1, farg2, farg3) &
bind(C, name="swigc_VectorLongLong_resize__SWIG_1")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_LONG), intent(in) :: farg2
integer(C_LONG_LONG), intent(in) :: farg3
end subroutine

subroutine swigc_VectorLongLong_push_back(farg1, farg2) &
bind(C, name="swigc_VectorLongLong_push_back")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_LONG_LONG), intent(in) :: farg2
end subroutine

function swigc_VectorLongLong_front(farg1) &
bind(C, name="swigc_VectorLongLong_front") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_LONG_LONG) :: fresult
end function

function swigc_VectorLongLong_back(farg1) &
bind(C, name="swigc_VectorLongLong_back") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_LONG_LONG) :: fresult
end function

subroutine swigc_VectorLongLong_set(farg1, farg2, farg3) &
bind(C, name="swigc_VectorLongLong_set")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_LONG), intent(in) :: farg2
integer(C_LONG_LONG), intent(in) :: farg3
end subroutine

function swigc_VectorLongLong_get(farg1, farg2) &
bind(C, name="swigc_VectorLongLong_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_LONG), intent(in) :: farg2
integer(C_LONG_LONG) :: fresult
end function

subroutine swigc_delete_VectorLongLong(farg1) &
bind(C, name="swigc_delete_VectorLongLong")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
end subroutine

function swigc_new_TeuchosComm__SWIG_0(farg1) &
bind(C, name="swigc_new_TeuchosComm__SWIG_0") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT), intent(in) :: farg1
type(C_PTR) :: fresult
end function

function swigc_new_TeuchosComm__SWIG_1() &
bind(C, name="swigc_new_TeuchosComm__SWIG_1") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR) :: fresult
end function

function swigc_TeuchosComm_getRank(farg1) &
bind(C, name="swigc_TeuchosComm_getRank") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT) :: fresult
end function

function swigc_TeuchosComm_getSize(farg1) &
bind(C, name="swigc_TeuchosComm_getSize") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT) :: fresult
end function

subroutine swigc_TeuchosComm_barrier(farg1) &
bind(C, name="swigc_TeuchosComm_barrier")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
end subroutine

subroutine swigc_delete_TeuchosComm(farg1) &
bind(C, name="swigc_delete_TeuchosComm")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
end subroutine

  function swigc_spcopy_TeuchosComm(farg1) &
     bind(C, name="swigc_spcopy_TeuchosComm") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   type(C_PTR) :: fresult
   type(C_PTR), value :: farg1
  end function
function swigc_new_string() &
bind(C, name="swigc_new_string") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR) :: fresult
end function

subroutine swigc_string_resize(farg1, farg2) &
bind(C, name="swigc_string_resize")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_LONG), intent(in) :: farg2
end subroutine

subroutine swigc_string_clear(farg1) &
bind(C, name="swigc_string_clear")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
end subroutine

function swigc_string_size(farg1) &
bind(C, name="swigc_string_size") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_LONG) :: fresult
end function

function swigc_string_length(farg1) &
bind(C, name="swigc_string_length") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_LONG) :: fresult
end function

subroutine swigc_string_set(farg1, farg2, farg3) &
bind(C, name="swigc_string_set")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_LONG), intent(in) :: farg2
integer(C_SIGNED_CHAR), intent(in) :: farg3
end subroutine

function swigc_string_get(farg1, farg2) &
bind(C, name="swigc_string_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_LONG), intent(in) :: farg2
integer(C_SIGNED_CHAR) :: fresult
end function

subroutine swigc_delete_string(farg1) &
bind(C, name="swigc_delete_string")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
end subroutine

subroutine swigc_ParameterList_print(farg1) &
bind(C, name="swigc_ParameterList_print")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
end subroutine

function swigc_new_ParameterList__SWIG_0() &
bind(C, name="swigc_new_ParameterList__SWIG_0") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR) :: fresult
end function

function swigc_new_ParameterList__SWIG_1(farg1) &
bind(C, name="swigc_new_ParameterList__SWIG_1") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: SwigfArrayWrapper
type(SwigfArrayWrapper) :: farg1
type(C_PTR) :: fresult
end function

subroutine swigc_ParameterList_get__SWIG_0(farg1, farg2, farg3) &
bind(C, name="swigc_ParameterList_get__SWIG_0")
use, intrinsic :: ISO_C_BINDING
import :: SwigfArrayWrapper
type(C_PTR), value :: farg1
type(SwigfArrayWrapper) :: farg2
type(C_PTR), value :: farg3
end subroutine

subroutine swigc_ParameterList_set__SWIG_0(farg1, farg2, farg3) &
bind(C, name="swigc_ParameterList_set__SWIG_0")
use, intrinsic :: ISO_C_BINDING
import :: SwigfArrayWrapper
type(C_PTR), value :: farg1
type(SwigfArrayWrapper) :: farg2
real(C_DOUBLE), intent(in) :: farg3
end subroutine

subroutine swigc_ParameterList_get__SWIG_1(farg1, farg2, farg3) &
bind(C, name="swigc_ParameterList_get__SWIG_1")
use, intrinsic :: ISO_C_BINDING
import :: SwigfArrayWrapper
type(C_PTR), value :: farg1
type(SwigfArrayWrapper) :: farg2
type(C_PTR), value :: farg3
end subroutine

subroutine swigc_ParameterList_set__SWIG_1(farg1, farg2, farg3) &
bind(C, name="swigc_ParameterList_set__SWIG_1")
use, intrinsic :: ISO_C_BINDING
import :: SwigfArrayWrapper
type(C_PTR), value :: farg1
type(SwigfArrayWrapper) :: farg2
integer(C_INT), intent(in) :: farg3
end subroutine

subroutine swigc_ParameterList_set__SWIG_2(farg1, farg2, farg3) &
bind(C, name="swigc_ParameterList_set__SWIG_2")
use, intrinsic :: ISO_C_BINDING
import :: SwigfArrayWrapper
type(C_PTR), value :: farg1
type(SwigfArrayWrapper) :: farg2
type(SwigfArrayWrapper) :: farg3
end subroutine

subroutine swigc_ParameterList_get__SWIG_2(farg1, farg2, farg3) &
bind(C, name="swigc_ParameterList_get__SWIG_2")
use, intrinsic :: ISO_C_BINDING
import :: SwigfArrayWrapper
type(C_PTR), value :: farg1
type(SwigfArrayWrapper) :: farg2
type(SwigfArrayWrapper) :: farg3
end subroutine

subroutine swigc_ParameterList_set__SWIG_3(farg1, farg2, farg3) &
bind(C, name="swigc_ParameterList_set__SWIG_3")
use, intrinsic :: ISO_C_BINDING
import :: SwigfArrayWrapper
type(C_PTR), value :: farg1
type(SwigfArrayWrapper) :: farg2
type(SwigfArrayWrapper) :: farg3
end subroutine

subroutine swigc_ParameterList_get__SWIG_3(farg1, farg2, farg3) &
bind(C, name="swigc_ParameterList_get__SWIG_3")
use, intrinsic :: ISO_C_BINDING
import :: SwigfArrayWrapper
type(C_PTR), value :: farg1
type(SwigfArrayWrapper) :: farg2
type(SwigfArrayWrapper) :: farg3
end subroutine

subroutine swigc_ParameterList_set__SWIG_4(farg1, farg2, farg3) &
bind(C, name="swigc_ParameterList_set__SWIG_4")
use, intrinsic :: ISO_C_BINDING
import :: SwigfArrayWrapper
type(C_PTR), value :: farg1
type(SwigfArrayWrapper) :: farg2
type(SwigfArrayWrapper) :: farg3
end subroutine

subroutine swigc_ParameterList_get__SWIG_4(farg1, farg2, farg3) &
bind(C, name="swigc_ParameterList_get__SWIG_4")
use, intrinsic :: ISO_C_BINDING
import :: SwigfArrayWrapper
type(C_PTR), value :: farg1
type(SwigfArrayWrapper) :: farg2
type(SwigfArrayWrapper) :: farg3
end subroutine

subroutine swigc_ParameterList_set__SWIG_5(farg1, farg2, farg3) &
bind(C, name="swigc_ParameterList_set__SWIG_5")
use, intrinsic :: ISO_C_BINDING
import :: SwigfArrayWrapper
type(C_PTR), value :: farg1
type(SwigfArrayWrapper) :: farg2
type(C_PTR), value :: farg3
end subroutine

subroutine swigc_ParameterList_get__SWIG_5(farg1, farg2, farg3) &
bind(C, name="swigc_ParameterList_get__SWIG_5")
use, intrinsic :: ISO_C_BINDING
import :: SwigfArrayWrapper
type(C_PTR), value :: farg1
type(SwigfArrayWrapper) :: farg2
type(C_PTR), value :: farg3
end subroutine

function swigc_ParameterList_sublist(farg1, farg2) &
bind(C, name="swigc_ParameterList_sublist") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: SwigfArrayWrapper
type(C_PTR), value :: farg1
type(SwigfArrayWrapper) :: farg2
type(C_PTR) :: fresult
end function

function swigc_ParameterList_get_length(farg1, farg2) &
bind(C, name="swigc_ParameterList_get_length") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: SwigfArrayWrapper
type(C_PTR), value :: farg1
type(SwigfArrayWrapper) :: farg2
integer(C_INT) :: fresult
end function

subroutine swigc_ParameterList_remove(farg1, farg2) &
bind(C, name="swigc_ParameterList_remove")
use, intrinsic :: ISO_C_BINDING
import :: SwigfArrayWrapper
type(C_PTR), value :: farg1
type(SwigfArrayWrapper) :: farg2
end subroutine

function swigc_ParameterList_is_parameter(farg1, farg2) &
bind(C, name="swigc_ParameterList_is_parameter") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: SwigfArrayWrapper
type(C_PTR), value :: farg1
type(SwigfArrayWrapper) :: farg2
logical(C_BOOL) :: fresult
end function

subroutine swigc_delete_ParameterList(farg1) &
bind(C, name="swigc_delete_ParameterList")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
end subroutine

  function swigc_spcopy_ParameterList(farg1) &
     bind(C, name="swigc_spcopy_ParameterList") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   type(C_PTR) :: fresult
   type(C_PTR), value :: farg1
  end function
subroutine swigc_load_from_xml(farg1, farg2) &
bind(C, name="swigc_load_from_xml")
use, intrinsic :: ISO_C_BINDING
import :: SwigfArrayWrapper
type(C_PTR), value :: farg1
type(SwigfArrayWrapper) :: farg2
end subroutine

subroutine swigc_save_to_xml(farg1, farg2) &
bind(C, name="swigc_save_to_xml")
use, intrinsic :: ISO_C_BINDING
import :: SwigfArrayWrapper
type(C_PTR), value :: farg1
type(SwigfArrayWrapper) :: farg2
end subroutine

 end interface


contains
 ! FORTRAN PROXY CODE
subroutine swigf_new_VectorInt__SWIG_0(self)
use, intrinsic :: ISO_C_BINDING
class(VectorInt) :: self
type(C_PTR) :: fresult 

if (c_associated(self%swigptr)) call self%release()
fresult = swigc_new_VectorInt__SWIG_0()
self%swigptr = fresult
end subroutine

subroutine swigf_new_VectorInt__SWIG_1(self, count)
use, intrinsic :: ISO_C_BINDING
class(VectorInt) :: self
integer(C_LONG), intent(in) :: count
type(C_PTR) :: fresult 
integer(C_LONG) :: farg1 

if (c_associated(self%swigptr)) call self%release()
farg1 = count
fresult = swigc_new_VectorInt__SWIG_1(farg1)
self%swigptr = fresult
end subroutine

subroutine swigf_new_VectorInt__SWIG_2(self, count, v)
use, intrinsic :: ISO_C_BINDING
class(VectorInt) :: self
integer(C_LONG), intent(in) :: count
integer(C_INT), intent(in) :: v
type(C_PTR) :: fresult 
integer(C_LONG) :: farg1 
integer(C_INT) :: farg2 

if (c_associated(self%swigptr)) call self%release()
farg1 = count
farg2 = v
fresult = swigc_new_VectorInt__SWIG_2(farg1, farg2)
self%swigptr = fresult
end subroutine

function swigf_VectorInt_size(self) &
result(swigf_result)
use, intrinsic :: ISO_C_BINDING
integer(C_LONG) :: swigf_result
class(VectorInt) :: self
integer(C_LONG) :: fresult 
type(C_PTR) :: farg1 

farg1 = self%swigptr
fresult = swigc_VectorInt_size(farg1)
swigf_result = fresult
end function

function swigf_VectorInt_capacity(self) &
result(swigf_result)
use, intrinsic :: ISO_C_BINDING
integer(C_LONG) :: swigf_result
class(VectorInt) :: self
integer(C_LONG) :: fresult 
type(C_PTR) :: farg1 

farg1 = self%swigptr
fresult = swigc_VectorInt_capacity(farg1)
swigf_result = fresult
end function

function swigf_VectorInt_empty(self) &
result(swigf_result)
use, intrinsic :: ISO_C_BINDING
logical(C_BOOL) :: swigf_result
class(VectorInt) :: self
logical(C_BOOL) :: fresult 
type(C_PTR) :: farg1 

farg1 = self%swigptr
fresult = swigc_VectorInt_empty(farg1)
swigf_result = fresult
end function

subroutine swigf_VectorInt_clear(self)
use, intrinsic :: ISO_C_BINDING
class(VectorInt) :: self
type(C_PTR) :: farg1 

farg1 = self%swigptr
call swigc_VectorInt_clear(farg1)
end subroutine

subroutine swigf_VectorInt_reserve(self, count)
use, intrinsic :: ISO_C_BINDING
class(VectorInt) :: self
integer(C_LONG), intent(in) :: count
type(C_PTR) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigptr
farg2 = count
call swigc_VectorInt_reserve(farg1, farg2)
end subroutine

subroutine swigf_VectorInt_resize__SWIG_0(self, count)
use, intrinsic :: ISO_C_BINDING
class(VectorInt) :: self
integer(C_LONG), intent(in) :: count
type(C_PTR) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigptr
farg2 = count
call swigc_VectorInt_resize__SWIG_0(farg1, farg2)
end subroutine

subroutine swigf_VectorInt_resize__SWIG_1(self, count, v)
use, intrinsic :: ISO_C_BINDING
class(VectorInt) :: self
integer(C_LONG), intent(in) :: count
integer(C_INT), intent(in) :: v
type(C_PTR) :: farg1 
integer(C_LONG) :: farg2 
integer(C_INT) :: farg3 

farg1 = self%swigptr
farg2 = count
farg3 = v
call swigc_VectorInt_resize__SWIG_1(farg1, farg2, farg3)
end subroutine

subroutine swigf_VectorInt_push_back(self, v)
use, intrinsic :: ISO_C_BINDING
class(VectorInt) :: self
integer(C_INT), intent(in) :: v
type(C_PTR) :: farg1 
integer(C_INT) :: farg2 

farg1 = self%swigptr
farg2 = v
call swigc_VectorInt_push_back(farg1, farg2)
end subroutine

function swigf_VectorInt_front(self) &
result(swigf_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swigf_result
class(VectorInt) :: self
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 

farg1 = self%swigptr
fresult = swigc_VectorInt_front(farg1)
swigf_result = fresult
end function

function swigf_VectorInt_back(self) &
result(swigf_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swigf_result
class(VectorInt) :: self
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 

farg1 = self%swigptr
fresult = swigc_VectorInt_back(farg1)
swigf_result = fresult
end function

subroutine swigf_VectorInt_set(self, index, v)
use, intrinsic :: ISO_C_BINDING
class(VectorInt) :: self
integer(C_LONG), intent(in) :: index
integer(C_INT), intent(in) :: v
type(C_PTR) :: farg1 
integer(C_LONG) :: farg2 
integer(C_INT) :: farg3 

farg1 = self%swigptr
farg2 = index
farg3 = v
call swigc_VectorInt_set(farg1, farg2, farg3)
end subroutine

function swigf_VectorInt_get(self, index) &
result(swigf_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swigf_result
class(VectorInt) :: self
integer(C_LONG), intent(in) :: index
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigptr
farg2 = index
fresult = swigc_VectorInt_get(farg1, farg2)
swigf_result = fresult
end function

subroutine swigf_delete_VectorInt(self)
use, intrinsic :: ISO_C_BINDING
class(VectorInt) :: self
type(C_PTR) :: farg1 

if (.not. c_associated(self%swigptr)) return
farg1 = self%swigptr
call swigc_delete_VectorInt(farg1)
self%swigptr = C_NULL_PTR
end subroutine

subroutine swigf_new_VectorDouble__SWIG_0(self)
use, intrinsic :: ISO_C_BINDING
class(VectorDouble) :: self
type(C_PTR) :: fresult 

if (c_associated(self%swigptr)) call self%release()
fresult = swigc_new_VectorDouble__SWIG_0()
self%swigptr = fresult
end subroutine

subroutine swigf_new_VectorDouble__SWIG_1(self, count)
use, intrinsic :: ISO_C_BINDING
class(VectorDouble) :: self
integer(C_LONG), intent(in) :: count
type(C_PTR) :: fresult 
integer(C_LONG) :: farg1 

if (c_associated(self%swigptr)) call self%release()
farg1 = count
fresult = swigc_new_VectorDouble__SWIG_1(farg1)
self%swigptr = fresult
end subroutine

subroutine swigf_new_VectorDouble__SWIG_2(self, count, v)
use, intrinsic :: ISO_C_BINDING
class(VectorDouble) :: self
integer(C_LONG), intent(in) :: count
real(C_DOUBLE), intent(in) :: v
type(C_PTR) :: fresult 
integer(C_LONG) :: farg1 
real(C_DOUBLE) :: farg2 

if (c_associated(self%swigptr)) call self%release()
farg1 = count
farg2 = v
fresult = swigc_new_VectorDouble__SWIG_2(farg1, farg2)
self%swigptr = fresult
end subroutine

function swigf_VectorDouble_size(self) &
result(swigf_result)
use, intrinsic :: ISO_C_BINDING
integer(C_LONG) :: swigf_result
class(VectorDouble) :: self
integer(C_LONG) :: fresult 
type(C_PTR) :: farg1 

farg1 = self%swigptr
fresult = swigc_VectorDouble_size(farg1)
swigf_result = fresult
end function

function swigf_VectorDouble_capacity(self) &
result(swigf_result)
use, intrinsic :: ISO_C_BINDING
integer(C_LONG) :: swigf_result
class(VectorDouble) :: self
integer(C_LONG) :: fresult 
type(C_PTR) :: farg1 

farg1 = self%swigptr
fresult = swigc_VectorDouble_capacity(farg1)
swigf_result = fresult
end function

function swigf_VectorDouble_empty(self) &
result(swigf_result)
use, intrinsic :: ISO_C_BINDING
logical(C_BOOL) :: swigf_result
class(VectorDouble) :: self
logical(C_BOOL) :: fresult 
type(C_PTR) :: farg1 

farg1 = self%swigptr
fresult = swigc_VectorDouble_empty(farg1)
swigf_result = fresult
end function

subroutine swigf_VectorDouble_clear(self)
use, intrinsic :: ISO_C_BINDING
class(VectorDouble) :: self
type(C_PTR) :: farg1 

farg1 = self%swigptr
call swigc_VectorDouble_clear(farg1)
end subroutine

subroutine swigf_VectorDouble_reserve(self, count)
use, intrinsic :: ISO_C_BINDING
class(VectorDouble) :: self
integer(C_LONG), intent(in) :: count
type(C_PTR) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigptr
farg2 = count
call swigc_VectorDouble_reserve(farg1, farg2)
end subroutine

subroutine swigf_VectorDouble_resize__SWIG_0(self, count)
use, intrinsic :: ISO_C_BINDING
class(VectorDouble) :: self
integer(C_LONG), intent(in) :: count
type(C_PTR) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigptr
farg2 = count
call swigc_VectorDouble_resize__SWIG_0(farg1, farg2)
end subroutine

subroutine swigf_VectorDouble_resize__SWIG_1(self, count, v)
use, intrinsic :: ISO_C_BINDING
class(VectorDouble) :: self
integer(C_LONG), intent(in) :: count
real(C_DOUBLE), intent(in) :: v
type(C_PTR) :: farg1 
integer(C_LONG) :: farg2 
real(C_DOUBLE) :: farg3 

farg1 = self%swigptr
farg2 = count
farg3 = v
call swigc_VectorDouble_resize__SWIG_1(farg1, farg2, farg3)
end subroutine

subroutine swigf_VectorDouble_push_back(self, v)
use, intrinsic :: ISO_C_BINDING
class(VectorDouble) :: self
real(C_DOUBLE), intent(in) :: v
type(C_PTR) :: farg1 
real(C_DOUBLE) :: farg2 

farg1 = self%swigptr
farg2 = v
call swigc_VectorDouble_push_back(farg1, farg2)
end subroutine

function swigf_VectorDouble_front(self) &
result(swigf_result)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE) :: swigf_result
class(VectorDouble) :: self
real(C_DOUBLE) :: fresult 
type(C_PTR) :: farg1 

farg1 = self%swigptr
fresult = swigc_VectorDouble_front(farg1)
swigf_result = fresult
end function

function swigf_VectorDouble_back(self) &
result(swigf_result)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE) :: swigf_result
class(VectorDouble) :: self
real(C_DOUBLE) :: fresult 
type(C_PTR) :: farg1 

farg1 = self%swigptr
fresult = swigc_VectorDouble_back(farg1)
swigf_result = fresult
end function

subroutine swigf_VectorDouble_set(self, index, v)
use, intrinsic :: ISO_C_BINDING
class(VectorDouble) :: self
integer(C_LONG), intent(in) :: index
real(C_DOUBLE), intent(in) :: v
type(C_PTR) :: farg1 
integer(C_LONG) :: farg2 
real(C_DOUBLE) :: farg3 

farg1 = self%swigptr
farg2 = index
farg3 = v
call swigc_VectorDouble_set(farg1, farg2, farg3)
end subroutine

function swigf_VectorDouble_get(self, index) &
result(swigf_result)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE) :: swigf_result
class(VectorDouble) :: self
integer(C_LONG), intent(in) :: index
real(C_DOUBLE) :: fresult 
type(C_PTR) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigptr
farg2 = index
fresult = swigc_VectorDouble_get(farg1, farg2)
swigf_result = fresult
end function

subroutine swigf_delete_VectorDouble(self)
use, intrinsic :: ISO_C_BINDING
class(VectorDouble) :: self
type(C_PTR) :: farg1 

if (.not. c_associated(self%swigptr)) return
farg1 = self%swigptr
call swigc_delete_VectorDouble(farg1)
self%swigptr = C_NULL_PTR
end subroutine

subroutine swigf_new_VectorLongLong__SWIG_0(self)
use, intrinsic :: ISO_C_BINDING
class(VectorLongLong) :: self
type(C_PTR) :: fresult 

if (c_associated(self%swigptr)) call self%release()
fresult = swigc_new_VectorLongLong__SWIG_0()
self%swigptr = fresult
end subroutine

subroutine swigf_new_VectorLongLong__SWIG_1(self, count)
use, intrinsic :: ISO_C_BINDING
class(VectorLongLong) :: self
integer(C_LONG), intent(in) :: count
type(C_PTR) :: fresult 
integer(C_LONG) :: farg1 

if (c_associated(self%swigptr)) call self%release()
farg1 = count
fresult = swigc_new_VectorLongLong__SWIG_1(farg1)
self%swigptr = fresult
end subroutine

subroutine swigf_new_VectorLongLong__SWIG_2(self, count, v)
use, intrinsic :: ISO_C_BINDING
class(VectorLongLong) :: self
integer(C_LONG), intent(in) :: count
integer(C_LONG_LONG), intent(in) :: v
type(C_PTR) :: fresult 
integer(C_LONG) :: farg1 
integer(C_LONG_LONG) :: farg2 

if (c_associated(self%swigptr)) call self%release()
farg1 = count
farg2 = v
fresult = swigc_new_VectorLongLong__SWIG_2(farg1, farg2)
self%swigptr = fresult
end subroutine

function swigf_VectorLongLong_size(self) &
result(swigf_result)
use, intrinsic :: ISO_C_BINDING
integer(C_LONG) :: swigf_result
class(VectorLongLong) :: self
integer(C_LONG) :: fresult 
type(C_PTR) :: farg1 

farg1 = self%swigptr
fresult = swigc_VectorLongLong_size(farg1)
swigf_result = fresult
end function

function swigf_VectorLongLong_capacity(self) &
result(swigf_result)
use, intrinsic :: ISO_C_BINDING
integer(C_LONG) :: swigf_result
class(VectorLongLong) :: self
integer(C_LONG) :: fresult 
type(C_PTR) :: farg1 

farg1 = self%swigptr
fresult = swigc_VectorLongLong_capacity(farg1)
swigf_result = fresult
end function

function swigf_VectorLongLong_empty(self) &
result(swigf_result)
use, intrinsic :: ISO_C_BINDING
logical(C_BOOL) :: swigf_result
class(VectorLongLong) :: self
logical(C_BOOL) :: fresult 
type(C_PTR) :: farg1 

farg1 = self%swigptr
fresult = swigc_VectorLongLong_empty(farg1)
swigf_result = fresult
end function

subroutine swigf_VectorLongLong_clear(self)
use, intrinsic :: ISO_C_BINDING
class(VectorLongLong) :: self
type(C_PTR) :: farg1 

farg1 = self%swigptr
call swigc_VectorLongLong_clear(farg1)
end subroutine

subroutine swigf_VectorLongLong_reserve(self, count)
use, intrinsic :: ISO_C_BINDING
class(VectorLongLong) :: self
integer(C_LONG), intent(in) :: count
type(C_PTR) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigptr
farg2 = count
call swigc_VectorLongLong_reserve(farg1, farg2)
end subroutine

subroutine swigf_VectorLongLong_resize__SWIG_0(self, count)
use, intrinsic :: ISO_C_BINDING
class(VectorLongLong) :: self
integer(C_LONG), intent(in) :: count
type(C_PTR) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigptr
farg2 = count
call swigc_VectorLongLong_resize__SWIG_0(farg1, farg2)
end subroutine

subroutine swigf_VectorLongLong_resize__SWIG_1(self, count, v)
use, intrinsic :: ISO_C_BINDING
class(VectorLongLong) :: self
integer(C_LONG), intent(in) :: count
integer(C_LONG_LONG), intent(in) :: v
type(C_PTR) :: farg1 
integer(C_LONG) :: farg2 
integer(C_LONG_LONG) :: farg3 

farg1 = self%swigptr
farg2 = count
farg3 = v
call swigc_VectorLongLong_resize__SWIG_1(farg1, farg2, farg3)
end subroutine

subroutine swigf_VectorLongLong_push_back(self, v)
use, intrinsic :: ISO_C_BINDING
class(VectorLongLong) :: self
integer(C_LONG_LONG), intent(in) :: v
type(C_PTR) :: farg1 
integer(C_LONG_LONG) :: farg2 

farg1 = self%swigptr
farg2 = v
call swigc_VectorLongLong_push_back(farg1, farg2)
end subroutine

function swigf_VectorLongLong_front(self) &
result(swigf_result)
use, intrinsic :: ISO_C_BINDING
integer(C_LONG_LONG) :: swigf_result
class(VectorLongLong) :: self
integer(C_LONG_LONG) :: fresult 
type(C_PTR) :: farg1 

farg1 = self%swigptr
fresult = swigc_VectorLongLong_front(farg1)
swigf_result = fresult
end function

function swigf_VectorLongLong_back(self) &
result(swigf_result)
use, intrinsic :: ISO_C_BINDING
integer(C_LONG_LONG) :: swigf_result
class(VectorLongLong) :: self
integer(C_LONG_LONG) :: fresult 
type(C_PTR) :: farg1 

farg1 = self%swigptr
fresult = swigc_VectorLongLong_back(farg1)
swigf_result = fresult
end function

subroutine swigf_VectorLongLong_set(self, index, v)
use, intrinsic :: ISO_C_BINDING
class(VectorLongLong) :: self
integer(C_LONG), intent(in) :: index
integer(C_LONG_LONG), intent(in) :: v
type(C_PTR) :: farg1 
integer(C_LONG) :: farg2 
integer(C_LONG_LONG) :: farg3 

farg1 = self%swigptr
farg2 = index
farg3 = v
call swigc_VectorLongLong_set(farg1, farg2, farg3)
end subroutine

function swigf_VectorLongLong_get(self, index) &
result(swigf_result)
use, intrinsic :: ISO_C_BINDING
integer(C_LONG_LONG) :: swigf_result
class(VectorLongLong) :: self
integer(C_LONG), intent(in) :: index
integer(C_LONG_LONG) :: fresult 
type(C_PTR) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigptr
farg2 = index
fresult = swigc_VectorLongLong_get(farg1, farg2)
swigf_result = fresult
end function

subroutine swigf_delete_VectorLongLong(self)
use, intrinsic :: ISO_C_BINDING
class(VectorLongLong) :: self
type(C_PTR) :: farg1 

if (.not. c_associated(self%swigptr)) return
farg1 = self%swigptr
call swigc_delete_VectorLongLong(farg1)
self%swigptr = C_NULL_PTR
end subroutine

subroutine swigf_new_TeuchosComm__SWIG_0(self, rawmpicomm)
use, intrinsic :: ISO_C_BINDING
class(TeuchosComm) :: self
integer(C_INT), intent(in) :: rawmpicomm
type(C_PTR) :: fresult 
integer(C_INT) :: farg1 

if (c_associated(self%swigptr)) call self%release()
farg1 = rawmpicomm
fresult = swigc_new_TeuchosComm__SWIG_0(farg1)
self%swigptr = fresult
end subroutine

subroutine swigf_new_TeuchosComm__SWIG_1(self)
use, intrinsic :: ISO_C_BINDING
class(TeuchosComm) :: self
type(C_PTR) :: fresult 

if (c_associated(self%swigptr)) call self%release()
fresult = swigc_new_TeuchosComm__SWIG_1()
self%swigptr = fresult
end subroutine

function swigf_TeuchosComm_getRank(self) &
result(swigf_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swigf_result
class(TeuchosComm) :: self
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 

farg1 = self%swigptr
fresult = swigc_TeuchosComm_getRank(farg1)
swigf_result = fresult
end function

function swigf_TeuchosComm_getSize(self) &
result(swigf_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swigf_result
class(TeuchosComm) :: self
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 

farg1 = self%swigptr
fresult = swigc_TeuchosComm_getSize(farg1)
swigf_result = fresult
end function

subroutine swigf_TeuchosComm_barrier(self)
use, intrinsic :: ISO_C_BINDING
class(TeuchosComm) :: self
type(C_PTR) :: farg1 

farg1 = self%swigptr
call swigc_TeuchosComm_barrier(farg1)
end subroutine

subroutine swigf_delete_TeuchosComm(self)
use, intrinsic :: ISO_C_BINDING
class(TeuchosComm) :: self
type(C_PTR) :: farg1 

if (.not. c_associated(self%swigptr)) return
farg1 = self%swigptr
call swigc_delete_TeuchosComm(farg1)
self%swigptr = C_NULL_PTR
end subroutine

  subroutine swigf_assign_TeuchosComm(self, other)
   use, intrinsic :: ISO_C_BINDING
   class(TeuchosComm), intent(inout) :: self
   type(TeuchosComm), intent(in) :: other
if (c_associated(self%swigptr)) call self%release()
   self%swigptr = swigc_spcopy_TeuchosComm(other%swigptr)
  end subroutine
subroutine swigf_new_string(self)
use, intrinsic :: ISO_C_BINDING
class(string) :: self
type(C_PTR) :: fresult 

if (c_associated(self%swigptr)) call self%release()
fresult = swigc_new_string()
self%swigptr = fresult
end subroutine

subroutine swigf_string_resize(self, count)
use, intrinsic :: ISO_C_BINDING
class(string) :: self
integer(C_LONG), intent(in) :: count
type(C_PTR) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigptr
farg2 = count
call swigc_string_resize(farg1, farg2)
end subroutine

subroutine swigf_string_clear(self)
use, intrinsic :: ISO_C_BINDING
class(string) :: self
type(C_PTR) :: farg1 

farg1 = self%swigptr
call swigc_string_clear(farg1)
end subroutine

function swigf_string_size(self) &
result(swigf_result)
use, intrinsic :: ISO_C_BINDING
integer(C_LONG) :: swigf_result
class(string) :: self
integer(C_LONG) :: fresult 
type(C_PTR) :: farg1 

farg1 = self%swigptr
fresult = swigc_string_size(farg1)
swigf_result = fresult
end function

function swigf_string_length(self) &
result(swigf_result)
use, intrinsic :: ISO_C_BINDING
integer(C_LONG) :: swigf_result
class(string) :: self
integer(C_LONG) :: fresult 
type(C_PTR) :: farg1 

farg1 = self%swigptr
fresult = swigc_string_length(farg1)
swigf_result = fresult
end function

subroutine swigf_string_set(self, pos, v)
use, intrinsic :: ISO_C_BINDING
class(string) :: self
integer(C_LONG), intent(in) :: pos
integer(C_SIGNED_CHAR), intent(in) :: v
type(C_PTR) :: farg1 
integer(C_LONG) :: farg2 
integer(C_SIGNED_CHAR) :: farg3 

farg1 = self%swigptr
farg2 = pos
farg3 = v
call swigc_string_set(farg1, farg2, farg3)
end subroutine

function swigf_string_get(self, pos) &
result(swigf_result)
use, intrinsic :: ISO_C_BINDING
integer(C_SIGNED_CHAR) :: swigf_result
class(string) :: self
integer(C_LONG), intent(in) :: pos
integer(C_SIGNED_CHAR) :: fresult 
type(C_PTR) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigptr
farg2 = pos
fresult = swigc_string_get(farg1, farg2)
swigf_result = fresult
end function

subroutine swigf_delete_string(self)
use, intrinsic :: ISO_C_BINDING
class(string) :: self
type(C_PTR) :: farg1 

if (.not. c_associated(self%swigptr)) return
farg1 = self%swigptr
call swigc_delete_string(farg1)
self%swigptr = C_NULL_PTR
end subroutine

subroutine swigf_ParameterList_print(self)
use, intrinsic :: ISO_C_BINDING
class(ParameterList) :: self
type(C_PTR) :: farg1 

farg1 = self%swigptr
call swigc_ParameterList_print(farg1)
end subroutine

subroutine swigf_new_ParameterList__SWIG_0(self)
use, intrinsic :: ISO_C_BINDING
class(ParameterList) :: self
type(C_PTR) :: fresult 

if (c_associated(self%swigptr)) call self%release()
fresult = swigc_new_ParameterList__SWIG_0()
self%swigptr = fresult
end subroutine

subroutine swigf_new_ParameterList__SWIG_1(self, name)
use, intrinsic :: ISO_C_BINDING
class(ParameterList) :: self
character(kind=C_CHAR, len=*), target :: name
type(C_PTR) :: fresult 
type(SwigfArrayWrapper) :: farg1 

if (c_associated(self%swigptr)) call self%release()
farg1%data = c_loc(name)
farg1%size = len(name)
fresult = swigc_new_ParameterList__SWIG_1(farg1)
self%swigptr = fresult
end subroutine

subroutine swigf_ParameterList_get__SWIG_0(self, name, value)
use, intrinsic :: ISO_C_BINDING
class(ParameterList) :: self
character(kind=C_CHAR, len=*), target :: name
real(C_DOUBLE), target, intent(inout) :: value
type(C_PTR) :: farg1 
type(SwigfArrayWrapper) :: farg2 
type(C_PTR) :: farg3 

farg1 = self%swigptr
farg2%data = c_loc(name)
farg2%size = len(name)
farg3 = c_loc(value)
call swigc_ParameterList_get__SWIG_0(farg1, farg2, farg3)
end subroutine

subroutine swigf_ParameterList_set__SWIG_0(self, name, value)
use, intrinsic :: ISO_C_BINDING
class(ParameterList) :: self
character(kind=C_CHAR, len=*), target :: name
real(C_DOUBLE), intent(in) :: value
type(C_PTR) :: farg1 
type(SwigfArrayWrapper) :: farg2 
real(C_DOUBLE) :: farg3 

farg1 = self%swigptr
farg2%data = c_loc(name)
farg2%size = len(name)
farg3 = value
call swigc_ParameterList_set__SWIG_0(farg1, farg2, farg3)
end subroutine

subroutine swigf_ParameterList_get__SWIG_1(self, name, value)
use, intrinsic :: ISO_C_BINDING
class(ParameterList) :: self
character(kind=C_CHAR, len=*), target :: name
integer(C_INT), target, intent(inout) :: value
type(C_PTR) :: farg1 
type(SwigfArrayWrapper) :: farg2 
type(C_PTR) :: farg3 

farg1 = self%swigptr
farg2%data = c_loc(name)
farg2%size = len(name)
farg3 = c_loc(value)
call swigc_ParameterList_get__SWIG_1(farg1, farg2, farg3)
end subroutine

subroutine swigf_ParameterList_set__SWIG_1(self, name, value)
use, intrinsic :: ISO_C_BINDING
class(ParameterList) :: self
character(kind=C_CHAR, len=*), target :: name
integer(C_INT), intent(in) :: value
type(C_PTR) :: farg1 
type(SwigfArrayWrapper) :: farg2 
integer(C_INT) :: farg3 

farg1 = self%swigptr
farg2%data = c_loc(name)
farg2%size = len(name)
farg3 = value
call swigc_ParameterList_set__SWIG_1(farg1, farg2, farg3)
end subroutine

subroutine swigf_ParameterList_set__SWIG_2(self, name, value)
use, intrinsic :: ISO_C_BINDING
class(ParameterList) :: self
character(kind=C_CHAR, len=*), target :: name
character(kind=C_CHAR, len=*), target :: value
type(C_PTR) :: farg1 
type(SwigfArrayWrapper) :: farg2 
type(SwigfArrayWrapper) :: farg3 

farg1 = self%swigptr
farg2%data = c_loc(name)
farg2%size = len(name)
farg3%data = c_loc(value)
farg3%size = len(value)
call swigc_ParameterList_set__SWIG_2(farg1, farg2, farg3)
end subroutine

subroutine swigf_ParameterList_get__SWIG_2(self, name, value)
use, intrinsic :: ISO_C_BINDING
class(ParameterList) :: self
character(kind=C_CHAR, len=*), target :: name
character(kind=C_CHAR, len=*), target :: value
type(C_PTR) :: farg1 
type(SwigfArrayWrapper) :: farg2 
type(SwigfArrayWrapper) :: farg3 

farg1 = self%swigptr
farg2%data = c_loc(name)
farg2%size = len(name)
farg3%data = c_loc(value)
farg3%size = len(value)
call swigc_ParameterList_get__SWIG_2(farg1, farg2, farg3)
end subroutine

subroutine swigf_ParameterList_set__SWIG_3(self, name, value)
use, intrinsic :: ISO_C_BINDING
class(ParameterList) :: self
character(kind=C_CHAR, len=*), target :: name
real(C_DOUBLE), dimension(:), target, intent(inout) :: value
type(C_PTR) :: farg1 
type(SwigfArrayWrapper) :: farg2 
type(SwigfArrayWrapper) :: farg3 

farg1 = self%swigptr
farg2%data = c_loc(name)
farg2%size = len(name)
farg3%data = c_loc(value(1))
farg3%size = size(value)
call swigc_ParameterList_set__SWIG_3(farg1, farg2, farg3)
end subroutine

subroutine swigf_ParameterList_get__SWIG_3(self, name, value)
use, intrinsic :: ISO_C_BINDING
class(ParameterList) :: self
character(kind=C_CHAR, len=*), target :: name
real(C_DOUBLE), dimension(:), target, intent(inout) :: value
type(C_PTR) :: farg1 
type(SwigfArrayWrapper) :: farg2 
type(SwigfArrayWrapper) :: farg3 

farg1 = self%swigptr
farg2%data = c_loc(name)
farg2%size = len(name)
farg3%data = c_loc(value(1))
farg3%size = size(value)
call swigc_ParameterList_get__SWIG_3(farg1, farg2, farg3)
end subroutine

subroutine swigf_ParameterList_set__SWIG_4(self, name, value)
use, intrinsic :: ISO_C_BINDING
class(ParameterList) :: self
character(kind=C_CHAR, len=*), target :: name
integer(C_INT), dimension(:), target, intent(inout) :: value
type(C_PTR) :: farg1 
type(SwigfArrayWrapper) :: farg2 
type(SwigfArrayWrapper) :: farg3 

farg1 = self%swigptr
farg2%data = c_loc(name)
farg2%size = len(name)
farg3%data = c_loc(value(1))
farg3%size = size(value)
call swigc_ParameterList_set__SWIG_4(farg1, farg2, farg3)
end subroutine

subroutine swigf_ParameterList_get__SWIG_4(self, name, value)
use, intrinsic :: ISO_C_BINDING
class(ParameterList) :: self
character(kind=C_CHAR, len=*), target :: name
integer(C_INT), dimension(:), target, intent(inout) :: value
type(C_PTR) :: farg1 
type(SwigfArrayWrapper) :: farg2 
type(SwigfArrayWrapper) :: farg3 

farg1 = self%swigptr
farg2%data = c_loc(name)
farg2%size = len(name)
farg3%data = c_loc(value(1))
farg3%size = size(value)
call swigc_ParameterList_get__SWIG_4(farg1, farg2, farg3)
end subroutine

subroutine swigf_ParameterList_set__SWIG_5(self, name, plist)
use, intrinsic :: ISO_C_BINDING
class(ParameterList) :: self
character(kind=C_CHAR, len=*), target :: name
type(ParameterList) :: plist
type(C_PTR) :: farg1 
type(SwigfArrayWrapper) :: farg2 
type(C_PTR) :: farg3 

farg1 = self%swigptr
farg2%data = c_loc(name)
farg2%size = len(name)
farg3 = plist%swigptr
call swigc_ParameterList_set__SWIG_5(farg1, farg2, farg3)
end subroutine

subroutine swigf_ParameterList_get__SWIG_5(self, name, plist)
use, intrinsic :: ISO_C_BINDING
class(ParameterList) :: self
character(kind=C_CHAR, len=*), target :: name
type(ParameterList) :: plist
type(C_PTR) :: farg1 
type(SwigfArrayWrapper) :: farg2 
type(C_PTR) :: farg3 

farg1 = self%swigptr
farg2%data = c_loc(name)
farg2%size = len(name)
farg3 = plist%swigptr
call swigc_ParameterList_get__SWIG_5(farg1, farg2, farg3)
end subroutine

function swigf_ParameterList_sublist(self, name) &
result(swigf_result)
use, intrinsic :: ISO_C_BINDING
type(ParameterList) :: swigf_result
class(ParameterList) :: self
character(kind=C_CHAR, len=*), target :: name
type(C_PTR) :: fresult 
type(C_PTR) :: farg1 
type(SwigfArrayWrapper) :: farg2 

farg1 = self%swigptr
farg2%data = c_loc(name)
farg2%size = len(name)
fresult = swigc_ParameterList_sublist(farg1, farg2)
swigf_result%swigptr = fresult
end function

function swigf_ParameterList_get_length(self, name) &
result(swigf_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swigf_result
class(ParameterList) :: self
character(kind=C_CHAR, len=*), target :: name
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(SwigfArrayWrapper) :: farg2 

farg1 = self%swigptr
farg2%data = c_loc(name)
farg2%size = len(name)
fresult = swigc_ParameterList_get_length(farg1, farg2)
swigf_result = fresult
end function

subroutine swigf_ParameterList_remove(self, name)
use, intrinsic :: ISO_C_BINDING
class(ParameterList) :: self
character(kind=C_CHAR, len=*), target :: name
type(C_PTR) :: farg1 
type(SwigfArrayWrapper) :: farg2 

farg1 = self%swigptr
farg2%data = c_loc(name)
farg2%size = len(name)
call swigc_ParameterList_remove(farg1, farg2)
end subroutine

function swigf_ParameterList_is_parameter(self, name) &
result(swigf_result)
use, intrinsic :: ISO_C_BINDING
logical(C_BOOL) :: swigf_result
class(ParameterList) :: self
character(kind=C_CHAR, len=*), target :: name
logical(C_BOOL) :: fresult 
type(C_PTR) :: farg1 
type(SwigfArrayWrapper) :: farg2 

farg1 = self%swigptr
farg2%data = c_loc(name)
farg2%size = len(name)
fresult = swigc_ParameterList_is_parameter(farg1, farg2)
swigf_result = fresult
end function

subroutine swigf_delete_ParameterList(self)
use, intrinsic :: ISO_C_BINDING
class(ParameterList) :: self
type(C_PTR) :: farg1 

if (.not. c_associated(self%swigptr)) return
farg1 = self%swigptr
call swigc_delete_ParameterList(farg1)
self%swigptr = C_NULL_PTR
end subroutine

  subroutine swigf_assign_ParameterList(self, other)
   use, intrinsic :: ISO_C_BINDING
   class(ParameterList), intent(inout) :: self
   type(ParameterList), intent(in) :: other
if (c_associated(self%swigptr)) call self%release()
   self%swigptr = swigc_spcopy_ParameterList(other%swigptr)
  end subroutine
subroutine load_from_xml(plist, xml)
use, intrinsic :: ISO_C_BINDING
type(ParameterList) :: plist
character(kind=C_CHAR, len=*), target :: xml
type(C_PTR) :: farg1 
type(SwigfArrayWrapper) :: farg2 

farg1 = plist%swigptr
farg2%data = c_loc(xml)
farg2%size = len(xml)
call swigc_load_from_xml(farg1, farg2)
end subroutine

subroutine save_to_xml(plist, xml)
use, intrinsic :: ISO_C_BINDING
class(ParameterList) :: plist
character(kind=C_CHAR, len=*), target :: xml
type(C_PTR) :: farg1 
type(SwigfArrayWrapper) :: farg2 

farg1 = plist%swigptr
farg2%data = c_loc(xml)
farg2%size = len(xml)
call swigc_save_to_xml(farg1, farg2)
end subroutine


end module forteuchos
