/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

/*
 * Copyright 2017-2018, UT-Battelle, LLC
 *
 * SPDX-License-Identifier: BSD-3-Clause
 * License-Filename: LICENSE
 */


#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* qualifier for exported *const* global data variables*/
#ifndef SWIGEXTERN
# ifdef __cplusplus
#   define SWIGEXTERN extern
# else
#   define SWIGEXTERN
# endif
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif

/*  Errors in SWIG */
#define  SWIG_UnknownError    	   -1
#define  SWIG_IOError        	   -2
#define  SWIG_RuntimeError   	   -3
#define  SWIG_IndexError     	   -4
#define  SWIG_TypeError      	   -5
#define  SWIG_DivisionByZero 	   -6
#define  SWIG_OverflowError  	   -7
#define  SWIG_SyntaxError    	   -8
#define  SWIG_ValueError     	   -9
#define  SWIG_SystemError    	   -10
#define  SWIG_AttributeError 	   -11
#define  SWIG_MemoryError    	   -12
#define  SWIG_NullReferenceError   -13




#define SWIG_exception_impl(DECL, CODE, MSG, RETURNNULL) \
 { throw std::logic_error("In " DECL ": " MSG); RETURNNULL; }


extern "C" {
void SWIG_check_unhandled_exception_impl(const char* decl);
void SWIG_store_exception(const char* decl, int errcode, const char *msg);
}


#undef SWIG_exception_impl
#define SWIG_exception_impl(DECL, CODE, MSG, RETURNNULL) \
    SWIG_store_exception(DECL, CODE, MSG); RETURNNULL;


namespace swig {

enum AssignmentFlags {
  IS_DESTR       = 0x01,
  IS_COPY_CONSTR = 0x02,
  IS_COPY_ASSIGN = 0x04,
  IS_MOVE_CONSTR = 0x08,
  IS_MOVE_ASSIGN = 0x10
};

template<class T, int Flags>
struct assignment_flags;
}


#define SWIG_assign(LEFTTYPE, LEFT, RIGHTTYPE, RIGHT, FLAGS) \
    SWIG_assign_impl<LEFTTYPE , RIGHTTYPE, swig::assignment_flags<LEFTTYPE, FLAGS >::value >(LEFT, RIGHT);


#define SWIG_check_sp_nonnull(INPUT, TYPENAME, FNAME, FUNCNAME, RETURNNULL) \
  if (!(INPUT)) { \
    SWIG_exception_impl(FUNCNAME, SWIG_TypeError, \
                        "Cannot pass null " TYPENAME " (class " FNAME ") " \
                        "as a reference", RETURNNULL); \
  }


#include <stdexcept>


#define SWIGVERSION 0x040000 
#define SWIG_VERSION SWIGVERSION


#define SWIG_as_voidptr(a) const_cast< void * >(static_cast< const void * >(a)) 
#define SWIG_as_voidptrptr(a) ((void)SWIG_as_voidptr(*a),reinterpret_cast< void** >(a)) 


#include <utility>


namespace swig {
template<class T, class U, int Flags>
struct assignment_flags<std::pair<const T, U>, Flags> {
  enum { value = IS_DESTR | IS_COPY_CONSTR };
};
template<class T, class U, int Flags>
struct assignment_flags<std::pair<T, const U>, Flags> {
  enum { value = IS_DESTR | IS_COPY_CONSTR };
};
}


#include <string>


#include "Teuchos_BLAS_types.hpp"
#include "Teuchos_DataAccess.hpp"


#include "Teuchos_Exceptions.hpp"


#include "Teuchos_RCP.hpp"


#include "Teuchos_Array.hpp"


#include "Teuchos_ArrayView.hpp"


#include "Teuchos_ArrayRCP.hpp"


#include "Teuchos_Comm.hpp"
#ifdef HAVE_MPI
# include "Teuchos_DefaultMpiComm.hpp"
#else
  typedef int MPI_Comm;
#endif
#include "Teuchos_DefaultSerialComm.hpp"


enum SwigMemState {
    SWIG_NULL = 0,
    SWIG_OWN,
    SWIG_MOVE,
    SWIG_REF,
    SWIG_CREF
};


struct SwigClassWrapper {
    void* ptr;
    SwigMemState mem;
};


SWIGINTERN SwigClassWrapper SwigClassWrapper_uninitialized() {
    SwigClassWrapper result;
    result.ptr = NULL;
    result.mem = SWIG_NULL;
    return result;
}

SWIGINTERN Teuchos::Comm< int > *new_Teuchos_Comm_Sl_int_Sg___SWIG_0(MPI_Comm rawMpiComm){
#ifdef HAVE_MPI
      return new Teuchos::MpiComm<int>(rawMpiComm);
#else
      throw std::runtime_error("MPI based constructor cannot be called when MPI is not enabled.");
#endif
    }

#define SWIG_NO_NULL_DELETER_0 , Teuchos::RCP_WEAK_NO_DEALLOC
#define SWIG_NO_NULL_DELETER_1
#define SWIG_NO_NULL_DELETER_SWIG_POINTER_NEW
#define SWIG_NO_NULL_DELETER_SWIG_POINTER_OWN

SWIGINTERN Teuchos::Comm< int > *new_Teuchos_Comm_Sl_int_Sg___SWIG_1(){
#ifdef HAVE_MPI
      return new Teuchos::MpiComm<int>(MPI_COMM_WORLD);
#else
      return new Teuchos::SerialComm<int>();
#endif
    }
SWIGINTERN MPI_Comm Teuchos_Comm_Sl_int_Sg__getRawMpiComm(Teuchos::Comm< int > *self){
#ifdef HAVE_MPI
      Teuchos::MpiComm<int>& comm = dynamic_cast<Teuchos::MpiComm<int>&>(*self);
      return *comm.getRawMpiComm();
#else
      throw std::runtime_error("MPI based constructor cannot be called when MPI is not enabled.");
#endif
    }

namespace swig {

// Define our own switching struct to support pre-c++11 builds
template<bool Val>
struct bool_constant {};
typedef bool_constant<true>  true_type;
typedef bool_constant<false> false_type;

// Deletion
template<class T>
SWIGINTERN void destruct_impl(T* self, true_type) {
  delete self;
}
template<class T>
SWIGINTERN T* destruct_impl(T* , false_type) {
  SWIG_exception_impl("assignment", SWIG_TypeError,
                      "Invalid assignment: class type has no destructor",
                      return NULL);
}

// Copy construction and assignment
template<class T, class U>
SWIGINTERN T* copy_construct_impl(const U* other, true_type) {
  return new T(*other);
}
template<class T, class U>
SWIGINTERN void copy_assign_impl(T* self, const U* other, true_type) {
  *self = *other;
}

// Disabled construction and assignment
template<class T, class U>
SWIGINTERN T* copy_construct_impl(const U* , false_type) {
  SWIG_exception_impl("assignment", SWIG_TypeError,
                      "Invalid assignment: class type has no copy constructor",
                      return NULL);
}
template<class T, class U>
SWIGINTERN void copy_assign_impl(T* , const U* , false_type) {
  SWIG_exception_impl("assignment", SWIG_TypeError,
                      "Invalid assignment: class type has no copy assignment",
                      return);
}

#if __cplusplus >= 201103L
#include <utility>
#include <type_traits>

// Move construction and assignment
template<class T, class U>
SWIGINTERN T* move_construct_impl(U* other, true_type) {
  return new T(std::move(*other));
}
template<class T, class U>
SWIGINTERN void move_assign_impl(T* self, U* other, true_type) {
  *self = std::move(*other);
}

// Disabled move construction and assignment
template<class T, class U>
SWIGINTERN T* move_construct_impl(U*, false_type) {
  SWIG_exception_impl("assignment", SWIG_TypeError,
                      "Invalid assignment: class type has no move constructor",
                      return NULL);
}
template<class T, class U>
SWIGINTERN void move_assign_impl(T*, U*, false_type) {
  SWIG_exception_impl("assignment", SWIG_TypeError,
                      "Invalid assignment: class type has no move assignment",
                      return);
}

template<class T, int Flags>
struct assignment_flags {
  constexpr static int value =
             (std::is_destructible<T>::value       ? IS_DESTR       : 0)
           | (std::is_copy_constructible<T>::value ? IS_COPY_CONSTR : 0)
           | (std::is_copy_assignable<T>::value    ? IS_COPY_ASSIGN : 0)
           | (std::is_move_constructible<T>::value ? IS_MOVE_CONSTR : 0)
           | (std::is_move_assignable<T>::value    ? IS_MOVE_ASSIGN : 0);
};

#else

template<class T, int Flags>
struct assignment_flags {
  enum { value = Flags };
};

#endif

template<class T, int Flags>
struct AssignmentTraits {
  static void destruct(T* self) {
    destruct_impl<T>(self, bool_constant<Flags & IS_DESTR>());
  }

  template<class U>
  static T* copy_construct(const U* other) {
    return copy_construct_impl<T,U>(other, bool_constant<bool(Flags & IS_COPY_CONSTR)>());
  }

  template<class U>
  static void copy_assign(T* self, const U* other) {
    copy_assign_impl<T,U>(self, other, bool_constant<bool(Flags & IS_COPY_ASSIGN)>());
  }

#if __cplusplus >= 201103L
  template<class U>
  static T* move_construct(U* other) {
    return move_construct_impl<T,U>(other, bool_constant<bool(Flags & IS_MOVE_CONSTR)>());
  }
  template<class U>
  static void move_assign(T* self, U* other) {
    move_assign_impl<T,U>(self, other, bool_constant<bool(Flags & IS_MOVE_ASSIGN)>());
  }
#else
  template<class U>
  static T* move_construct(U* other) {
    return copy_construct_impl<T,U>(other, bool_constant<bool(Flags & IS_COPY_CONSTR)>());
  }
  template<class U>
  static void move_assign(T* self, U* other) {
    copy_assign_impl<T,U>(self, other, bool_constant<bool(Flags & IS_COPY_ASSIGN)>());
  }
#endif
};

} // end namespace swig


template<class T1, class T2, int AFlags>
SWIGINTERN void SWIG_assign_impl(SwigClassWrapper* self, SwigClassWrapper* other) {
  typedef swig::AssignmentTraits<T1, AFlags> Traits_t;
  T1* pself  = static_cast<T1*>(self->ptr);
  T2* pother = static_cast<T2*>(other->ptr);

  switch (self->mem) {
    case SWIG_NULL:
      /* LHS is unassigned */
      switch (other->mem) {
        case SWIG_NULL: /* null op */ break;
        case SWIG_MOVE: /* capture pointer from RHS */
          self->ptr = other->ptr;
          other->ptr = NULL;
          self->mem = SWIG_OWN;
          other->mem = SWIG_NULL;
          break;
        case SWIG_OWN: /* copy from RHS */
          self->ptr = Traits_t::copy_construct(pother);
          self->mem = SWIG_OWN;
          break;
        case SWIG_REF: /* pointer to RHS */
        case SWIG_CREF:
          self->ptr = other->ptr;
          self->mem = other->mem;
          break;
      }
      break;
    case SWIG_OWN:
      /* LHS owns memory */
      switch (other->mem) {
        case SWIG_NULL:
          /* Delete LHS */
          Traits_t::destruct(pself);
          self->ptr = NULL;
          self->mem = SWIG_NULL;
          break;
        case SWIG_MOVE:
          /* Move RHS into LHS; delete RHS */
          Traits_t::move_assign(pself, pother);
          Traits_t::destruct(pother);
          other->ptr = NULL;
          other->mem = SWIG_NULL;
          break;
        case SWIG_OWN:
        case SWIG_REF:
        case SWIG_CREF:
          /* Copy RHS to LHS */
          Traits_t::copy_assign(pself, pother);
          break;
      }
      break;
    case SWIG_MOVE:
      SWIG_exception_impl("assignment", SWIG_RuntimeError,
        "Left-hand side of assignment should never be in a 'MOVE' state",
        return);
      break;
    case SWIG_REF:
      /* LHS is a reference */
      switch (other->mem) {
        case SWIG_NULL:
          /* Remove LHS reference */
          self->ptr = NULL;
          self->mem = SWIG_NULL;
          break;
        case SWIG_MOVE:
          /* Move RHS into LHS; delete RHS. The original ownership stays the
           * same. */
          Traits_t::move_assign(pself, pother);
          Traits_t::destruct(pother);
          other->ptr = NULL;
          other->mem = SWIG_NULL;
          break;
        case SWIG_OWN:
        case SWIG_REF:
        case SWIG_CREF:
          /* Copy RHS to LHS */
          Traits_t::copy_assign(pself, pother);
          break;
      }
      break;
    case SWIG_CREF:
      switch (other->mem) {
        case SWIG_NULL:
          /* Remove LHS reference */
          self->ptr = NULL;
          self->mem = SWIG_NULL;
        default:
          SWIG_exception_impl("assignment", SWIG_RuntimeError,
              "Cannot assign to a const reference", return);
          break;
      }
      break;
  }
}


#include "Teuchos_ParameterList.hpp"


#include <stdlib.h>
#ifdef _MSC_VER
# ifndef strtoull
#  define strtoull _strtoui64
# endif
# ifndef strtoll
#  define strtoll _strtoi64
# endif
#endif


struct SwigArrayWrapper {
    void* data;
    size_t size;
};


SWIGINTERN SwigArrayWrapper SwigArrayWrapper_uninitialized() {
  SwigArrayWrapper result;
  result.data = NULL;
  result.size = 0;
  return result;
}


#include "Teuchos_XMLParameterListCoreHelpers.hpp"


void load_from_xml(const Teuchos::RCP<Teuchos::ParameterList>& plist,
                   const std::string& xml_path)
{
    Teuchos::updateParametersFromXmlFile(xml_path, Teuchos::inOutArg(*plist));
}

void save_to_xml(const Teuchos::ParameterList& plist,
                 const std::string& xml_path)
{
    Teuchos::writeParameterListToXmlFile(plist, xml_path);
}

#ifdef __cplusplus
extern "C" {
#endif
SWIGEXPORT int swigc_TeuchosComm_getRank(SwigClassWrapper const *farg1) {
  int fresult ;
  Teuchos::Comm< int > *arg1 = (Teuchos::Comm< int > *) 0 ;
  Teuchos::RCP< Teuchos::Comm< int > const > *smartarg1 ;
  int result;
  
  smartarg1 = static_cast< Teuchos::RCP<const Teuchos::Comm<int> >* >(farg1->ptr);
  arg1 = smartarg1 ? const_cast<Teuchos::Comm<int>*>(smartarg1->get()) : NULL;
  {
    // Make sure no unhandled exceptions exist before performing a new action
    SWIG_check_unhandled_exception_impl("Teuchos::Comm< int >::getRank() const");;
    try
    {
      // Attempt the wrapped function call
      result = (int)((Teuchos::Comm< int > const *)arg1)->getRank();
    }
    catch (const std::range_error& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::Comm< int >::getRank() const", SWIG_IndexError, e.what(), return 0);
    }
    catch (const std::exception& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::Comm< int >::getRank() const", SWIG_RuntimeError, e.what(), return 0);
    }
    catch (...)
    {
      SWIG_exception_impl("Teuchos::Comm< int >::getRank() const", SWIG_UnknownError, "An unknown exception occurred", return 0);
    }
  }
  fresult = result;
  return fresult;
}


SWIGEXPORT int swigc_TeuchosComm_getSize(SwigClassWrapper const *farg1) {
  int fresult ;
  Teuchos::Comm< int > *arg1 = (Teuchos::Comm< int > *) 0 ;
  Teuchos::RCP< Teuchos::Comm< int > const > *smartarg1 ;
  int result;
  
  smartarg1 = static_cast< Teuchos::RCP<const Teuchos::Comm<int> >* >(farg1->ptr);
  arg1 = smartarg1 ? const_cast<Teuchos::Comm<int>*>(smartarg1->get()) : NULL;
  {
    // Make sure no unhandled exceptions exist before performing a new action
    SWIG_check_unhandled_exception_impl("Teuchos::Comm< int >::getSize() const");;
    try
    {
      // Attempt the wrapped function call
      result = (int)((Teuchos::Comm< int > const *)arg1)->getSize();
    }
    catch (const std::range_error& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::Comm< int >::getSize() const", SWIG_IndexError, e.what(), return 0);
    }
    catch (const std::exception& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::Comm< int >::getSize() const", SWIG_RuntimeError, e.what(), return 0);
    }
    catch (...)
    {
      SWIG_exception_impl("Teuchos::Comm< int >::getSize() const", SWIG_UnknownError, "An unknown exception occurred", return 0);
    }
  }
  fresult = result;
  return fresult;
}


SWIGEXPORT void swigc_TeuchosComm_barrier(SwigClassWrapper const *farg1) {
  Teuchos::Comm< int > *arg1 = (Teuchos::Comm< int > *) 0 ;
  Teuchos::RCP< Teuchos::Comm< int > const > *smartarg1 ;
  
  smartarg1 = static_cast< Teuchos::RCP<const Teuchos::Comm<int> >* >(farg1->ptr);
  arg1 = smartarg1 ? const_cast<Teuchos::Comm<int>*>(smartarg1->get()) : NULL;
  {
    // Make sure no unhandled exceptions exist before performing a new action
    SWIG_check_unhandled_exception_impl("Teuchos::Comm< int >::barrier() const");;
    try
    {
      // Attempt the wrapped function call
      ((Teuchos::Comm< int > const *)arg1)->barrier();
    }
    catch (const std::range_error& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::Comm< int >::barrier() const", SWIG_IndexError, e.what(), return );
    }
    catch (const std::exception& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::Comm< int >::barrier() const", SWIG_RuntimeError, e.what(), return );
    }
    catch (...)
    {
      SWIG_exception_impl("Teuchos::Comm< int >::barrier() const", SWIG_UnknownError, "An unknown exception occurred", return );
    }
  }
  
}


SWIGEXPORT SwigClassWrapper swigc_new_TeuchosComm__SWIG_0(int const *farg1) {
  SwigClassWrapper fresult ;
  MPI_Comm arg1 ;
  Teuchos::Comm< int > *result = 0 ;
  
#ifdef HAVE_MPI
  arg1 = MPI_Comm_f2c(static_cast< MPI_Fint >(*farg1));
#else
  arg1 = *farg1;
#endif
  {
    // Make sure no unhandled exceptions exist before performing a new action
    SWIG_check_unhandled_exception_impl("Teuchos::Comm< int >::Comm(MPI_Comm)");;
    try
    {
      // Attempt the wrapped function call
      result = (Teuchos::Comm< int > *)new_Teuchos_Comm_Sl_int_Sg___SWIG_0(arg1);
    }
    catch (const std::range_error& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::Comm< int >::Comm(MPI_Comm)", SWIG_IndexError, e.what(), return SwigClassWrapper_uninitialized());
    }
    catch (const std::exception& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::Comm< int >::Comm(MPI_Comm)", SWIG_RuntimeError, e.what(), return SwigClassWrapper_uninitialized());
    }
    catch (...)
    {
      SWIG_exception_impl("Teuchos::Comm< int >::Comm(MPI_Comm)", SWIG_UnknownError, "An unknown exception occurred", return SwigClassWrapper_uninitialized());
    }
  }
  fresult.ptr = result ? new Teuchos::RCP< Teuchos::Comm<int> >(result SWIG_NO_NULL_DELETER_1) : NULL;
  fresult.mem = SWIG_MOVE;
  return fresult;
}


SWIGEXPORT SwigClassWrapper swigc_new_TeuchosComm__SWIG_1() {
  SwigClassWrapper fresult ;
  Teuchos::Comm< int > *result = 0 ;
  
  {
    // Make sure no unhandled exceptions exist before performing a new action
    SWIG_check_unhandled_exception_impl("Teuchos::Comm< int >::Comm()");;
    try
    {
      // Attempt the wrapped function call
      result = (Teuchos::Comm< int > *)new_Teuchos_Comm_Sl_int_Sg___SWIG_1();
    }
    catch (const std::range_error& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::Comm< int >::Comm()", SWIG_IndexError, e.what(), return SwigClassWrapper_uninitialized());
    }
    catch (const std::exception& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::Comm< int >::Comm()", SWIG_RuntimeError, e.what(), return SwigClassWrapper_uninitialized());
    }
    catch (...)
    {
      SWIG_exception_impl("Teuchos::Comm< int >::Comm()", SWIG_UnknownError, "An unknown exception occurred", return SwigClassWrapper_uninitialized());
    }
  }
  fresult.ptr = result ? new Teuchos::RCP< Teuchos::Comm<int> >(result SWIG_NO_NULL_DELETER_1) : NULL;
  fresult.mem = SWIG_MOVE;
  return fresult;
}


SWIGEXPORT int swigc_TeuchosComm_getRawMpiComm(SwigClassWrapper const *farg1) {
  int fresult ;
  Teuchos::Comm< int > *arg1 = (Teuchos::Comm< int > *) 0 ;
  Teuchos::RCP< Teuchos::Comm< int > > *smartarg1 ;
  MPI_Comm result;
  
  smartarg1 = static_cast< Teuchos::RCP< Teuchos::Comm<int> >* >(farg1->ptr);
  arg1 = smartarg1 ? smartarg1->get() : NULL;
  {
    // Make sure no unhandled exceptions exist before performing a new action
    SWIG_check_unhandled_exception_impl("Teuchos::Comm< int >::getRawMpiComm()");;
    try
    {
      // Attempt the wrapped function call
      result = Teuchos_Comm_Sl_int_Sg__getRawMpiComm(arg1);
    }
    catch (const std::range_error& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::Comm< int >::getRawMpiComm()", SWIG_IndexError, e.what(), return 0);
    }
    catch (const std::exception& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::Comm< int >::getRawMpiComm()", SWIG_RuntimeError, e.what(), return 0);
    }
    catch (...)
    {
      SWIG_exception_impl("Teuchos::Comm< int >::getRawMpiComm()", SWIG_UnknownError, "An unknown exception occurred", return 0);
    }
  }
#ifdef HAVE_MPI
  fresult = static_cast< int >(MPI_Comm_c2f(result));
#else
  fresult = result;
#endif
  return fresult;
}


SWIGEXPORT void swigc_delete_TeuchosComm(SwigClassWrapper const *farg1) {
  Teuchos::Comm< int > *arg1 = (Teuchos::Comm< int > *) 0 ;
  Teuchos::RCP< Teuchos::Comm< int > > *smartarg1 ;
  
  smartarg1 = static_cast< Teuchos::RCP< Teuchos::Comm<int> >* >(farg1->ptr);
  arg1 = smartarg1 ? smartarg1->get() : NULL;
  {
    // Make sure no unhandled exceptions exist before performing a new action
    SWIG_check_unhandled_exception_impl("Teuchos::Comm< int >::~Comm()");;
    try
    {
      // Attempt the wrapped function call
      (void)arg1; delete smartarg1; 
    }
    catch (const std::range_error& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::Comm< int >::~Comm()", SWIG_IndexError, e.what(), return );
    }
    catch (const std::exception& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::Comm< int >::~Comm()", SWIG_RuntimeError, e.what(), return );
    }
    catch (...)
    {
      SWIG_exception_impl("Teuchos::Comm< int >::~Comm()", SWIG_UnknownError, "An unknown exception occurred", return );
    }
  }
  
}


SWIGEXPORT void swigc_assignment_TeuchosComm(SwigClassWrapper * self, SwigClassWrapper const * other) {
  typedef Teuchos::RCP< Teuchos::Comm<int> > swig_lhs_classtype;
  SWIG_assign(swig_lhs_classtype, self,
    swig_lhs_classtype, const_cast<SwigClassWrapper*>(other),
    0 | swig::IS_DESTR | swig::IS_COPY_CONSTR);
}


SWIGEXPORT SwigClassWrapper swigc_new_ParameterList__SWIG_0() {
  SwigClassWrapper fresult ;
  Teuchos::ParameterList *result = 0 ;
  
  {
    // Make sure no unhandled exceptions exist before performing a new action
    SWIG_check_unhandled_exception_impl("Teuchos::ParameterList::ParameterList()");;
    try
    {
      // Attempt the wrapped function call
      result = (Teuchos::ParameterList *)new Teuchos::ParameterList();
    }
    catch (const std::range_error& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::ParameterList()", SWIG_IndexError, e.what(), return SwigClassWrapper_uninitialized());
    }
    catch (const std::exception& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::ParameterList()", SWIG_RuntimeError, e.what(), return SwigClassWrapper_uninitialized());
    }
    catch (...)
    {
      SWIG_exception_impl("Teuchos::ParameterList::ParameterList()", SWIG_UnknownError, "An unknown exception occurred", return SwigClassWrapper_uninitialized());
    }
  }
  fresult.ptr = result ? new Teuchos::RCP< Teuchos::ParameterList >(result SWIG_NO_NULL_DELETER_1) : NULL;
  fresult.mem = SWIG_MOVE;
  return fresult;
}


SWIGEXPORT SwigClassWrapper swigc_new_ParameterList__SWIG_1(SwigArrayWrapper *farg1) {
  SwigClassWrapper fresult ;
  std::string *arg1 = 0 ;
  std::string tempstr1 ;
  Teuchos::ParameterList *result = 0 ;
  
  tempstr1 = std::string(static_cast<const char *>(farg1->data), farg1->size);
  arg1 = &tempstr1;
  {
    // Make sure no unhandled exceptions exist before performing a new action
    SWIG_check_unhandled_exception_impl("Teuchos::ParameterList::ParameterList(std::string const &)");;
    try
    {
      // Attempt the wrapped function call
      result = (Teuchos::ParameterList *)new Teuchos::ParameterList((std::string const &)*arg1);
    }
    catch (const std::range_error& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::ParameterList(std::string const &)", SWIG_IndexError, e.what(), return SwigClassWrapper_uninitialized());
    }
    catch (const std::exception& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::ParameterList(std::string const &)", SWIG_RuntimeError, e.what(), return SwigClassWrapper_uninitialized());
    }
    catch (...)
    {
      SWIG_exception_impl("Teuchos::ParameterList::ParameterList(std::string const &)", SWIG_UnknownError, "An unknown exception occurred", return SwigClassWrapper_uninitialized());
    }
  }
  fresult.ptr = result ? new Teuchos::RCP< Teuchos::ParameterList >(result SWIG_NO_NULL_DELETER_1) : NULL;
  fresult.mem = SWIG_MOVE;
  return fresult;
}


SWIGEXPORT void swigc_ParameterList_print(SwigClassWrapper const *farg1) {
  Teuchos::ParameterList *arg1 = (Teuchos::ParameterList *) 0 ;
  Teuchos::RCP< Teuchos::ParameterList const > *smartarg1 ;
  
  smartarg1 = static_cast< Teuchos::RCP<const Teuchos::ParameterList >* >(farg1->ptr);
  arg1 = smartarg1 ? const_cast<Teuchos::ParameterList*>(smartarg1->get()) : NULL;
  {
    // Make sure no unhandled exceptions exist before performing a new action
    SWIG_check_unhandled_exception_impl("Teuchos::ParameterList::print() const");;
    try
    {
      // Attempt the wrapped function call
      ((Teuchos::ParameterList const *)arg1)->print();
    }
    catch (const std::range_error& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::print() const", SWIG_IndexError, e.what(), return );
    }
    catch (const std::exception& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::print() const", SWIG_RuntimeError, e.what(), return );
    }
    catch (...)
    {
      SWIG_exception_impl("Teuchos::ParameterList::print() const", SWIG_UnknownError, "An unknown exception occurred", return );
    }
  }
  
}


SWIGEXPORT void swigc_ParameterList_remove(SwigClassWrapper const *farg1, SwigArrayWrapper *farg2) {
  Teuchos::ParameterList *arg1 = (Teuchos::ParameterList *) 0 ;
  std::string *arg2 = 0 ;
  Teuchos::RCP< Teuchos::ParameterList > *smartarg1 ;
  std::string tempstr2 ;
  
  smartarg1 = static_cast< Teuchos::RCP< Teuchos::ParameterList >* >(farg1->ptr);
  arg1 = smartarg1 ? smartarg1->get() : NULL;
  tempstr2 = std::string(static_cast<const char *>(farg2->data), farg2->size);
  arg2 = &tempstr2;
  {
    // Make sure no unhandled exceptions exist before performing a new action
    SWIG_check_unhandled_exception_impl("Teuchos::ParameterList::remove(std::string const &)");;
    try
    {
      // Attempt the wrapped function call
      (arg1)->remove((std::string const &)*arg2);
    }
    catch (const std::range_error& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::remove(std::string const &)", SWIG_IndexError, e.what(), return );
    }
    catch (const std::exception& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::remove(std::string const &)", SWIG_RuntimeError, e.what(), return );
    }
    catch (...)
    {
      SWIG_exception_impl("Teuchos::ParameterList::remove(std::string const &)", SWIG_UnknownError, "An unknown exception occurred", return );
    }
  }
  
}


SWIGEXPORT bool swigc_ParameterList_is_parameter(SwigClassWrapper const *farg1, SwigArrayWrapper *farg2) {
  bool fresult ;
  Teuchos::ParameterList *arg1 = (Teuchos::ParameterList *) 0 ;
  std::string *arg2 = 0 ;
  Teuchos::RCP< Teuchos::ParameterList const > *smartarg1 ;
  std::string tempstr2 ;
  bool result;
  
  smartarg1 = static_cast< Teuchos::RCP<const Teuchos::ParameterList >* >(farg1->ptr);
  arg1 = smartarg1 ? const_cast<Teuchos::ParameterList*>(smartarg1->get()) : NULL;
  tempstr2 = std::string(static_cast<const char *>(farg2->data), farg2->size);
  arg2 = &tempstr2;
  {
    // Make sure no unhandled exceptions exist before performing a new action
    SWIG_check_unhandled_exception_impl("Teuchos::ParameterList::isParameter(std::string const &) const");;
    try
    {
      // Attempt the wrapped function call
      result = (bool)((Teuchos::ParameterList const *)arg1)->isParameter((std::string const &)*arg2);
    }
    catch (const std::range_error& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::isParameter(std::string const &) const", SWIG_IndexError, e.what(), return 0);
    }
    catch (const std::exception& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::isParameter(std::string const &) const", SWIG_RuntimeError, e.what(), return 0);
    }
    catch (...)
    {
      SWIG_exception_impl("Teuchos::ParameterList::isParameter(std::string const &) const", SWIG_UnknownError, "An unknown exception occurred", return 0);
    }
  }
  fresult = result;
  return fresult;
}


SWIGEXPORT SwigClassWrapper swigc_ParameterList_sublist(SwigClassWrapper const *farg1, SwigArrayWrapper *farg2) {
  SwigClassWrapper fresult ;
  Teuchos::ParameterList *arg1 = (Teuchos::ParameterList *) 0 ;
  std::string *arg2 = 0 ;
  Teuchos::RCP< Teuchos::ParameterList > *smartarg1 ;
  std::string tempstr2 ;
  Teuchos::ParameterList *result = 0 ;
  
  smartarg1 = static_cast< Teuchos::RCP< Teuchos::ParameterList >* >(farg1->ptr);
  arg1 = smartarg1 ? smartarg1->get() : NULL;
  tempstr2 = std::string(static_cast<const char *>(farg2->data), farg2->size);
  arg2 = &tempstr2;
  {
    // Make sure no unhandled exceptions exist before performing a new action
    SWIG_check_unhandled_exception_impl("Teuchos::ParameterList::sublist(std::string const &)");;
    try
    {
      // Attempt the wrapped function call
      result = (Teuchos::ParameterList *) &(arg1)->sublist((std::string const &)*arg2);
    }
    catch (const std::range_error& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::sublist(std::string const &)", SWIG_IndexError, e.what(), return SwigClassWrapper_uninitialized());
    }
    catch (const std::exception& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::sublist(std::string const &)", SWIG_RuntimeError, e.what(), return SwigClassWrapper_uninitialized());
    }
    catch (...)
    {
      SWIG_exception_impl("Teuchos::ParameterList::sublist(std::string const &)", SWIG_UnknownError, "An unknown exception occurred", return SwigClassWrapper_uninitialized());
    }
  }
  {
    fresult.ptr = new Teuchos::RCP< Teuchos::ParameterList >(result SWIG_NO_NULL_DELETER_0);
    fresult.mem = SWIG_MOVE;
  }
  return fresult;
}


SWIGEXPORT void swigc_ParameterList_set__SWIG_1(SwigClassWrapper const *farg1, SwigArrayWrapper *farg2, double const *farg3) {
  Teuchos::ParameterList *arg1 = (Teuchos::ParameterList *) 0 ;
  std::string *arg2 = 0 ;
  double *arg3 = 0 ;
  Teuchos::RCP< Teuchos::ParameterList > *smartarg1 ;
  std::string tempstr2 ;
  
  smartarg1 = static_cast< Teuchos::RCP< Teuchos::ParameterList >* >(farg1->ptr);
  arg1 = smartarg1 ? smartarg1->get() : NULL;
  tempstr2 = std::string(static_cast<const char *>(farg2->data), farg2->size);
  arg2 = &tempstr2;
  arg3 = reinterpret_cast< double * >(const_cast< double* >(farg3));
  {
    // Make sure no unhandled exceptions exist before performing a new action
    SWIG_check_unhandled_exception_impl("Teuchos::ParameterList::set< double >(std::string const &,double const &)");;
    try
    {
      // Attempt the wrapped function call
      (arg1)->SWIGTEMPLATEDISAMBIGUATOR set< double >((std::string const &)*arg2,(double const &)*arg3);
    }
    catch (const std::range_error& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::set< double >(std::string const &,double const &)", SWIG_IndexError, e.what(), return );
    }
    catch (const std::exception& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::set< double >(std::string const &,double const &)", SWIG_RuntimeError, e.what(), return );
    }
    catch (...)
    {
      SWIG_exception_impl("Teuchos::ParameterList::set< double >(std::string const &,double const &)", SWIG_UnknownError, "An unknown exception occurred", return );
    }
  }
  
}


SWIGEXPORT void swigc_ParameterList_set__SWIG_2(SwigClassWrapper const *farg1, SwigArrayWrapper *farg2, int const *farg3) {
  Teuchos::ParameterList *arg1 = (Teuchos::ParameterList *) 0 ;
  std::string *arg2 = 0 ;
  int *arg3 = 0 ;
  Teuchos::RCP< Teuchos::ParameterList > *smartarg1 ;
  std::string tempstr2 ;
  
  smartarg1 = static_cast< Teuchos::RCP< Teuchos::ParameterList >* >(farg1->ptr);
  arg1 = smartarg1 ? smartarg1->get() : NULL;
  tempstr2 = std::string(static_cast<const char *>(farg2->data), farg2->size);
  arg2 = &tempstr2;
  arg3 = reinterpret_cast< int * >(const_cast< int* >(farg3));
  {
    // Make sure no unhandled exceptions exist before performing a new action
    SWIG_check_unhandled_exception_impl("Teuchos::ParameterList::set< int >(std::string const &,int const &)");;
    try
    {
      // Attempt the wrapped function call
      (arg1)->SWIGTEMPLATEDISAMBIGUATOR set< int >((std::string const &)*arg2,(int const &)*arg3);
    }
    catch (const std::range_error& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::set< int >(std::string const &,int const &)", SWIG_IndexError, e.what(), return );
    }
    catch (const std::exception& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::set< int >(std::string const &,int const &)", SWIG_RuntimeError, e.what(), return );
    }
    catch (...)
    {
      SWIG_exception_impl("Teuchos::ParameterList::set< int >(std::string const &,int const &)", SWIG_UnknownError, "An unknown exception occurred", return );
    }
  }
  
}


SWIGEXPORT void swigc_ParameterList_set__SWIG_3(SwigClassWrapper const *farg1, SwigArrayWrapper *farg2, long long const *farg3) {
  Teuchos::ParameterList *arg1 = (Teuchos::ParameterList *) 0 ;
  std::string *arg2 = 0 ;
  long long *arg3 = 0 ;
  Teuchos::RCP< Teuchos::ParameterList > *smartarg1 ;
  std::string tempstr2 ;
  
  smartarg1 = static_cast< Teuchos::RCP< Teuchos::ParameterList >* >(farg1->ptr);
  arg1 = smartarg1 ? smartarg1->get() : NULL;
  tempstr2 = std::string(static_cast<const char *>(farg2->data), farg2->size);
  arg2 = &tempstr2;
  arg3 = reinterpret_cast< long long * >(const_cast< long long* >(farg3));
  {
    // Make sure no unhandled exceptions exist before performing a new action
    SWIG_check_unhandled_exception_impl("Teuchos::ParameterList::set< long long >(std::string const &,long long const &)");;
    try
    {
      // Attempt the wrapped function call
      (arg1)->SWIGTEMPLATEDISAMBIGUATOR set< long long >((std::string const &)*arg2,(long long const &)*arg3);
    }
    catch (const std::range_error& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::set< long long >(std::string const &,long long const &)", SWIG_IndexError, e.what(), return );
    }
    catch (const std::exception& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::set< long long >(std::string const &,long long const &)", SWIG_RuntimeError, e.what(), return );
    }
    catch (...)
    {
      SWIG_exception_impl("Teuchos::ParameterList::set< long long >(std::string const &,long long const &)", SWIG_UnknownError, "An unknown exception occurred", return );
    }
  }
  
}


SWIGEXPORT void swigc_ParameterList_set__SWIG_4(SwigClassWrapper const *farg1, SwigArrayWrapper *farg2, bool const *farg3) {
  Teuchos::ParameterList *arg1 = (Teuchos::ParameterList *) 0 ;
  std::string *arg2 = 0 ;
  bool *arg3 = 0 ;
  Teuchos::RCP< Teuchos::ParameterList > *smartarg1 ;
  std::string tempstr2 ;
  
  smartarg1 = static_cast< Teuchos::RCP< Teuchos::ParameterList >* >(farg1->ptr);
  arg1 = smartarg1 ? smartarg1->get() : NULL;
  tempstr2 = std::string(static_cast<const char *>(farg2->data), farg2->size);
  arg2 = &tempstr2;
  arg3 = reinterpret_cast< bool * >(const_cast< bool* >(farg3));
  {
    // Make sure no unhandled exceptions exist before performing a new action
    SWIG_check_unhandled_exception_impl("Teuchos::ParameterList::set< bool >(std::string const &,bool const &)");;
    try
    {
      // Attempt the wrapped function call
      (arg1)->SWIGTEMPLATEDISAMBIGUATOR set< bool >((std::string const &)*arg2,(bool const &)*arg3);
    }
    catch (const std::range_error& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::set< bool >(std::string const &,bool const &)", SWIG_IndexError, e.what(), return );
    }
    catch (const std::exception& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::set< bool >(std::string const &,bool const &)", SWIG_RuntimeError, e.what(), return );
    }
    catch (...)
    {
      SWIG_exception_impl("Teuchos::ParameterList::set< bool >(std::string const &,bool const &)", SWIG_UnknownError, "An unknown exception occurred", return );
    }
  }
  
}


SWIGEXPORT void swigc_ParameterList_set__SWIG_5(SwigClassWrapper const *farg1, SwigArrayWrapper *farg2, SwigArrayWrapper *farg3) {
  Teuchos::ParameterList *arg1 = (Teuchos::ParameterList *) 0 ;
  std::string *arg2 = 0 ;
  std::string *arg3 = 0 ;
  Teuchos::RCP< Teuchos::ParameterList > *smartarg1 ;
  std::string tempstr2 ;
  std::string tempstr3 ;
  
  smartarg1 = static_cast< Teuchos::RCP< Teuchos::ParameterList >* >(farg1->ptr);
  arg1 = smartarg1 ? smartarg1->get() : NULL;
  tempstr2 = std::string(static_cast<const char *>(farg2->data), farg2->size);
  arg2 = &tempstr2;
  tempstr3 = std::string(static_cast<const char *>(farg3->data), farg3->size);
  arg3 = &tempstr3;
  {
    // Make sure no unhandled exceptions exist before performing a new action
    SWIG_check_unhandled_exception_impl("Teuchos::ParameterList::set< std::string >(std::string const &,std::string const &)");;
    try
    {
      // Attempt the wrapped function call
      (arg1)->SWIGTEMPLATEDISAMBIGUATOR set< std::string >((std::string const &)*arg2,(std::string const &)*arg3);
    }
    catch (const std::range_error& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::set< std::string >(std::string const &,std::string const &)", SWIG_IndexError, e.what(), return );
    }
    catch (const std::exception& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::set< std::string >(std::string const &,std::string const &)", SWIG_RuntimeError, e.what(), return );
    }
    catch (...)
    {
      SWIG_exception_impl("Teuchos::ParameterList::set< std::string >(std::string const &,std::string const &)", SWIG_UnknownError, "An unknown exception occurred", return );
    }
  }
  
}


SWIGEXPORT void swigc_ParameterList_set__SWIG_6(SwigClassWrapper const *farg1, SwigArrayWrapper *farg2, SwigArrayWrapper *farg3) {
  Teuchos::ParameterList *arg1 = (Teuchos::ParameterList *) 0 ;
  std::string *arg2 = 0 ;
  Teuchos::Array< double > *arg3 = 0 ;
  Teuchos::RCP< Teuchos::ParameterList > *smartarg1 ;
  std::string tempstr2 ;
  Teuchos::Array< double > temparr3 ;
  Teuchos::Array< double >::value_type *tempbegin3 ;
  
  smartarg1 = static_cast< Teuchos::RCP< Teuchos::ParameterList >* >(farg1->ptr);
  arg1 = smartarg1 ? smartarg1->get() : NULL;
  tempstr2 = std::string(static_cast<const char *>(farg2->data), farg2->size);
  arg2 = &tempstr2;
  tempbegin3 = static_cast<Teuchos::Array<double>::value_type*>(farg3->data);
  temparr3.assign(tempbegin3, tempbegin3 + farg3->size);
  arg3 = &temparr3;
  {
    // Make sure no unhandled exceptions exist before performing a new action
    SWIG_check_unhandled_exception_impl("Teuchos::ParameterList::set< Teuchos::Array< double > >(std::string const &,Teuchos::Array< double > const &)");;
    try
    {
      // Attempt the wrapped function call
      (arg1)->SWIGTEMPLATEDISAMBIGUATOR set< Teuchos::Array< double > >((std::string const &)*arg2,(Teuchos::Array< double > const &)*arg3);
    }
    catch (const std::range_error& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::set< Teuchos::Array< double > >(std::string const &,Teuchos::Array< double > const &)", SWIG_IndexError, e.what(), return );
    }
    catch (const std::exception& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::set< Teuchos::Array< double > >(std::string const &,Teuchos::Array< double > const &)", SWIG_RuntimeError, e.what(), return );
    }
    catch (...)
    {
      SWIG_exception_impl("Teuchos::ParameterList::set< Teuchos::Array< double > >(std::string const &,Teuchos::Array< double > const &)", SWIG_UnknownError, "An unknown exception occurred", return );
    }
  }
  
}


SWIGEXPORT void swigc_ParameterList_set__SWIG_7(SwigClassWrapper const *farg1, SwigArrayWrapper *farg2, SwigArrayWrapper *farg3) {
  Teuchos::ParameterList *arg1 = (Teuchos::ParameterList *) 0 ;
  std::string *arg2 = 0 ;
  Teuchos::Array< int > *arg3 = 0 ;
  Teuchos::RCP< Teuchos::ParameterList > *smartarg1 ;
  std::string tempstr2 ;
  Teuchos::Array< int > temparr3 ;
  Teuchos::Array< int >::value_type *tempbegin3 ;
  
  smartarg1 = static_cast< Teuchos::RCP< Teuchos::ParameterList >* >(farg1->ptr);
  arg1 = smartarg1 ? smartarg1->get() : NULL;
  tempstr2 = std::string(static_cast<const char *>(farg2->data), farg2->size);
  arg2 = &tempstr2;
  tempbegin3 = static_cast<Teuchos::Array<int>::value_type*>(farg3->data);
  temparr3.assign(tempbegin3, tempbegin3 + farg3->size);
  arg3 = &temparr3;
  {
    // Make sure no unhandled exceptions exist before performing a new action
    SWIG_check_unhandled_exception_impl("Teuchos::ParameterList::set< Teuchos::Array< int > >(std::string const &,Teuchos::Array< int > const &)");;
    try
    {
      // Attempt the wrapped function call
      (arg1)->SWIGTEMPLATEDISAMBIGUATOR set< Teuchos::Array< int > >((std::string const &)*arg2,(Teuchos::Array< int > const &)*arg3);
    }
    catch (const std::range_error& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::set< Teuchos::Array< int > >(std::string const &,Teuchos::Array< int > const &)", SWIG_IndexError, e.what(), return );
    }
    catch (const std::exception& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::set< Teuchos::Array< int > >(std::string const &,Teuchos::Array< int > const &)", SWIG_RuntimeError, e.what(), return );
    }
    catch (...)
    {
      SWIG_exception_impl("Teuchos::ParameterList::set< Teuchos::Array< int > >(std::string const &,Teuchos::Array< int > const &)", SWIG_UnknownError, "An unknown exception occurred", return );
    }
  }
  
}


SWIGEXPORT void swigc_ParameterList_set__SWIG_8(SwigClassWrapper const *farg1, SwigArrayWrapper *farg2, SwigArrayWrapper *farg3) {
  Teuchos::ParameterList *arg1 = (Teuchos::ParameterList *) 0 ;
  std::string *arg2 = 0 ;
  Teuchos::Array< long long > *arg3 = 0 ;
  Teuchos::RCP< Teuchos::ParameterList > *smartarg1 ;
  std::string tempstr2 ;
  Teuchos::Array< long long > temparr3 ;
  Teuchos::Array< long long >::value_type *tempbegin3 ;
  
  smartarg1 = static_cast< Teuchos::RCP< Teuchos::ParameterList >* >(farg1->ptr);
  arg1 = smartarg1 ? smartarg1->get() : NULL;
  tempstr2 = std::string(static_cast<const char *>(farg2->data), farg2->size);
  arg2 = &tempstr2;
  tempbegin3 = static_cast<Teuchos::Array<long long>::value_type*>(farg3->data);
  temparr3.assign(tempbegin3, tempbegin3 + farg3->size);
  arg3 = &temparr3;
  {
    // Make sure no unhandled exceptions exist before performing a new action
    SWIG_check_unhandled_exception_impl("Teuchos::ParameterList::set< Teuchos::Array< long long > >(std::string const &,Teuchos::Array< long long > const &)");;
    try
    {
      // Attempt the wrapped function call
      (arg1)->SWIGTEMPLATEDISAMBIGUATOR set< Teuchos::Array< long long > >((std::string const &)*arg2,(Teuchos::Array< long long > const &)*arg3);
    }
    catch (const std::range_error& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::set< Teuchos::Array< long long > >(std::string const &,Teuchos::Array< long long > const &)", SWIG_IndexError, e.what(), return );
    }
    catch (const std::exception& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::set< Teuchos::Array< long long > >(std::string const &,Teuchos::Array< long long > const &)", SWIG_RuntimeError, e.what(), return );
    }
    catch (...)
    {
      SWIG_exception_impl("Teuchos::ParameterList::set< Teuchos::Array< long long > >(std::string const &,Teuchos::Array< long long > const &)", SWIG_UnknownError, "An unknown exception occurred", return );
    }
  }
  
}


SWIGEXPORT void swigc_ParameterList_set__SWIG_9(SwigClassWrapper const *farg1, SwigArrayWrapper *farg2, SwigClassWrapper const *farg3) {
  Teuchos::ParameterList *arg1 = (Teuchos::ParameterList *) 0 ;
  std::string *arg2 = 0 ;
  Teuchos::ParameterList *arg3 = 0 ;
  Teuchos::RCP< Teuchos::ParameterList > *smartarg1 ;
  std::string tempstr2 ;
  Teuchos::RCP< Teuchos::ParameterList const > *smartarg3 ;
  
  smartarg1 = static_cast< Teuchos::RCP< Teuchos::ParameterList >* >(farg1->ptr);
  arg1 = smartarg1 ? smartarg1->get() : NULL;
  tempstr2 = std::string(static_cast<const char *>(farg2->data), farg2->size);
  arg2 = &tempstr2;
  SWIG_check_sp_nonnull(farg3, "Teuchos::ParameterList *", "ParameterList", "Teuchos::ParameterList::set< Teuchos::ParameterList >(std::string const &,Teuchos::ParameterList const &)", return )
  smartarg3 = static_cast< Teuchos::RCP<const Teuchos::ParameterList >* >(farg3->ptr);
  arg3 = const_cast<Teuchos::ParameterList*>(smartarg3->get());
  {
    // Make sure no unhandled exceptions exist before performing a new action
    SWIG_check_unhandled_exception_impl("Teuchos::ParameterList::set< Teuchos::ParameterList >(std::string const &,Teuchos::ParameterList const &)");;
    try
    {
      // Attempt the wrapped function call
      (arg1)->SWIGTEMPLATEDISAMBIGUATOR set< Teuchos::ParameterList >((std::string const &)*arg2,(Teuchos::ParameterList const &)*arg3);
    }
    catch (const std::range_error& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::set< Teuchos::ParameterList >(std::string const &,Teuchos::ParameterList const &)", SWIG_IndexError, e.what(), return );
    }
    catch (const std::exception& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::set< Teuchos::ParameterList >(std::string const &,Teuchos::ParameterList const &)", SWIG_RuntimeError, e.what(), return );
    }
    catch (...)
    {
      SWIG_exception_impl("Teuchos::ParameterList::set< Teuchos::ParameterList >(std::string const &,Teuchos::ParameterList const &)", SWIG_UnknownError, "An unknown exception occurred", return );
    }
  }
  
}


SWIGEXPORT double swigc_ParameterList_get_real(SwigClassWrapper const *farg1, SwigArrayWrapper *farg2) {
  double fresult ;
  Teuchos::ParameterList *arg1 = (Teuchos::ParameterList *) 0 ;
  std::string *arg2 = 0 ;
  Teuchos::RCP< Teuchos::ParameterList > *smartarg1 ;
  std::string tempstr2 ;
  double *result = 0 ;
  
  smartarg1 = static_cast< Teuchos::RCP< Teuchos::ParameterList >* >(farg1->ptr);
  arg1 = smartarg1 ? smartarg1->get() : NULL;
  tempstr2 = std::string(static_cast<const char *>(farg2->data), farg2->size);
  arg2 = &tempstr2;
  {
    // Make sure no unhandled exceptions exist before performing a new action
    SWIG_check_unhandled_exception_impl("Teuchos::ParameterList::get< double >(std::string const &)");;
    try
    {
      // Attempt the wrapped function call
      result = (double *) &(arg1)->SWIGTEMPLATEDISAMBIGUATOR get< double >((std::string const &)*arg2);
    }
    catch (const std::range_error& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::get< double >(std::string const &)", SWIG_IndexError, e.what(), return 0);
    }
    catch (const std::exception& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::get< double >(std::string const &)", SWIG_RuntimeError, e.what(), return 0);
    }
    catch (...)
    {
      SWIG_exception_impl("Teuchos::ParameterList::get< double >(std::string const &)", SWIG_UnknownError, "An unknown exception occurred", return 0);
    }
  }
  fresult = *result;
  return fresult;
}


SWIGEXPORT int swigc_ParameterList_get_integer(SwigClassWrapper const *farg1, SwigArrayWrapper *farg2) {
  int fresult ;
  Teuchos::ParameterList *arg1 = (Teuchos::ParameterList *) 0 ;
  std::string *arg2 = 0 ;
  Teuchos::RCP< Teuchos::ParameterList > *smartarg1 ;
  std::string tempstr2 ;
  int *result = 0 ;
  
  smartarg1 = static_cast< Teuchos::RCP< Teuchos::ParameterList >* >(farg1->ptr);
  arg1 = smartarg1 ? smartarg1->get() : NULL;
  tempstr2 = std::string(static_cast<const char *>(farg2->data), farg2->size);
  arg2 = &tempstr2;
  {
    // Make sure no unhandled exceptions exist before performing a new action
    SWIG_check_unhandled_exception_impl("Teuchos::ParameterList::get< int >(std::string const &)");;
    try
    {
      // Attempt the wrapped function call
      result = (int *) &(arg1)->SWIGTEMPLATEDISAMBIGUATOR get< int >((std::string const &)*arg2);
    }
    catch (const std::range_error& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::get< int >(std::string const &)", SWIG_IndexError, e.what(), return 0);
    }
    catch (const std::exception& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::get< int >(std::string const &)", SWIG_RuntimeError, e.what(), return 0);
    }
    catch (...)
    {
      SWIG_exception_impl("Teuchos::ParameterList::get< int >(std::string const &)", SWIG_UnknownError, "An unknown exception occurred", return 0);
    }
  }
  fresult = *result;
  return fresult;
}


SWIGEXPORT long long swigc_ParameterList_get_longlong(SwigClassWrapper const *farg1, SwigArrayWrapper *farg2) {
  long long fresult ;
  Teuchos::ParameterList *arg1 = (Teuchos::ParameterList *) 0 ;
  std::string *arg2 = 0 ;
  Teuchos::RCP< Teuchos::ParameterList > *smartarg1 ;
  std::string tempstr2 ;
  long long *result = 0 ;
  
  smartarg1 = static_cast< Teuchos::RCP< Teuchos::ParameterList >* >(farg1->ptr);
  arg1 = smartarg1 ? smartarg1->get() : NULL;
  tempstr2 = std::string(static_cast<const char *>(farg2->data), farg2->size);
  arg2 = &tempstr2;
  {
    // Make sure no unhandled exceptions exist before performing a new action
    SWIG_check_unhandled_exception_impl("Teuchos::ParameterList::get< long long >(std::string const &)");;
    try
    {
      // Attempt the wrapped function call
      result = (long long *) &(arg1)->SWIGTEMPLATEDISAMBIGUATOR get< long long >((std::string const &)*arg2);
    }
    catch (const std::range_error& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::get< long long >(std::string const &)", SWIG_IndexError, e.what(), return 0);
    }
    catch (const std::exception& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::get< long long >(std::string const &)", SWIG_RuntimeError, e.what(), return 0);
    }
    catch (...)
    {
      SWIG_exception_impl("Teuchos::ParameterList::get< long long >(std::string const &)", SWIG_UnknownError, "An unknown exception occurred", return 0);
    }
  }
  fresult = *result;
  return fresult;
}


SWIGEXPORT bool swigc_ParameterList_get_logical(SwigClassWrapper const *farg1, SwigArrayWrapper *farg2) {
  bool fresult ;
  Teuchos::ParameterList *arg1 = (Teuchos::ParameterList *) 0 ;
  std::string *arg2 = 0 ;
  Teuchos::RCP< Teuchos::ParameterList > *smartarg1 ;
  std::string tempstr2 ;
  bool *result = 0 ;
  
  smartarg1 = static_cast< Teuchos::RCP< Teuchos::ParameterList >* >(farg1->ptr);
  arg1 = smartarg1 ? smartarg1->get() : NULL;
  tempstr2 = std::string(static_cast<const char *>(farg2->data), farg2->size);
  arg2 = &tempstr2;
  {
    // Make sure no unhandled exceptions exist before performing a new action
    SWIG_check_unhandled_exception_impl("Teuchos::ParameterList::get< bool >(std::string const &)");;
    try
    {
      // Attempt the wrapped function call
      result = (bool *) &(arg1)->SWIGTEMPLATEDISAMBIGUATOR get< bool >((std::string const &)*arg2);
    }
    catch (const std::range_error& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::get< bool >(std::string const &)", SWIG_IndexError, e.what(), return 0);
    }
    catch (const std::exception& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::get< bool >(std::string const &)", SWIG_RuntimeError, e.what(), return 0);
    }
    catch (...)
    {
      SWIG_exception_impl("Teuchos::ParameterList::get< bool >(std::string const &)", SWIG_UnknownError, "An unknown exception occurred", return 0);
    }
  }
  fresult = *result;
  return fresult;
}


SWIGEXPORT SwigArrayWrapper swigc_ParameterList_get_string(SwigClassWrapper const *farg1, SwigArrayWrapper *farg2) {
  SwigArrayWrapper fresult ;
  Teuchos::ParameterList *arg1 = (Teuchos::ParameterList *) 0 ;
  std::string *arg2 = 0 ;
  Teuchos::RCP< Teuchos::ParameterList > *smartarg1 ;
  std::string tempstr2 ;
  std::string *result = 0 ;
  
  smartarg1 = static_cast< Teuchos::RCP< Teuchos::ParameterList >* >(farg1->ptr);
  arg1 = smartarg1 ? smartarg1->get() : NULL;
  tempstr2 = std::string(static_cast<const char *>(farg2->data), farg2->size);
  arg2 = &tempstr2;
  {
    // Make sure no unhandled exceptions exist before performing a new action
    SWIG_check_unhandled_exception_impl("Teuchos::ParameterList::get< std::string >(std::string const &)");;
    try
    {
      // Attempt the wrapped function call
      result = (std::string *) &(arg1)->SWIGTEMPLATEDISAMBIGUATOR get< std::string >((std::string const &)*arg2);
    }
    catch (const std::range_error& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::get< std::string >(std::string const &)", SWIG_IndexError, e.what(), return SwigArrayWrapper_uninitialized());
    }
    catch (const std::exception& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::get< std::string >(std::string const &)", SWIG_RuntimeError, e.what(), return SwigArrayWrapper_uninitialized());
    }
    catch (...)
    {
      SWIG_exception_impl("Teuchos::ParameterList::get< std::string >(std::string const &)", SWIG_UnknownError, "An unknown exception occurred", return SwigArrayWrapper_uninitialized());
    }
  }
  fresult.data = (result->empty() ? NULL : &(*result->begin()));
  fresult.size = result->size();
  return fresult;
}


SWIGEXPORT SwigArrayWrapper swigc_ParameterList_get_arr_real(SwigClassWrapper const *farg1, SwigArrayWrapper *farg2) {
  SwigArrayWrapper fresult ;
  Teuchos::ParameterList *arg1 = (Teuchos::ParameterList *) 0 ;
  std::string *arg2 = 0 ;
  Teuchos::RCP< Teuchos::ParameterList > *smartarg1 ;
  std::string tempstr2 ;
  Teuchos::Array< double > *result = 0 ;
  
  smartarg1 = static_cast< Teuchos::RCP< Teuchos::ParameterList >* >(farg1->ptr);
  arg1 = smartarg1 ? smartarg1->get() : NULL;
  tempstr2 = std::string(static_cast<const char *>(farg2->data), farg2->size);
  arg2 = &tempstr2;
  {
    // Make sure no unhandled exceptions exist before performing a new action
    SWIG_check_unhandled_exception_impl("Teuchos::ParameterList::get< Teuchos::Array< double > >(std::string const &)");;
    try
    {
      // Attempt the wrapped function call
      result = (Teuchos::Array< double > *) &(arg1)->SWIGTEMPLATEDISAMBIGUATOR get< Teuchos::Array< double > >((std::string const &)*arg2);
    }
    catch (const std::range_error& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::get< Teuchos::Array< double > >(std::string const &)", SWIG_IndexError, e.what(), return SwigArrayWrapper_uninitialized());
    }
    catch (const std::exception& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::get< Teuchos::Array< double > >(std::string const &)", SWIG_RuntimeError, e.what(), return SwigArrayWrapper_uninitialized());
    }
    catch (...)
    {
      SWIG_exception_impl("Teuchos::ParameterList::get< Teuchos::Array< double > >(std::string const &)", SWIG_UnknownError, "An unknown exception occurred", return SwigArrayWrapper_uninitialized());
    }
  }
  fresult.data = (result->empty() ? NULL : &(*result->begin()));
  fresult.size = result->size();
  return fresult;
}


SWIGEXPORT SwigArrayWrapper swigc_ParameterList_get_arr_integer(SwigClassWrapper const *farg1, SwigArrayWrapper *farg2) {
  SwigArrayWrapper fresult ;
  Teuchos::ParameterList *arg1 = (Teuchos::ParameterList *) 0 ;
  std::string *arg2 = 0 ;
  Teuchos::RCP< Teuchos::ParameterList > *smartarg1 ;
  std::string tempstr2 ;
  Teuchos::Array< int > *result = 0 ;
  
  smartarg1 = static_cast< Teuchos::RCP< Teuchos::ParameterList >* >(farg1->ptr);
  arg1 = smartarg1 ? smartarg1->get() : NULL;
  tempstr2 = std::string(static_cast<const char *>(farg2->data), farg2->size);
  arg2 = &tempstr2;
  {
    // Make sure no unhandled exceptions exist before performing a new action
    SWIG_check_unhandled_exception_impl("Teuchos::ParameterList::get< Teuchos::Array< int > >(std::string const &)");;
    try
    {
      // Attempt the wrapped function call
      result = (Teuchos::Array< int > *) &(arg1)->SWIGTEMPLATEDISAMBIGUATOR get< Teuchos::Array< int > >((std::string const &)*arg2);
    }
    catch (const std::range_error& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::get< Teuchos::Array< int > >(std::string const &)", SWIG_IndexError, e.what(), return SwigArrayWrapper_uninitialized());
    }
    catch (const std::exception& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::get< Teuchos::Array< int > >(std::string const &)", SWIG_RuntimeError, e.what(), return SwigArrayWrapper_uninitialized());
    }
    catch (...)
    {
      SWIG_exception_impl("Teuchos::ParameterList::get< Teuchos::Array< int > >(std::string const &)", SWIG_UnknownError, "An unknown exception occurred", return SwigArrayWrapper_uninitialized());
    }
  }
  fresult.data = (result->empty() ? NULL : &(*result->begin()));
  fresult.size = result->size();
  return fresult;
}


SWIGEXPORT SwigArrayWrapper swigc_ParameterList_get_arr_longlong(SwigClassWrapper const *farg1, SwigArrayWrapper *farg2) {
  SwigArrayWrapper fresult ;
  Teuchos::ParameterList *arg1 = (Teuchos::ParameterList *) 0 ;
  std::string *arg2 = 0 ;
  Teuchos::RCP< Teuchos::ParameterList > *smartarg1 ;
  std::string tempstr2 ;
  Teuchos::Array< long long > *result = 0 ;
  
  smartarg1 = static_cast< Teuchos::RCP< Teuchos::ParameterList >* >(farg1->ptr);
  arg1 = smartarg1 ? smartarg1->get() : NULL;
  tempstr2 = std::string(static_cast<const char *>(farg2->data), farg2->size);
  arg2 = &tempstr2;
  {
    // Make sure no unhandled exceptions exist before performing a new action
    SWIG_check_unhandled_exception_impl("Teuchos::ParameterList::get< Teuchos::Array< long long > >(std::string const &)");;
    try
    {
      // Attempt the wrapped function call
      result = (Teuchos::Array< long long > *) &(arg1)->SWIGTEMPLATEDISAMBIGUATOR get< Teuchos::Array< long long > >((std::string const &)*arg2);
    }
    catch (const std::range_error& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::get< Teuchos::Array< long long > >(std::string const &)", SWIG_IndexError, e.what(), return SwigArrayWrapper_uninitialized());
    }
    catch (const std::exception& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::get< Teuchos::Array< long long > >(std::string const &)", SWIG_RuntimeError, e.what(), return SwigArrayWrapper_uninitialized());
    }
    catch (...)
    {
      SWIG_exception_impl("Teuchos::ParameterList::get< Teuchos::Array< long long > >(std::string const &)", SWIG_UnknownError, "An unknown exception occurred", return SwigArrayWrapper_uninitialized());
    }
  }
  fresult.data = (result->empty() ? NULL : &(*result->begin()));
  fresult.size = result->size();
  return fresult;
}


SWIGEXPORT void swigc_delete_ParameterList(SwigClassWrapper const *farg1) {
  Teuchos::ParameterList *arg1 = (Teuchos::ParameterList *) 0 ;
  Teuchos::RCP< Teuchos::ParameterList > *smartarg1 ;
  
  smartarg1 = static_cast< Teuchos::RCP< Teuchos::ParameterList >* >(farg1->ptr);
  arg1 = smartarg1 ? smartarg1->get() : NULL;
  {
    // Make sure no unhandled exceptions exist before performing a new action
    SWIG_check_unhandled_exception_impl("Teuchos::ParameterList::~ParameterList()");;
    try
    {
      // Attempt the wrapped function call
      (void)arg1; delete smartarg1; 
    }
    catch (const std::range_error& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::~ParameterList()", SWIG_IndexError, e.what(), return );
    }
    catch (const std::exception& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("Teuchos::ParameterList::~ParameterList()", SWIG_RuntimeError, e.what(), return );
    }
    catch (...)
    {
      SWIG_exception_impl("Teuchos::ParameterList::~ParameterList()", SWIG_UnknownError, "An unknown exception occurred", return );
    }
  }
  
}


SWIGEXPORT void swigc_assignment_ParameterList(SwigClassWrapper * self, SwigClassWrapper const * other) {
  typedef Teuchos::RCP< Teuchos::ParameterList > swig_lhs_classtype;
  SWIG_assign(swig_lhs_classtype, self,
    swig_lhs_classtype, const_cast<SwigClassWrapper*>(other),
    0 | swig::IS_DESTR | swig::IS_COPY_CONSTR);
}


SWIGEXPORT void swigc_load_from_xml(SwigClassWrapper const *farg1, SwigArrayWrapper *farg2) {
  Teuchos::RCP< Teuchos::ParameterList > *arg1 = 0 ;
  std::string *arg2 = 0 ;
  Teuchos::RCP< Teuchos::ParameterList > tempnull1 ;
  std::string tempstr2 ;
  
  arg1 = farg1->ptr ? static_cast< Teuchos::RCP< Teuchos::ParameterList > * >(farg1->ptr) : &tempnull1;
  tempstr2 = std::string(static_cast<const char *>(farg2->data), farg2->size);
  arg2 = &tempstr2;
  {
    // Make sure no unhandled exceptions exist before performing a new action
    SWIG_check_unhandled_exception_impl("load_from_xml(Teuchos::RCP< Teuchos::ParameterList > const &,std::string const &)");;
    try
    {
      // Attempt the wrapped function call
      load_from_xml((Teuchos::RCP< Teuchos::ParameterList > const &)*arg1,(std::string const &)*arg2);
    }
    catch (const std::range_error& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("load_from_xml(Teuchos::RCP< Teuchos::ParameterList > const &,std::string const &)", SWIG_IndexError, e.what(), return );
    }
    catch (const std::exception& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("load_from_xml(Teuchos::RCP< Teuchos::ParameterList > const &,std::string const &)", SWIG_RuntimeError, e.what(), return );
    }
    catch (...)
    {
      SWIG_exception_impl("load_from_xml(Teuchos::RCP< Teuchos::ParameterList > const &,std::string const &)", SWIG_UnknownError, "An unknown exception occurred", return );
    }
  }
  
}


SWIGEXPORT void swigc_save_to_xml(SwigClassWrapper const *farg1, SwigArrayWrapper *farg2) {
  Teuchos::ParameterList *arg1 = 0 ;
  std::string *arg2 = 0 ;
  Teuchos::RCP< Teuchos::ParameterList const > *smartarg1 ;
  std::string tempstr2 ;
  
  SWIG_check_sp_nonnull(farg1, "Teuchos::ParameterList *", "ParameterList", "save_to_xml(Teuchos::ParameterList const &,std::string const &)", return )
  smartarg1 = static_cast< Teuchos::RCP<const Teuchos::ParameterList >* >(farg1->ptr);
  arg1 = const_cast<Teuchos::ParameterList*>(smartarg1->get());
  tempstr2 = std::string(static_cast<const char *>(farg2->data), farg2->size);
  arg2 = &tempstr2;
  {
    // Make sure no unhandled exceptions exist before performing a new action
    SWIG_check_unhandled_exception_impl("save_to_xml(Teuchos::ParameterList const &,std::string const &)");;
    try
    {
      // Attempt the wrapped function call
      save_to_xml((Teuchos::ParameterList const &)*arg1,(std::string const &)*arg2);
    }
    catch (const std::range_error& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("save_to_xml(Teuchos::ParameterList const &,std::string const &)", SWIG_IndexError, e.what(), return );
    }
    catch (const std::exception& e)
    {
      // Store a C++ exception
      SWIG_exception_impl("save_to_xml(Teuchos::ParameterList const &,std::string const &)", SWIG_RuntimeError, e.what(), return );
    }
    catch (...)
    {
      SWIG_exception_impl("save_to_xml(Teuchos::ParameterList const &,std::string const &)", SWIG_UnknownError, "An unknown exception occurred", return );
    }
  }
  
}


#ifdef __cplusplus
}
#endif

