/* Pass CLASSNAME to cpp using -DCLASSNAME= */

#define STRINGIFY0(X) #X
#define STRINGIFY(X) STRINGIFY0(X)

#define TEST_FILE0(X) X##_test_impls
#define TEST_CALLS_FILE0(X) X##_test_calls
#define TEST_EXEC_FILE0(X) X##_run_one_test.exe

#define TEST_FILE1(CLASSNAME) TEST_FILE0(CLASSNAME)
#define TEST_CALLS_FILE1(CLASSNAME) TEST_CALLS_FILE0(CLASSNAME)
#define TEST_EXEC_FILE1(CLASSNAME) TEST_EXEC_FILE0(CLASSNAME)

#define TEST_FILE2 TEST_FILE1(CLASSNAME)
#define TEST_CALLS_FILE2 TEST_CALLS_FILE1(CLASSNAME)
#define TEST_EXEC_FILE2 TEST_EXEC_FILE1(CLASSNAME)

#define TEST_FILE_STR2 STRINGIFY(TEST_FILE2)
#define TEST_CALLS_FILE_STR2 STRINGIFY(TEST_CALLS_FILE2)

/**/#define TEST_FILE TEST_FILE2
/**/#define TEST_CALLS_FILE TEST_CALLS_FILE2
/**/#define TEST_EXEC_FILE TEST_EXEC_FILE2
/**/#define TEST_FILE_STR TEST_FILE_STR2
/**/#define TEST_CALLS_FILE_STR TEST_CALLS_FILE_STR2
