! This file was automatically generated by SWIG (http://www.swig.org).
! Version 4.0.0
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.

! Copyright 2017, UT-Battelle, LLC
!
! SPDX-License-Identifier: BSD-3-Clause
! License-Filename: LICENSE

module fortrilinos
 use, intrinsic :: ISO_C_BINDING
 use forerror
 use forteuchos
 use fortpetra

 use, intrinsic :: iso_c_binding, only : &
   c_bool, &
   c_int, &
   c_long, &
   c_long_long, &
   c_size_t, &
   c_double, &
   scalar_type => c_double, &
   local_ordinal_type => c_int, &
   global_ordinal_type => c_long_long, &
   global_size_type => c_long, &
   size_type => c_size_t, &
   bool_type => c_bool, &
   int_type => c_int, &
   mag_type => c_double, &
   norm_type => c_double

 implicit none
 private

 ! PUBLIC METHODS AND TYPES

public :: scalar_type
public :: local_ordinal_type
public :: global_ordinal_type
public :: global_size_type
public :: size_type
public :: bool_type
public :: int_type
public :: mag_type
public :: norm_type

 public :: TrilinosSolver

 enum, bind(c)
  enumerator :: SwigMemState = -1
  enumerator :: SWIG_NULL = 0
  enumerator :: SWIG_OWN
  enumerator :: SWIG_MOVE
  enumerator :: SWIG_REF
  enumerator :: SWIG_CREF
 end enum


type, bind(C) :: SwigClassWrapper
  type(C_PTR), public :: ptr = C_NULL_PTR
  integer(C_INT), public :: mem = SWIG_NULL
end type

 public :: TrilinosEigenSolver

type, bind(C) :: SwigArrayWrapper
  type(C_PTR), public :: data = C_NULL_PTR
  integer(C_SIZE_T), public :: size = 0
end type

 public :: create_TrilinosEigenSolver
 interface create_TrilinosEigenSolver
  module procedure new_TrilinosEigenSolver
 end interface
 public :: create_TrilinosSolver
 interface create_TrilinosSolver
  module procedure new_TrilinosSolver
 end interface

 ! TYPES
 type :: TrilinosSolver
  ! These should be treated as PROTECTED data
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure, private :: init__SWIG_0 => swigf_TrilinosSolver_init__SWIG_0
  procedure, private :: init__SWIG_1 => swigf_TrilinosSolver_init__SWIG_1
  procedure :: setup_matrix => swigf_TrilinosSolver_setup_matrix
  procedure, private :: setup_operator__SWIG_0 => swigf_TrilinosSolver_setup_operator__SWIG_0
  procedure, private :: setup_operator__SWIG_1 => swigf_TrilinosSolver_setup_operator__SWIG_1
  procedure :: setup_solver => swigf_TrilinosSolver_setup_solver
  procedure :: solve => swigf_TrilinosSolver_solve
  procedure :: finalize => swigf_TrilinosSolver_finalize
  procedure :: release => delete_TrilinosSolver
  procedure, private :: swigf_assignment_TrilinosSolver
  generic :: init => init__SWIG_0, init__SWIG_1
  generic :: assignment(=) => swigf_assignment_TrilinosSolver
  generic :: setup_operator => setup_operator__SWIG_0, setup_operator__SWIG_1
 end type
 type :: TrilinosEigenSolver
  ! These should be treated as PROTECTED data
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure, private :: init__SWIG_0 => swigf_TrilinosEigenSolver_init__SWIG_0
  procedure, private :: init__SWIG_1 => swigf_TrilinosEigenSolver_init__SWIG_1
  procedure :: setup_matrix => swigf_TrilinosEigenSolver_setup_matrix
  procedure :: setup_matrix_rhs => swigf_TrilinosEigenSolver_setup_matrix_rhs
  procedure, private :: setup_operator__SWIG_0 => swigf_TrilinosEigenSolver_setup_operator__SWIG_0
  procedure, private :: setup_operator__SWIG_1 => swigf_TrilinosEigenSolver_setup_operator__SWIG_1
  procedure, private :: setup_operator_rhs__SWIG_0 => swigf_TrilinosEigenSolver_setup_operator_rhs__SWIG_0
  procedure, private :: setup_operator_rhs__SWIG_1 => swigf_TrilinosEigenSolver_setup_operator_rhs__SWIG_1
  procedure :: setup_solver => swigf_TrilinosEigenSolver_setup_solver
  procedure :: solve => swigf_TrilinosEigenSolver_solve
  procedure :: finalize => swigf_TrilinosEigenSolver_finalize
  procedure :: release => delete_TrilinosEigenSolver
  procedure, private :: swigf_assignment_TrilinosEigenSolver
  generic :: init => init__SWIG_0, init__SWIG_1
  generic :: assignment(=) => swigf_assignment_TrilinosEigenSolver
  generic :: setup_operator => setup_operator__SWIG_0, setup_operator__SWIG_1
  generic :: setup_operator_rhs => setup_operator_rhs__SWIG_0, setup_operator_rhs__SWIG_1
 end type


 ! WRAPPER DECLARATIONS
 interface
function swigc_new_TrilinosSolver() &
bind(C, name="swigc_new_TrilinosSolver") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: SwigClassWrapper
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_TrilinosSolver_init__SWIG_0(farg1) &
bind(C, name="swigc_TrilinosSolver_init__SWIG_0")
use, intrinsic :: ISO_C_BINDING
import :: SwigClassWrapper
type(SwigClassWrapper) :: farg1
end subroutine

subroutine swigc_TrilinosSolver_init__SWIG_1(farg1, farg2) &
bind(C, name="swigc_TrilinosSolver_init__SWIG_1")
use, intrinsic :: ISO_C_BINDING
import :: SwigClassWrapper
type(SwigClassWrapper) :: farg1
type(SwigClassWrapper) :: farg2
end subroutine

subroutine swigc_TrilinosSolver_setup_matrix(farg1, farg2) &
bind(C, name="swigc_TrilinosSolver_setup_matrix")
use, intrinsic :: ISO_C_BINDING
import :: SwigClassWrapper
type(SwigClassWrapper) :: farg1
type(SwigClassWrapper) :: farg2
end subroutine

subroutine swigc_TrilinosSolver_setup_operator__SWIG_0(farg1, farg2, farg3, farg4) &
bind(C, name="swigc_TrilinosSolver_setup_operator__SWIG_0")
use, intrinsic :: ISO_C_BINDING
import :: SwigClassWrapper
type(SwigClassWrapper) :: farg1
type(C_FUNPTR), value :: farg2
type(SwigClassWrapper) :: farg3
type(SwigClassWrapper) :: farg4
end subroutine

subroutine swigc_TrilinosSolver_setup_operator__SWIG_1(farg1, farg2, farg3) &
bind(C, name="swigc_TrilinosSolver_setup_operator__SWIG_1")
use, intrinsic :: ISO_C_BINDING
import :: SwigClassWrapper
type(SwigClassWrapper) :: farg1
type(C_FUNPTR), value :: farg2
type(SwigClassWrapper) :: farg3
end subroutine

subroutine swigc_TrilinosSolver_setup_solver(farg1, farg2) &
bind(C, name="swigc_TrilinosSolver_setup_solver")
use, intrinsic :: ISO_C_BINDING
import :: SwigClassWrapper
type(SwigClassWrapper) :: farg1
type(SwigClassWrapper) :: farg2
end subroutine

subroutine swigc_TrilinosSolver_solve(farg1, farg2, farg3) &
bind(C, name="swigc_TrilinosSolver_solve")
use, intrinsic :: ISO_C_BINDING
import :: SwigClassWrapper
type(SwigClassWrapper) :: farg1
type(SwigClassWrapper) :: farg2
type(SwigClassWrapper) :: farg3
end subroutine

subroutine swigc_TrilinosSolver_finalize(farg1) &
bind(C, name="swigc_TrilinosSolver_finalize")
use, intrinsic :: ISO_C_BINDING
import :: SwigClassWrapper
type(SwigClassWrapper) :: farg1
end subroutine

subroutine swigc_delete_TrilinosSolver(farg1) &
bind(C, name="swigc_delete_TrilinosSolver")
use, intrinsic :: ISO_C_BINDING
import :: SwigClassWrapper
type(SwigClassWrapper) :: farg1
end subroutine

  subroutine swigc_assignment_TrilinosSolver(self, other) &
     bind(C, name="swigc_assignment_TrilinosSolver")
   use, intrinsic :: ISO_C_BINDING
   import :: SwigClassWrapper
   type(SwigClassWrapper), intent(inout) :: self
   type(SwigClassWrapper), intent(in) :: other
  end subroutine
function swigc_new_TrilinosEigenSolver() &
bind(C, name="swigc_new_TrilinosEigenSolver") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: SwigClassWrapper
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_TrilinosEigenSolver_init__SWIG_0(farg1) &
bind(C, name="swigc_TrilinosEigenSolver_init__SWIG_0")
use, intrinsic :: ISO_C_BINDING
import :: SwigClassWrapper
type(SwigClassWrapper) :: farg1
end subroutine

subroutine swigc_TrilinosEigenSolver_init__SWIG_1(farg1, farg2) &
bind(C, name="swigc_TrilinosEigenSolver_init__SWIG_1")
use, intrinsic :: ISO_C_BINDING
import :: SwigClassWrapper
type(SwigClassWrapper) :: farg1
type(SwigClassWrapper) :: farg2
end subroutine

subroutine swigc_TrilinosEigenSolver_setup_matrix(farg1, farg2) &
bind(C, name="swigc_TrilinosEigenSolver_setup_matrix")
use, intrinsic :: ISO_C_BINDING
import :: SwigClassWrapper
type(SwigClassWrapper) :: farg1
type(SwigClassWrapper) :: farg2
end subroutine

subroutine swigc_TrilinosEigenSolver_setup_matrix_rhs(farg1, farg2) &
bind(C, name="swigc_TrilinosEigenSolver_setup_matrix_rhs")
use, intrinsic :: ISO_C_BINDING
import :: SwigClassWrapper
type(SwigClassWrapper) :: farg1
type(SwigClassWrapper) :: farg2
end subroutine

subroutine swigc_TrilinosEigenSolver_setup_operator__SWIG_0(farg1, farg2, farg3, farg4) &
bind(C, name="swigc_TrilinosEigenSolver_setup_operator__SWIG_0")
use, intrinsic :: ISO_C_BINDING
import :: SwigClassWrapper
type(SwigClassWrapper) :: farg1
type(C_FUNPTR), value :: farg2
type(SwigClassWrapper) :: farg3
type(SwigClassWrapper) :: farg4
end subroutine

subroutine swigc_TrilinosEigenSolver_setup_operator__SWIG_1(farg1, farg2, farg3) &
bind(C, name="swigc_TrilinosEigenSolver_setup_operator__SWIG_1")
use, intrinsic :: ISO_C_BINDING
import :: SwigClassWrapper
type(SwigClassWrapper) :: farg1
type(C_FUNPTR), value :: farg2
type(SwigClassWrapper) :: farg3
end subroutine

subroutine swigc_TrilinosEigenSolver_setup_operator_rhs__SWIG_0(farg1, farg2, farg3, farg4) &
bind(C, name="swigc_TrilinosEigenSolver_setup_operator_rhs__SWIG_0")
use, intrinsic :: ISO_C_BINDING
import :: SwigClassWrapper
type(SwigClassWrapper) :: farg1
type(C_FUNPTR), value :: farg2
type(SwigClassWrapper) :: farg3
type(SwigClassWrapper) :: farg4
end subroutine

subroutine swigc_TrilinosEigenSolver_setup_operator_rhs__SWIG_1(farg1, farg2, farg3) &
bind(C, name="swigc_TrilinosEigenSolver_setup_operator_rhs__SWIG_1")
use, intrinsic :: ISO_C_BINDING
import :: SwigClassWrapper
type(SwigClassWrapper) :: farg1
type(C_FUNPTR), value :: farg2
type(SwigClassWrapper) :: farg3
end subroutine

subroutine swigc_TrilinosEigenSolver_setup_solver(farg1, farg2) &
bind(C, name="swigc_TrilinosEigenSolver_setup_solver")
use, intrinsic :: ISO_C_BINDING
import :: SwigClassWrapper
type(SwigClassWrapper) :: farg1
type(SwigClassWrapper) :: farg2
end subroutine

subroutine swigc_TrilinosEigenSolver_solve(farg1, farg2, farg3) &
bind(C, name="swigc_TrilinosEigenSolver_solve")
use, intrinsic :: ISO_C_BINDING
import :: SwigClassWrapper
import :: SwigArrayWrapper
type(SwigClassWrapper) :: farg1
type(SwigArrayWrapper) :: farg2
type(SwigClassWrapper) :: farg3
end subroutine

subroutine swigc_TrilinosEigenSolver_finalize(farg1) &
bind(C, name="swigc_TrilinosEigenSolver_finalize")
use, intrinsic :: ISO_C_BINDING
import :: SwigClassWrapper
type(SwigClassWrapper) :: farg1
end subroutine

subroutine swigc_delete_TrilinosEigenSolver(farg1) &
bind(C, name="swigc_delete_TrilinosEigenSolver")
use, intrinsic :: ISO_C_BINDING
import :: SwigClassWrapper
type(SwigClassWrapper) :: farg1
end subroutine

  subroutine swigc_assignment_TrilinosEigenSolver(self, other) &
     bind(C, name="swigc_assignment_TrilinosEigenSolver")
   use, intrinsic :: ISO_C_BINDING
   import :: SwigClassWrapper
   type(SwigClassWrapper), intent(inout) :: self
   type(SwigClassWrapper), intent(in) :: other
  end subroutine
 end interface


contains
 ! FORTRAN PROXY CODE
function new_TrilinosSolver() &
result(self)
use, intrinsic :: ISO_C_BINDING
type(TrilinosSolver) :: self
type(SwigClassWrapper) :: fresult 

fresult = swigc_new_TrilinosSolver()
self%swigdata = fresult
end function

subroutine swigf_TrilinosSolver_init__SWIG_0(self)
use, intrinsic :: ISO_C_BINDING
class(TrilinosSolver), intent(inout) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
call swigc_TrilinosSolver_init__SWIG_0(farg1)
end subroutine

subroutine swigf_TrilinosSolver_init__SWIG_1(self, comm)
use, intrinsic :: ISO_C_BINDING
class(TrilinosSolver), intent(inout) :: self
type(TeuchosComm) :: comm
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = comm%swigdata
call swigc_TrilinosSolver_init__SWIG_1(farg1, farg2)
end subroutine

subroutine swigf_TrilinosSolver_setup_matrix(self, a)
use, intrinsic :: ISO_C_BINDING
class(TrilinosSolver), intent(inout) :: self
type(TpetraCrsMatrix) :: a
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = a%swigdata
call swigc_TrilinosSolver_setup_matrix(farg1, farg2)
end subroutine

subroutine swigf_TrilinosSolver_setup_operator__SWIG_0(self, callback, domainmap, rangemap)
use, intrinsic :: ISO_C_BINDING
class(TrilinosSolver), intent(inout) :: self
type(C_FUNPTR), intent(in), value :: callback
type(TpetraMap) :: domainmap
type(TpetraMap) :: rangemap
type(SwigClassWrapper) :: farg1 
type(C_FUNPTR) :: farg2 
type(SwigClassWrapper) :: farg3 
type(SwigClassWrapper) :: farg4 

farg1 = self%swigdata
farg2 = callback
farg3 = domainmap%swigdata
farg4 = rangemap%swigdata
call swigc_TrilinosSolver_setup_operator__SWIG_0(farg1, farg2, farg3, farg4)
end subroutine

subroutine swigf_TrilinosSolver_setup_operator__SWIG_1(self, callback, domainmap)
use, intrinsic :: ISO_C_BINDING
class(TrilinosSolver), intent(inout) :: self
type(C_FUNPTR), intent(in), value :: callback
type(TpetraMap) :: domainmap
type(SwigClassWrapper) :: farg1 
type(C_FUNPTR) :: farg2 
type(SwigClassWrapper) :: farg3 

farg1 = self%swigdata
farg2 = callback
farg3 = domainmap%swigdata
call swigc_TrilinosSolver_setup_operator__SWIG_1(farg1, farg2, farg3)
end subroutine

subroutine swigf_TrilinosSolver_setup_solver(self, paramlist)
use, intrinsic :: ISO_C_BINDING
class(TrilinosSolver), intent(inout) :: self
type(ParameterList) :: paramlist
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = paramlist%swigdata
call swigc_TrilinosSolver_setup_solver(farg1, farg2)
end subroutine

subroutine swigf_TrilinosSolver_solve(self, rhs, lhs)
use, intrinsic :: ISO_C_BINDING
class(TrilinosSolver), intent(in) :: self
type(TpetraMultiVector) :: rhs
type(TpetraMultiVector) :: lhs
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 
type(SwigClassWrapper) :: farg3 

farg1 = self%swigdata
farg2 = rhs%swigdata
farg3 = lhs%swigdata
call swigc_TrilinosSolver_solve(farg1, farg2, farg3)
end subroutine

subroutine swigf_TrilinosSolver_finalize(self)
use, intrinsic :: ISO_C_BINDING
class(TrilinosSolver), intent(inout) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
call swigc_TrilinosSolver_finalize(farg1)
end subroutine

subroutine delete_TrilinosSolver(self)
use, intrinsic :: ISO_C_BINDING
class(TrilinosSolver), intent(inout) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
if (self%swigdata%mem == SWIG_OWN) then
call swigc_delete_TrilinosSolver(farg1)
end if
self%swigdata%ptr = C_NULL_PTR
self%swigdata%mem = SWIG_NULL
end subroutine

  subroutine swigf_assignment_TrilinosSolver(self, other)
   use, intrinsic :: ISO_C_BINDING
   class(TrilinosSolver), intent(inout) :: self
   type(TrilinosSolver), intent(in) :: other
   call swigc_assignment_TrilinosSolver(self%swigdata, other%swigdata)
  end subroutine
function new_TrilinosEigenSolver() &
result(self)
use, intrinsic :: ISO_C_BINDING
type(TrilinosEigenSolver) :: self
type(SwigClassWrapper) :: fresult 

fresult = swigc_new_TrilinosEigenSolver()
self%swigdata = fresult
end function

subroutine swigf_TrilinosEigenSolver_init__SWIG_0(self)
use, intrinsic :: ISO_C_BINDING
class(TrilinosEigenSolver), intent(inout) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
call swigc_TrilinosEigenSolver_init__SWIG_0(farg1)
end subroutine

subroutine swigf_TrilinosEigenSolver_init__SWIG_1(self, comm)
use, intrinsic :: ISO_C_BINDING
class(TrilinosEigenSolver), intent(inout) :: self
type(TeuchosComm) :: comm
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = comm%swigdata
call swigc_TrilinosEigenSolver_init__SWIG_1(farg1, farg2)
end subroutine

subroutine swigf_TrilinosEigenSolver_setup_matrix(self, a)
use, intrinsic :: ISO_C_BINDING
class(TrilinosEigenSolver), intent(inout) :: self
type(TpetraCrsMatrix) :: a
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = a%swigdata
call swigc_TrilinosEigenSolver_setup_matrix(farg1, farg2)
end subroutine

subroutine swigf_TrilinosEigenSolver_setup_matrix_rhs(self, m)
use, intrinsic :: ISO_C_BINDING
class(TrilinosEigenSolver), intent(inout) :: self
type(TpetraCrsMatrix) :: m
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = m%swigdata
call swigc_TrilinosEigenSolver_setup_matrix_rhs(farg1, farg2)
end subroutine

subroutine swigf_TrilinosEigenSolver_setup_operator__SWIG_0(self, callback, domainmap, rangemap)
use, intrinsic :: ISO_C_BINDING
class(TrilinosEigenSolver), intent(inout) :: self
type(C_FUNPTR), intent(in), value :: callback
type(TpetraMap) :: domainmap
type(TpetraMap) :: rangemap
type(SwigClassWrapper) :: farg1 
type(C_FUNPTR) :: farg2 
type(SwigClassWrapper) :: farg3 
type(SwigClassWrapper) :: farg4 

farg1 = self%swigdata
farg2 = callback
farg3 = domainmap%swigdata
farg4 = rangemap%swigdata
call swigc_TrilinosEigenSolver_setup_operator__SWIG_0(farg1, farg2, farg3, farg4)
end subroutine

subroutine swigf_TrilinosEigenSolver_setup_operator__SWIG_1(self, callback, domainmap)
use, intrinsic :: ISO_C_BINDING
class(TrilinosEigenSolver), intent(inout) :: self
type(C_FUNPTR), intent(in), value :: callback
type(TpetraMap) :: domainmap
type(SwigClassWrapper) :: farg1 
type(C_FUNPTR) :: farg2 
type(SwigClassWrapper) :: farg3 

farg1 = self%swigdata
farg2 = callback
farg3 = domainmap%swigdata
call swigc_TrilinosEigenSolver_setup_operator__SWIG_1(farg1, farg2, farg3)
end subroutine

subroutine swigf_TrilinosEigenSolver_setup_operator_rhs__SWIG_0(self, callback, domainmap, rangemap)
use, intrinsic :: ISO_C_BINDING
class(TrilinosEigenSolver), intent(inout) :: self
type(C_FUNPTR), intent(in), value :: callback
type(TpetraMap) :: domainmap
type(TpetraMap) :: rangemap
type(SwigClassWrapper) :: farg1 
type(C_FUNPTR) :: farg2 
type(SwigClassWrapper) :: farg3 
type(SwigClassWrapper) :: farg4 

farg1 = self%swigdata
farg2 = callback
farg3 = domainmap%swigdata
farg4 = rangemap%swigdata
call swigc_TrilinosEigenSolver_setup_operator_rhs__SWIG_0(farg1, farg2, farg3, farg4)
end subroutine

subroutine swigf_TrilinosEigenSolver_setup_operator_rhs__SWIG_1(self, callback, domainmap)
use, intrinsic :: ISO_C_BINDING
class(TrilinosEigenSolver), intent(inout) :: self
type(C_FUNPTR), intent(in), value :: callback
type(TpetraMap) :: domainmap
type(SwigClassWrapper) :: farg1 
type(C_FUNPTR) :: farg2 
type(SwigClassWrapper) :: farg3 

farg1 = self%swigdata
farg2 = callback
farg3 = domainmap%swigdata
call swigc_TrilinosEigenSolver_setup_operator_rhs__SWIG_1(farg1, farg2, farg3)
end subroutine

subroutine swigf_TrilinosEigenSolver_setup_solver(self, paramlist)
use, intrinsic :: ISO_C_BINDING
class(TrilinosEigenSolver), intent(inout) :: self
type(ParameterList) :: paramlist
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = paramlist%swigdata
call swigc_TrilinosEigenSolver_setup_solver(farg1, farg2)
end subroutine

subroutine swigf_TrilinosEigenSolver_solve(self, eigenvalues, lhs)
use, intrinsic :: ISO_C_BINDING
class(TrilinosEigenSolver), intent(in) :: self
real(C_DOUBLE), dimension(:), target, intent(inout) :: eigenvalues
real(C_DOUBLE), pointer :: farg2_view
type(TpetraMultiVector) :: lhs
type(SwigClassWrapper) :: farg1 
type(SwigArrayWrapper) :: farg2 
type(SwigClassWrapper) :: farg3 

farg1 = self%swigdata
farg2_view => eigenvalues(1)
farg2%data = c_loc(farg2_view)
farg2%size = size(eigenvalues)
farg3 = lhs%swigdata
call swigc_TrilinosEigenSolver_solve(farg1, farg2, farg3)
end subroutine

subroutine swigf_TrilinosEigenSolver_finalize(self)
use, intrinsic :: ISO_C_BINDING
class(TrilinosEigenSolver), intent(inout) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
call swigc_TrilinosEigenSolver_finalize(farg1)
end subroutine

subroutine delete_TrilinosEigenSolver(self)
use, intrinsic :: ISO_C_BINDING
class(TrilinosEigenSolver), intent(inout) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
if (self%swigdata%mem == SWIG_OWN) then
call swigc_delete_TrilinosEigenSolver(farg1)
end if
self%swigdata%ptr = C_NULL_PTR
self%swigdata%mem = SWIG_NULL
end subroutine

  subroutine swigf_assignment_TrilinosEigenSolver(self, other)
   use, intrinsic :: ISO_C_BINDING
   class(TrilinosEigenSolver), intent(inout) :: self
   type(TrilinosEigenSolver), intent(in) :: other
   call swigc_assignment_TrilinosEigenSolver(self%swigdata, other%swigdata)
  end subroutine

end module
